### ISSUE TITLE
@JsonSerializable() in not working in generated classes;

### ISSUE THREAD

**Issue by topperspal** [google/json_serializable.dart#1012]
I want to build toJson() abd fromJson()  for a generated class ( A model classs generated by some other generator ),

how can i achieve this?

**Comment by kevmoo** [comment]
At the moment, this is not supported!

**Comment by topperspal** [comment]
I have created a package that generates code for form management and also creates a DataClass for the form. I want to make the DataClasses generate code for Json serializable code also and also don't want to reinvent the wheel so I want to use JsonSerializable directly inside the generated DataClass

**Comment by t-beckmann** [comment]
Don‘t understand. Can‘t you just generate @JsonKey, etc. annotations in your generator and run json_serializable over the result?

**Comment by kevmoo** [comment]
See https://pub.dev/packages/build_config#adjusting-builder-ordering

**Comment by definitelyme** [comment]
> See https://pub.dev/packages/build_config#adjusting-builder-ordering

The doc you supplied did not give a proper example of how to use the `runs_before` key. Can you provide an example using the `json_serialiable` and `freezed` package - assuming freezed is expected to run before `json_serializable`
