### ISSUE TITLE
Using `protobuf` with this package

### ISSUE THREAD

**Issue by varunbhalerao56** [google/json_serializable.dart#1017]
Hello, I am using `protobuf` and I want to use the same models in my own custom models. There is a way to convert the protobuf method `fromJson`  but the way it is done is different. Is there any way I can change it for a specific field? 

Currently, this is the error I am getting.

```
Expecting a `fromJson` constructor with exactly one positional parameter. The only extra parameters allowed are functions of the form `T Function(Object?) fromJsonT` where `T` is a type parameter of the target type.
package:npsg_store/gen/domain.pb.dart:1506:19
     ╷
1506 │   factory Address.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);
     │                   ^^^^^^^^
     ╵
```

**Comment by kevmoo** [comment]
There's really no path here that isn't pretty disruptive. Sorry.

**Comment by kunalgrover05** [comment]
Actually this is not really hard, just inconvenient to use them together. 

The workaround is to manually annotate all fields which are Protobuf generated models with a custom method. You will need to do it once per model.
```
ProtobufModel protobufFromJson(String json) {
    return ProtobufModel.fromJson(json);
}

String protobufToJson(ProtobufModel protobufModel) {
    return protoBufModel.writeToJson();
}


@JsonSerializable()
class MyClass {
  final DateTime timestamp; // this will get auto-serialized

  @JsonKey(fromJson: protobufFromJson, toJson: protobufToJson)
  final ProtobufModel protobufModel;
}
```

**Comment by varunbhalerao56** [comment]
@kunalgrover05 thanks a lot!
