### ISSUE TITLE
Unclear defaultValue warning on matching defaults in constructor

### ISSUE THREAD

**Issue by micimize** [google/json_serializable.dart#1018]
Generating json serialization code with `defaultValue: 1` produces a warning when the same value is supplied in the constructor. This warning is likely meant to indicate to the developer that they don't need the annotation parameter, but looks more like an actual behavior-effecting or value-mismatch error.

Logged Warnings:
```
[WARNING] json_serializable:json_serializable on lib/modules/weight_lifting/weighted_set.dart:
The constructor parameter for `count` has a default value `1`, but the `JsonKey.defaultValue` value `1` will be used for missing or `null` values in JSON decoding.
[WARNING] json_serializable:json_serializable on lib/modules/clock/duration/duration_data_class.dart:
```

Classes look something like:
```dart
@JsonSerializable()
class ValueType {

  const ValueType({this.value = 1});

  factory ValueType.fromJson(Map<String, dynamic> json) =>
      _$ValueTypeFromJson(json);

  @override

  @JsonKey(defaultValue: 1)
  final int value;
}
```

### dart/flutter/dependency context:
```bash
$ dart --version
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"

$ flutter --version                                                       
Flutter 2.7.0-3.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fc7015e35a (3 days ago) • 2021-10-27 15:18:41 -0700
Engine • revision a75e3b80f9
Tools • Dart 2.15.0 (build 2.15.0-178.1.beta)
```

```yaml
  # pubspec.lock
  json_annotation:
    dependency: "direct main"
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  json_serializable:
    dependency: "direct dev"
    description:
      name: json_serializable
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.1"
```

**Comment by micimize** [comment]
Nevermind, for some reason I saw this error after upgrading but it was a result of build_runner failing due to `json_annotation:` in my `pubspec.yaml`. This warning no longer shows up

```
The version constraint "any" on json_annotation allows versions before 4.3.0 which is not allowed.
```

**Comment by danallen88** [comment]
This is still an issue for me, even using 

```
json_annotation: ^4.3.0
json_serializable: ^6.0.1
```

If I run `build_runner` a second time, the cached build doesn't output these warnings.  It's only after making a change that invalidates that cache do I get these warnings; I expect you're in the same situation, but it seems like this isn't resolved.

**Comment by micimize** [comment]
@danallen88 ah indeed could be the issue. Lets leave your issue as the main tracking one anyhow

**Comment by micimize** [comment]
Closed by https://github.com/google/json_serializable.dart/pull/1027
