### ISSUE TITLE
Failed to recognize `json_annotation` from packages after 6.0.0

### ISSUE THREAD

**Issue by AlexV525** [google/json_serializable.dart#1020]
## Summary

Use `json_annotation` in a package with export is no longer valid after `json_serializable` 6.0.0 since the `build_runner` will complain the error:

```
You are missing a required dependency on json_annotation in the "dependencies" section of your pubspec with a lower bound of at least "4.3.0".
```

## Step to reproduce

1. Clone the project https://github.com/AlexV525/json_annotation_test.
2. Run `build_runner` build in the `project_a` with no issues.
3. Change the `json_serializable` dependency in both package and project to 6.0.0.
4. Change the `json_annotation` to 4.3.0 in the base package, but not with the project.
4. Rerun `build_runner` build and the error occurred.

## Environments

Flutter: 2.5.3

**Comment by AlexV525** [comment]
cc @kevmoo

**Comment by kevmoo** [comment]
Which version of Flutter are you using?

**Comment by AlexV525** [comment]
> Which version of Flutter are you using?

Sorry for not providing this, it's 2.5.3. Added to the top comment.

**Comment by agrawalharsh90** [comment]
Same issue is also coming for latest version `json_serializable: ^6.0.1`

**Comment by kevmoo** [comment]
https://github.com/AlexV525/json_annotation_test/pull/1

No issue for me. Which version of Flutter  are you guys using?

**Comment by AlexV525** [comment]
> [AlexV525/json_annotation_test#1](https://github.com/AlexV525/json_annotation_test/pull/1)
> 
> No issue for me. Which version of Flutter are you guys using?

Not really, following the step 4: `Change the json_annotation to 4.3.0 in the base package, but not with the project.`, which means no `json_annotation` for the `project_a`.

**Comment by ookami-kb** [comment]
@kevmoo but for project-A it's a transitive dependency, so it's present and up to date in `pubspec.lock`.

We have the same problem. With one weird detail. We have 3 packages: `core`, `package_a` and `package_b`, with `package_a` and `package_b` depending on `core`, and `core` is the one providing `json_annotation` dependency transitively. 

When I run flutter build in `package_a` there's an error that was mentioned in the issue.

When I run flutter build in `package_b` there's only a warning:

```
[WARNING] json_serializable:json_serializable on lib/api/dto/tasks.dart:
Could not read the "pubspec.yaml` file associated with this package. Usage of package:json_annotation could not be verified.
```

and code generation works.

Before the update it was working for both packages.

**Comment by kevmoo** [comment]
Hrm...I never planned on folks exporting `json_annotation`

This makes...a lot of things complex.

Will need to noodle on it.

**Comment by ookami-kb** [comment]
AFAIK, https://github.com/rrousselGit/freezed works in the same way by re-exporting `json_annotation`, so it will break their use case as well. @rrousselGit

**Comment by kevmoo** [comment]
Yeah, builders requiring other builders gets tricky. It's tough to support unintended composition.

**Comment by AlexV525** [comment]
> This makes...a lot of things complex.

More complex thing here is after we upgrade to 6.x, all of our project (about 5+) are broken because the transparentive package dependant is invalid from our base package, then we'll need to manually define all pubspecs to achieve the same behavior. This IS A HUGE BREAKING BEHAVIOR that will cost more time and work to waste, and the old  version still respects the base package's exports.

Speaking of these behaviors, I'm getting more and more things like this from Dart, like broken dependencies graph, reject symlinks without any announcements. Please be more careful when constrainting something.

**Comment by kevmoo** [comment]
@AlexV525 – json_serializable was a v6 – a major version change – which signals breaking changes.

I was explicit in the changelog about the new behavior. This package was never designed to support an exported annotation. The dependency between json_serializable and json_annotation is very tight and has caused many folks many breaks in the past do to published packages.

**Comment by AlexV525** [comment]
Well, nevermind, because it's already changed. Could we have supports with this, now let's say, feature?

**Comment by ookami-kb** [comment]
> Hrm...I never planned on folks exporting `json_annotation`
> 
> This makes...a lot of things complex.
> 
> Will need to noodle on it.

Just out of curiosity – why require the specific `json_annotation` version explicitly?

Breaking changes in builder are marked as major version changes in builder itself, why do you need to make sure that there's this specific version in `pubspec.yaml`? Can it be at least a check for `pubspeck.lock`?

For us, it's not about "builders requiring other builders", but rather "pinning" the version once in `core` package and using it in dependant packages to avoid repeating the same shared dependencies.

**Comment by AlexV525** [comment]
> For us, it's not about "builders requiring other builders", but rather "pinning" the version once in `core` package and using it in dependant packages to avoid repeating the same shared dependencies.

That's exactly what we're doing. It's too heavy to depend on annotations in everywhere.

**Comment by kevmoo** [comment]
This issue is w/ published packages.

You may build w/ `json_annotation` v2.3` but a user of a package may only get `v2.0` - which will break.

I guess we could get ever more clever and look for a package with `publish_to: none` in the pubspec. Hrm...

**Comment by ookami-kb** [comment]
But if the code in a public package is already generated, how does it matter if it was generated with `json_annotation` `2.3` or `2.0` (especially when there were no breaking changes in `json_annotation` versions)? The generated code doesn't depend on annotations themselves, or does it?

**Comment by ookami-kb** [comment]
And if I get the problem correctly, it's not specific to code generation packages. 

E.g. I can specify `smth: ^4.0.0` in my published package, but actually use API from `4.1.0`. And end-user will have `smth: 4.0.0` which will formally pass the requirement but will break the compilation. 

So should 1 package fix the general ecosystem problem (by breaking the valid use cases at the same time)? Or is the root problem in something different?

**Comment by kevmoo** [comment]
I should likely document this better.

Here's the issue – explicitly.

My dependency on `json_annotation` is `^4.0.0`
`pub get` gives me `4.3.0` – great.
I generate code – that requires `4.3.0` – because it needs the new `enum` helpers.
Tests all run fine locally.

Some other user depends on my package, but because of their SDK version (or something else) `pub get` only gives them `json_annotation` `4.2.0`.

Now they get a runtime failure in code they didn't write – and they don't know why!

**Comment by ookami-kb** [comment]
Yeah, but isn't it the same I mentioned in https://github.com/google/json_serializable.dart/issues/1020#issuecomment-956468339? So it's not specific neither to `json_annotation` nor to code generation at all.

If I'm the author of the public package `smth` that depends on `json_annotation` and I **claim** that my package works with `json_annotation: ^4.0.0` it's **my** responsibility to ensure that it actually works with the lowest bound. It's in no way the problem of `json_annotation` itself.

It could be useful to provide some feedback to me as the author of package `smth` that I use some API that is not available in the lowest bound – _something like this_ is done in native Android, where IDE warns if I use some API that is not available in the `minSdkVersion` specified in `build.gradle` – but it's imho just a nice-to-have feature, the responsibility is still on the author of package `smth`.

**Comment by kevmoo** [comment]
@ookami-kb – sure!

But in this case we're running `json_serializable` on a child package, right?

`json_serializable` shouldn't make assumptions – at least IMHO

**Comment by ookami-kb** [comment]
Yeah, but the error will not be in `json_serializable`, right? It will be pointing to package `smth` as it is trying to use something not available. So the valid case is to open the issue in `smth` package as it's not following the contract with a minimal support version.

Since the code in `smth` is already generated, it won't be touched by `json_serializable` as far as I understand.

**Comment by AlexV525** [comment]
> Some other user depends on my package, but because of their SDK version (or something else) `pub get` only gives them `json_annotation` `4.2.0`.
> 
> Now they get a runtime failure in code they didn't write – and they don't know why!

That's how pub resolve gets worked, isn't it? As far as you can check the transparent dependency from `.dart_tools/package_config.json`, you'll get the resolved version the ensure whether the `json_annotation` is at the right stage.

**Comment by AlexV525** [comment]
> `json_serializable` shouldn't make assumptions – at least IMHO

`json_serializable` is laid in the `dev_dependencies`, it would be okay to define it in projects. But the `json_annotation` is laid in `dependencies`, at least it should be respected when it came across packages.

**Comment by AlexV525** [comment]
TBH, if you're indicating that it scopes to avoid the "feature" or the broken dependencies graph of the pub packages management, please improve pub. It should have some explicit keys or annotations to use a transparent dependency.

**Comment by AlexV525** [comment]
I don't think leaving this alone is a valid solution. Filed another issue for this.
