### ISSUE TITLE
toJson and fromJson method sometimes can not be correctly generate

### ISSUE THREAD

**Issue by jinfagang** [google/json_serializable.dart#1022]
I have a classes like this:

```
import 'dart:convert';
import 'package:flutter_mqtt/abstraction/models/BaseMessage.dart';

import 'enums/MessageType.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:copy_with_extension/copy_with_extension.dart';

part 'TypingMessage.g.dart';

@JsonSerializable()
@CopyWith()
class TypingMessage extends BaseMessage{
  final String id;
  final MessageType type;
  final String fromId;
  final String fromName;
  final String? roomId;
  @JsonKey(fromJson: _isTypingFromJson)
  final bool isTyping;
  TypingMessage({
    required this.id,
    required this.type,
    required this.fromId,
    required this.fromName,
    this.roomId,
    required this.isTyping,
  }):super(id: id, fromId: fromId, fromName: fromName, type: type);

  factory TypingMessage.fromJson(Map<String, dynamic> json) => _$TypingMessageFromJson(json);
  factory TypingMessage.fromString(String jsonString) => _$TypingMessageFromJson(json.decode(jsonString));
  Map<String, dynamic> toJson() => _$TypingMessageToJson(this);


  static bool _isTypingFromJson(String boolStr) =>
      boolStr.toLowerCase() == "true";
}

```

It generate something like this:

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'TypingMessage.dart';

// **************************************************************************
// CopyWithGenerator
// **************************************************************************

extension TypingMessageCopyWith on TypingMessage {
  TypingMessage copyWith({
    String? fromId,
    String? fromName,
    String? id,
    bool? isTyping,
    String? roomId,
    MessageType? type,
  }) {
    return TypingMessage(
      fromId: fromId ?? this.fromId,
      fromName: fromName ?? this.fromName,
      id: id ?? this.id,
      isTyping: isTyping ?? this.isTyping,
      roomId: roomId ?? this.roomId,
      type: type ?? this.type,
    );
  }
}


```

where is toJson and fromJson??? I already set exxplicit_to_json to True.

and **this is only happened after I upgraded json_serialize**

**Comment by kevmoo** [comment]
@jinfagang – do you have a dependency on `json_serializable` in your pubspec?

**Comment by jinfagang** [comment]
@kevmoo Of course I have, other models file can generate, except this one. so weired.

**Comment by kevmoo** [comment]
Very weird!

Did you run with `--verbose` anything in the log?

**Comment by jinfagang** [comment]
@kevmoo I am recently manually copied generate code to that file with previous version of json serializer, after I implemented all features in my app, I will post detailed log here

**Comment by rbrus** [comment]
@kevmoo @jinfagang I am experiencing the same issue. Each time after running 'flutter pub run build_runner build' I need to manually fix the 'toJson' part in the *.g.dart files.

My classes are fairly simple (I cannot copy them) but they look like this:

XYZ({
    required String name,
    required String description,
    required List<ABC> abcList,
    required this.opqList,
    required this.date,
  }) : super(
          name: name,
          abcList: abcList,
        );

final List<OPQ> opqList;
final DateTime date;

All classes XYZ, ABC and OPQ are all @JsonSerializable() and have the corresponding *.g.part file.

The fromJson is correctly generated for all classes and subclasses. It calls map(*.fromJson()) over each element on the list. 
However, in the toJson section, it doesn't add map() in the other way around toJson(). It actually, treats the lists in the same way as a normal String or int variable:

 'name': instance.name,
 'description': instance.description,
 'abcList': instance.abcList, // it should be maped
 'opqList': instance.opqList, // it should be maped

So what I do, I simply fix it by adding ".map((e) => e.toJson()).toList()":

 'name': instance.name,
 'description': instance.description,
 'abcList': instance.abcList.map((e) => e.toJson()).toList(),
 'opqList': instance.opqList.map((e) => e.toJson()).toList(),

And it works.

**Comment by leoshusar** [comment]
@rbrus I tried your case and it happens when you have dynamic list. If you use `List<T>` instead of just `List` and `explicitToJson: true`, it will correctly add `.map((e) => e.toJson()).toList()`.

I don't know if this is intended or not though.

**Comment by kevmoo** [comment]
`explicitToJson` is what you want.
