### ISSUE TITLE
JsonKey.defaultValue not recognizing constructor default value

### ISSUE THREAD

**Issue by danallen88** [google/json_serializable.dart#1023]
As mentioned in #1018 and in  https://github.com/rrousselGit/freezed/issues/503, it seems that the default annotations provided by the freezed library are not recognized by json_serializable.  

flutter doctor:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] Connected device (2 available)

• No issues found!
```

and with
```
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  freezed_annotation: ^0.14.2
```

Running `flutter pub run build_runner build --delete-conflicting-outputs` I get the following output:

> [WARNING] json_serializable:json_serializable on lib/src/infrastructure/app_settings/model/app_settings_data.dart:
The constructor parameter for `username` has a default value `''`, but the `JsonKey.defaultValue` value `''` will be used for missing or `null` values in JSON decoding.

Relevant class:
```dart

@freezed
class AppSettingsData with _$AppSettingsData {
  AppSettingsData._();
  factory AppSettingsData({
    @Default('') String username,
  }) = _AppSettingsData;

  factory AppSettingsData.fromJson(Map<String, dynamic> json) =>
      _$AppSettingsDataFromJson(json);
}
```

**Comment by kevmoo** [comment]
Freezed is a completely separate package from json_serializable. It builds on json_serializable. There isn't anything I can do here!

**Comment by micimize** [comment]
@kevmoo please refer to #1018 – this is not a purely `freezed` issue, it is an issue caused by having a `JsonKey` with the same default as the constructor, like so:
```dart
```dart
@JsonSerializable()
class ValueType {

  const ValueType({this.value = 1});

  factory ValueType.fromJson(Map<String, dynamic> json) =>
      _$ValueTypeFromJson(json);

  @override

  @JsonKey(defaultValue: 1)
  final int value;
}
/// logged error:
/// The constructor parameter for `count` has a default value `1`, but the `JsonKey.defaultValue` value `1`
/// will be used for missing or `null` values in JSON decoding.
```
> This warning is likely meant to indicate to the developer that they don't need the annotation parameter, but looks more like an actual behavior-effecting or value-mismatch error

Thus it is not merely a `freezed` issue. I think it is fine to leave the warning, but it shoud be more precise IMO, especially when the defaults match.

**Comment by rrousselGit** [comment]
Indeed Freezed is unrelated to this issue, it only highlights the problem. 

The problem is a false positive with the warning. The warning shouldn't appear when the default value passed to the constructor and the default value passed to JsonKey are identical

**Comment by kevmoo** [comment]
> Indeed Freezed is unrelated to this issue, it only highlights the problem.
> 
> The problem is a false positive with the warning. The warning shouldn't appear when the default value passed to the constructor and the default value passed to JsonKey are identical

That I agree with. I could imagine a "hint" that says "hey, you can drop the default value in `JsonKey` – the constructor handle that.

I'd open a new issue to cover that!

**Comment by SunlightBro** [comment]
@kevmoo I tried myself on a PR #1027 for this hint.
But I forgot to sign the cla first, could you "Re-run" the workflow ?
