### ISSUE TITLE
Automatically add 'part 'myobject.g.part' to source file

### ISSUE THREAD

**Issue by g-apparence** [google/json_serializable.dart#1026]
Hi,
currently if you forget to add 
```dart
part 'myobject.g.part
```
you will have an error at the end of the process

could we : 
- detect the user forgot this earlier
- add it automatically  to source file. 
(I've made something like this on the gate plugin. That's maybe not the best solution and there must be a cleaner solution. But this works and remove a lot of useless rebuild because you forgot this line.)

**Comment by kevmoo** [comment]
I get the desire here, but we have a STRICT model where we don't touch user code.
