### ISSUE TITLE
How to ignore fields

### ISSUE THREAD

**Issue by Lanhaoo** [google/json_serializable.dart#1033]
How to ignore fields. For example,.

@ jsonKey (name: 'name').
Rope? First name.

@ JsonKey (name: 'questonNumber').
INT? Question number.

@ JsonKey (name: 'shareType').
Rope? ShareType .

/ / this field is a field I added myself, and the server will not return it, nor will the server return it. I have also given the default value.
Bool isExpanded=False .

For now, when I execute.

Flutter packages pub run build_runner build.

The field is then converted. However, because the server did not return this field, it is empty and the program error

<img width="957" alt="截屏2021-11-16 下午3 41 38" src="https://user-images.githubusercontent.com/38837048/141941909-56bb45ed-a1b9-4d03-8a78-bcada3bbf991.png">

<img width="734" alt="截屏2021-11-16 下午3 41 52" src="https://user-images.githubusercontent.com/38837048/141941925-b64e64a6-3d9b-41b4-a700-f34937ce1894.png">

**Comment by Mister-Hope** [comment]
```
ignoreUnannotated → bool?
When true, only fields annotated with JsonKey will have code generated. [...]
```

See https://pub.flutter-io.cn/documentation/json_annotation/latest/json_annotation/JsonSerializable-class.html

**Comment by kevmoo** [comment]
Also: https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/ignore.html
