### ISSUE TITLE
Convert DateTime Type to ISODate MongoDB with  json_serializable 

### ISSUE THREAD

**Issue by YouSour** [google/json_serializable.dart#1037]
hi , i am using MongoDB as my backend , i don't have any clues how can i convert **DateTime type** to **ISODate MongoDB** , i try to look through document and searching , i can't find anything about it , do you have any idea about this ? thank in advance

**Comment by kevan-ivadolabs** [comment]
hi @YouSour ,

you could probably build a custom converter, there is an example here: https://github.com/google/json_serializable.dart/blob/master/example/lib/json_converter_example.dart

**Comment by YouSour** [comment]
@kevan-ivadolabs thank you , solved 😄
