### ISSUE TITLE
Serialaze property some ways

### ISSUE THREAD

**Issue by tremp-m** [google/json_serializable.dart#1041]
Hi
I can't find out how i can do one thing.
For example i have such class:

```
  class Dto{
    bool isTrue;
  }

```
i want have 2 conversion ways:
in first i want get 
  ```
{
    isTrue: true
  }
```

in second:

  ```
{
    isTrue: 1
  }
```

is it possible? thx

**Comment by ltropin** [comment]
Use **fromJson** (is static funtion class or Top level function) in **JsonKey** 
```dart
static bool _isTrueParse(Object value) {
    final intValue = int.tryParse(value.toString());
    if (intValue != null) {
      return intValue == 1;
    }
    return value as bool;
  }
```

Example:
```dart
@JsonKey(name: 'isTrue', fromJson: _isTrueParse)
bool isTrue;
```

**Comment by tremp-m** [comment]
> Use **fromJson** (is static funtion class or Top level function) in **JsonKey**
> 
> ```dart
> static bool _isTrueParse(Object value) {
>     final intValue = int.tryParse(value.toString());
>     if (intValue != null) {
>       return intValue == 1;
>     }
>     return value as bool;
>   }
> ```
> 
> Example:
> 
> ```dart
> @JsonKey(name: 'isTrue', fromJson: _isTrueParse)
> bool isTrue;
> ```
> 
> or create a custom JsonConverter for reusing

thx for reply, but i want backward converse toJson) (from DTO to json (2 variants))

**Comment by kevmoo** [comment]
https://github.com/google/json_serializable.dart/issues/1041#issuecomment-979704301 – this is right.

How do you want to encode it with `toJson`?

**Comment by tremp-m** [comment]
рлд

> [#1041 (comment)](https://github.com/google/json_serializable.dart/issues/1041#issuecomment-979704301) – this is right.
> 
> How do you want to encode it with `toJson`?

Sorry, but itsn't right for my case. I don't now how i can do this. I think that is impossable, but maybe i wrong? Therefore, I asked this question.
