### ISSUE TITLE
How to use with --build-filter?

### ISSUE THREAD

**Issue by duzenko** [google/json_serializable.dart#1054]
A few version back I could limit the scope of the generation to a particular folder with
```
flutter pub run build_runner build --delete-conflicting-outputs --build-filter 'lib/models/feed/*.dart'
```
Now whatever I try it either deletes generated files in other folders, complains about conflicts, or processes all folders
Please advise

**Comment by kevmoo** [comment]
@jakemac53 ?

**Comment by jakemac53** [comment]
I would need to know more information, as far as I am aware this option should still work fine.

> Now whatever I try it either deletes generated files in other folders

This is what `--delete-conflicting-outputs` does - if you are cloning a repo fresh and you check generated files into git (fine to do), you will want to regenerate all the files the first time most likely.

> complains about conflicts

This doesn't happen if you pass `--delete-conflicting-outputs` right? Or are you getting issues even with that?

> or processes all folders

Note that any file which is transitively imported by any input in your filter will also be generated (its a transitive input). So that can cause more things to be built than you might intend.

**Comment by duzenko** [comment]
Could be a one time glitch then
I quickly retried once again with a folder filter and it did not delete or complain about anything but nothing was changed too
I will reopen if it plays up again

**Comment by duzenko** [comment]
Occurred again. This command
`flutter pub run build_runner build --delete-conflicting-outputs --build-filter 'lib/api/domains/user/*.dart'`
while generating the code in the 'lib/api/domains/user' folder, deletes generated files in all other folders

**Comment by jakemac53** [comment]
Yes, `--delete-conflicting-outputs` is a global option - it doesn't only apply to the outputs built as a part of the `--build-filter`. This is something done before the build even starts.
 
 When using that option you would need to do a full build (without `--build-filter`) first, or else the other files won't be generated.

**Comment by duzenko** [comment]
What is the meaning of `--build-filter` then if it's not supposed to be producing adequate results with and without delete conflicting outputs?
Anyway, my issue is that sometimes it works, and then sometimes it does not. Today it worked in another folder.

**Comment by duzenko** [comment]
@jakemac53 please clarify how we can regenerate a subset of generated files (e.g. in a given subfolder) when only one or few files change without regenerating the entire project.

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/pull/3233 which moves docs for the feature from the changelog to a more discoverable place in our docs directory.

**Comment by StoneNan** [comment]
> @jakemac53 please clarify how we can regenerate a subset of generated files (e.g. in a given subfolder) when only one or few files change without regenerating the entire project.

So, is there any good solution, please 😵‍💫
