### ISSUE TITLE
_$CLASSFromJson to possibly receive an instance instead of creating a new one

### ISSUE THREAD

**Issue by zerobytes** [google/json_serializable.dart#1076]
Currently, the implementation of the _$FromJson method is always creating a new instance of that object.
But in many use cases I already have an instance and I just want to fill it with the data that I got from the server, instead of creating a new instance and eventually having to replace of my pointers to that old instance.

It could be a second, and optional, parameter making it use the given instance instead of creating a new one.

_$CLASSFromJson(json, this);

this way the boilerplate would contain something like
```dart

void fromJson(json)=>_$CLASSFromJson(json,this);

```

and finally the current instance would have it's fields populated with the data from that JSON.

**Comment by kevmoo** [comment]
See my comment in the PR.
