### ISSUE TITLE
Request for backpatch to json_serializable v3 to allow analyzer v1 (and source_gen v0.9 to allow dart_style v2)

### ISSUE THREAD

**Issue by evanweible-wf** [google/json_serializable.dart#1081]
Hello! We're working on upgrading our dart ecosystem to the latest of all dependencies, and one area we're stuck on right now is json_serializable. Since v4 outputs null-safe code, upgrading to it requires migrating to null-safety at the same time. We have stayed on v3 so far, but doing so precludes us from upgrading to analyzer v1, which in turn restricts our ability to upgrade a lot of other dependencies.

We'd really like to be able to take a more iterative approach to these dependency upgrades and null-safe migrations. If json_serializable v3 allowed analyzer v1 and source_gen v0.9 allowed dart_style v2, we'd be able to upgrade to the next major of the following packages _without_ also having to migrate to null-safety:

- analyzer
- build and build_*
- checked_yaml
- dart_style
- logging
- mockito
- pubspec_parse

And probably some more that we haven't enumerated yet.

I've opened PRs on my forks of this repo and source_gen to validate that json_serializable v3 is compatible with analyzer v1 and source_gen v0.9 is compatible with dart_style v2:

- https://github.com/evanweible-wf/json_serializable.dart/pull/1 (Note: the `ensure_build` step times out on Dart Stable, and I have no idea why. It passes locally on Stable.)
- https://github.com/evanweible-wf/source_gen/pull/1

If those back patches seem reasonable to you, I can open those PRs against the main repos once a base branch for those back patches exist. Let me know if there are any concerns with making these changes!

@kevmoo

**Comment by kevmoo** [comment]
I'd accept a PR against v3. I'll open a branch now you can send a PR against.

**Comment by kevmoo** [comment]
Use https://github.com/google/json_serializable.dart/tree/v3_x

**Comment by evanweible-wf** [comment]
Awesome, thanks Kevin! Do you you maintain source_gen, too? Does that back patch seem reasonable as well?

**Comment by kevmoo** [comment]
@evanweible-wf – I also work on source_gen. Happy to help there.

**Comment by evanweible-wf** [comment]
Thank you for the help Kevin!
