### ISSUE TITLE
Failed to serialize models after using `build_runner` 2.1.7 (`analyzer` 3.1.0)

### ISSUE THREAD

**Issue by AlexV525** [google/json_serializable.dart#1083]
Related to https://github.com/dart-lang/build/pull/3222.

## Step to reproduce

Run `dart run build_runner build --delete-conflicting-outputs`.

```dart
@JsonSerializable(
//  fieldRename: FieldRename.snake, // <- Uncomment this to see affects.
)
class TestJsonA {
  TestJsonA({required this.testFieldA});

  factory TestJsonA.fromJson(Map<String, dynamic> json) =>
      _$TestJsonAFromJson(json);

  final String testFieldA;

  Map<String, dynamic> toJson() => _$TestJsonAToJson(this);
}
```

## Logs

```
[INFO] Generating build script completed, took 458ms
[INFO] Reading cached asset graph completed, took 60ms
[INFO] Checking for updates since last build completed, took 465ms
[SEVERE] json_serializable:json_serializable on lib/model.dart:

Bad state: No element
[INFO] Running build completed, took 1.2s
[INFO] Caching finalized dependency graph completed, took 38ms
[SEVERE] Failed after 1.3s
```

## Environment

Dart version: 2.15.1

### Packages
analyzer: 3.1.0
build_runner: 2.1.7
json_annotation: 4.4.0
json_serializable: 6.1.3

**Comment by AlexV525** [comment]
/cc @jakemac53

Please, apply tests like `customers tests` across repositories, or for the `build_runner` that so many tools depend on.

**Comment by bardram** [comment]
I made a temporary fix by fixing the dependency to version `4.3.0` - like:

```
dependencies:
  flutter:
    sdk: flutter
    
  json_annotation: 4.3.0 # ^4.3.0
```

But this seems wrong, since a new version (4.4.0) is available?

**Comment by shilangyu** [comment]
Reverting `_fe_analyzer_shared` to `32.0.0` and `analyzer` to `3.0.0` also fixes this problem.

**Comment by kevmoo** [comment]
@scheglov – looks like something broken with analyzer `3.1.0`

**Comment by kevmoo** [comment]
@bardram – you're better off adding a constraint on `pkg:analyzer` to `<3.1.0`

**Comment by jakemac53** [comment]
> Please, apply tests like `customers tests` across repositories, or for the `build_runner` that so many tools depend on.

I filed https://github.com/dart-lang/build/issues/3236 to track possibly doing this, it would be a decent body of work to get it set up though. Note that the build packages don't appear to have been the root of the failure here, so it wouldn't have fixed this issue, but its anyways a good suggestion.

**Comment by scheglov** [comment]
It should be something like this:
```dart
T enumValueForDartObject<T>(
  DartObject source,
  List<T> items,
  String Function(T) name,
) {
  final index = source.getField('index')!.toIntValue()!;
  return items[index];
  // return items.singleWhere((v) => source.getField(name(v)) != null);
}
```

**Comment by kevmoo** [comment]
Yup. Working on a patch now!

**Comment by kevmoo** [comment]
https://github.com/google/json_serializable.dart/pull/1084

**Comment by kevmoo** [comment]
@scheglov – so this was "effectively" a breaking change. Perhaps undocumented, but certainly a break.

**Comment by shilangyu** [comment]
Thanks for a quick fix!

**Comment by Raphicci** [comment]
You guys were so fast to fix this, thanks a lot !
