### ISSUE TITLE
json_serializable different reference key

### ISSUE THREAD

**Issue by UnluckyY1** [google/json_serializable.dart#1085]
I'm asking a question and not found an similar post/issue for this.

I explain, I use json_serializable, but webservice provide some information of the same type of object by with different name keys, 

so is there anyway to specify the key name (fromJson) and the key name(toJson) ?

**Comment by kevmoo** [comment]
Trying using
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/readValue.html
