### ISSUE TITLE
jsonEncode an object that has a child object as a field that in turns references parent object

### ISSUE THREAD

**Issue by sajidbarcha** [google/json_serializable.dart#1087]
The issue is happening on Frontend, Flutter. 
Backend Facts: I am working with a Java/Spring backend which is employing JPA/Hibernate to CRUD data into a Postgres db. From my flutter app, I am trying to send a post request containing AppUser, which contains a field of type List of Address objects. An AppUser has a one-to-many relationship with Address entity. In order to leverage the power of JPA/Hibernate libraries on the backend, I am expected to include the child object (List of Address addresses) as a property of AppUser, and each element (an Address object) in the child property (List) also has a property of type AppUser called appUser. This is how JPA expects the data to arrive so it can stitch the relationships and insert data with property primary-key foreign-key relationships. 

On Flutter side, the **JsonCyclicError (Cyclic error in JSON stringify)** exception thrown when I pass the object's json to jsonEncode function of dart:convert. I really can't change the backend to avoid this issue, I need to find a way on the dart side to somehow get past this problem and successfully jsonEncode this object. It looks like the toJson functions are properly converting the main object and its properties to json format, but jsonEncode is where I am getting the error. Help will be greatly appreciated.

using
  json_annotation: ^4.0.1
  build_runner: ^2.1.1
  json_serializable: ^4.1.4

`$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[!] IntelliJ IDEA Ultimate Edition (version 2016.2)
    X This install is older than the minimum recommended version of 2017.1.0.
[√] VS Code, 32-bit edition (version 1.63.2)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.`

**Comment by kevmoo** [comment]
There's nothing this package can do to help you. You need to change your data model to avoid cycles. That's the only solution.
