### ISSUE TITLE
"Checked" flag not working with nullable values

### ISSUE THREAD

**Issue by paulkangaroo** [google/json_serializable.dart#1092]
When deserializing an object whose properties are all nullable, I'm not getting an exception with checked = true. Is this working as intended?

For example, I have a class like so:

```
@JsonSerializable(
    explicitToJson: true, fieldRename: FieldRename.snake, checked: true)
class UserProfileModel {
  final UserProfileDataModel? data;
  final UserProfileInclude? included;

  UserProfileModel({
    this.data,
    this.included,
  });
```

When attempting to decode a json string such as this: `{type: Idle, code: -1, msg: result is idle}`, I would expect **CheckedFromJsonException** to be thrown. However, instead a **UserProfileModel** is being created with data and included values set to null.

I'm able to raise an exception with "disallowUnrecognizedKeys", however I thought CheckedFromJsonException should also be thrown in this scenario. Is there another way to type check incoming json strings for classes with only nullable properties?

Thanks!

`Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (9 weeks ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0`

**Comment by spauldhaliwal** [comment]
Accidentally created the ticket from my work account but I'll be following it from this account going forward.

**Comment by kevmoo** [comment]
`UserProfileModel` has nullable fields. So the other values are ignored. What type of exception is throw with `disallowUnrecognizedhKeys`?
