### ISSUE TITLE
Could not generate `toJson` code for `box`.

### ISSUE THREAD

**Issue by daviddagan** [google/json_serializable.dart#1094]
hello when om using both annotations(hive and JsonSerializable) on an object I get this error: Could not generate `toJson` code for `box`.
this is my object:

part 'rsrp_apps.g.dart';

@HiveType(typeId: 0)
@JsonSerializable(createFactory: false)
class RsrpApp extends HiveObject {
  @HiveField(0)
  final String iconUrl;
  @HiveField(1)
  final String name;
  @HiveField(2)
  @JsonKey(name: "G3")
  final List<double> g3;
  @HiveField(3)
  @JsonKey(name: "G4")
  final List<double> g4;
  @HiveField(4)
  @JsonKey(name: "G5")
  final List<double> g5;

  RsrpApp({required this.iconUrl, required this.g3, required this.g4, required this.g5, this.name = ""});

  //--> flutter pub run build_runner build
   Map<String, dynamic> toJson() => _$RsrpAppsToJson(this);

**Comment by kevmoo** [comment]
please run build with `--verbose` and let me know the info!

**Comment by daviddagan** [comment]
the reason its dont work is when I use  "extends HiveObject"
when I remove it it build and work fine

**Comment by kevmoo** [comment]
Please include the output using `--verbose`.

Also: where is `HiveObject` coming from? It if depends on something in the flutter package, this won't work, sadly.
