### ISSUE TITLE
Using a Json Serializable Class prevents dart complete exe from working with AOT error referencing dart:mirror

### ISSUE THREAD

**Issue by labaxter** [google/json_serializable.dart#1097]
It apperas json_serializable requires the import of dart:mirror? Or is this included by something json_serializable uses?

I commented on https://github.com/dart-lang/sdk/issues/44489, and was it was suggested I take the issue to json_serializable.  If this can be fixed it would be nice to be able to generate native code (a feature of dart, and something I will want when I move to a flutter UI)

```
$ dart --version
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "linux_x64"
$
```

Here is a dart program that compiles and runs just fine

```
import 'dart:io';
//import 'package:vault/common/password.dart';
void main() async {
  Directory d = Directory.current;
  print("CWD: ${d.path}");
//  Password pw = Password("password",false);
//  String str = pw.password;
}

$ dart compile exe bin/cmd.dart
Info: Compiling with sound null safety
Generated: /home/lab/src/vault/bin/cmd.exe
$
```
When I un-comment the reference to a json_serializable class (Password) it fails to compile:

```

$ ~/src/vault dart compile exe bin/cmd.dart
Info: Compiling with sound null safety
error: import of dart:mirrors is not supported in the current Dart runtime
Error: AOT compilation failed
Generating AOT snapshot failed!
$

```

**Comment by labaxter** [comment]
@jakemac53  Great question.  I've now determined that this is definitely NOT a  json_serializable problem.  It is probably something else I've used, or how the my code is organized... I need to do more digging.  Closing this issue.

**Comment by labaxter** [comment]
BTW: It was importing json_annotation.

**Comment by jakemac53** [comment]
Sounds good, fwiw I have a little utility package that may help you find where the mirrors import is coming from, [import_path](https://pub.dev/packages/import_path).

**Comment by labaxter** [comment]
See issue I raised on import_path. In retrospect, I think you are assuming that one has cloned your repository.

I did that; did `dart pub update`  but then could not quickly figure out how to use it (exceptions thrown).  

But I found where my problem is: I used the quiver package for its object hashing methods to implement get hashCode in classes where I overloaded == operator. I can probably live without that, or come up with an alternative.

**Comment by jakemac53** [comment]
Note that we now have [Object.hash](https://api.dart.dev/stable/2.16.1/dart-core/Object/hash.html) (and hashAll), although those won't help if quiver was using mirrors to look at all the fields and generate a hashCode that way. You could however use a different code generator to generate `hashCode` and `==` for you, something like [freezed](https://pub.dev/packages/freezed).

**Comment by labaxter** [comment]
@jakemac53 Well, I was wrong.  It was not quiver.  It took until late evening for me to have it finally figured out.  

It appears to have been a twisted overlay of imports.  At some point a while ago I got the idea that I could just create a common file that imported everything, and then exported them to the rest of the code.  Once I got rid of that, and imported only what I needed where I needed it, the problem went away.  I started with a 2 line main(), and just added things until I found an import that caused the compile error, (there were several -- each time I thought I'd found it I found more).  For each one I simplified the module to just import explicitly what was needed.  And I moved some of the code I'd put in common modules, to where it was referenced avoiding the import of that module.  There should be if there isn't, a "best practice" of not creating complex import schemes.  There may be, and I just didn't see it.

It turned out I wasn't using == operator, so I just deleted that from the class definitions, and removed the tests for them.  I now have cleaner code that does compile to native executables.

It I decide I want them I'll use Object.hash(), which a should have used in the first place. I chalk that up to being a dart newbie. You've been very helpful.  Thank you.

**Comment by jakemac53** [comment]
Fwiw, `Object.hash()` is fairly new so lots of people don't know it exists :).

As far as best practices you should definitely try to at least create separate imports for the separate platforms that are required. We don't have a lot of good docs or published best practices as far as I am aware though. Most people do end up just exposing everything through a single import which works OK.... until it doesn't 🤣 .
