### ISSUE TITLE
Clarify when encodable properties can be set "final" and when they cannot

### ISSUE THREAD

**Issue by dgaedcke** [google/json_serializable.dart#1101]
flutter --version
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (2 days ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2

It's not clear from the documentation WHEN you can use "final" on your serializable class properties and when you cannot.   I'm seeing inconsistent effects that are confusing ...

**Comment by kevmoo** [comment]
Each field you want to be settable needs to be settable some how. Either via a constructor parameter or a read/write field/property.
