### ISSUE TITLE
Exclude generated files from coverage

### ISSUE THREAD

**Issue by jtdLab** [google/json_serializable.dart#1106]
Hi,

when generating code for a given class A the resulting file a.g.dart is part of the coverage report.
This should not be the case in my opinion because the generated code is assumed to be well tested and thus should not pop up in the coverage report.

This issue can be fixed with adding **// coverage:ignore-file** to the generated file.

Better solutions and discussion is very welcome :)

**Comment by kevmoo** [comment]
Open an issue in https://github.com/dart-lang/source_gen/ for this

We'd need to do something similar to our support for `ignore_for_file`

**Comment by darwin-morocho** [comment]
@kevmoo I have opened this PR https://github.com/dart-lang/source_gen/pull/636 to solve this
