### ISSUE TITLE
[Feature Request] - provide fromJson and toJson via extension method

### ISSUE THREAD

**Issue by giaur500** [google/json_serializable.dart#1138]
Currently, we still need to write `fromJson`/`toJson` methods and connect them to auto generated ones, like this:

```
/// Connect the generated [_$PersonFromJson] function to the `fromJson`
  /// factory.
  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);

  /// Connect the generated [_$PersonToJson] function to the `toJson` method.
  Map<String, dynamic> toJson() => _$PersonToJson(this);
```
Proposal: generator should generate extension methods, so they will be visible without need to add anything to model class. This approach is used by `copyWith` generator: https://pub.dev/packages/copy_with_extension_gen 
Autogenerated code includes extension `copyWith` method, like this:

```
extension $ModelCopyWith on Model {
  /// Returns a callable class that can be used as follows: `instanceOfclass Model.copyWith(...)` or like so:`instanceOfclass Model.name.copyWith.fieldName(...)`.
  _$ModelCWProxy get copyWith => _$ModelCWProxyImpl(this);
}
```

We could generate similar code for `fromJson` and `toJson` methods.

**Comment by rrousselGit** [comment]
Extensions cannot offer a fromJson constructor

And toJson cannot be an extension, as this would prevent dart:convert from serializing the class.

**Comment by kevmoo** [comment]
What @rrousselGit said. There is an old (closed) bug on this, too.
