### ISSUE TITLE
How to implement an abstract class that can be implemented?

### ISSUE THREAD

**Issue by DanMossa** [google/json_serializable.dart#1144]
Hey all!

I'm creating a @JsonSerializable class that implements an abstract Base class.

The serializable classes have a toJson as well as a factory fromJson.

I'm able to create an abstract toJson method inside my abstract Base class.

But I'm having a hard time figuring out how to write the fromJson inside of the abstract Base class.

Any ideas?

**Comment by kevmoo** [comment]
You cannot write the `fromJosn` in the abstract class – UNLESS it has knowledge of all of the subclasses.

**Comment by kevmoo** [comment]
...and can tell which subclass to instantiate given the content of the JSON
