### ISSUE TITLE
[Feature Request] Enum value with enhanced Enums

### ISSUE THREAD

**Issue by a7md0** [google/json_serializable.dart#1147]
Feature request related to [Enhanced enums](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md) while using [JsonValue](https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonValue-class.html)

1. Currently, we would have to declare the value twice per Enum value (to allow this package to serialize/deserialize the Enum and to have access to `.value`)
```dart
import 'package:json_annotation/json_annotation.dart';

part 'status_code.g.dart';

enum StatusCode {
  @JsonValue(200)
  success(200),

  @JsonValue(500)
  weird(500),

  const StatusCode(this.value);

  final int value;
}
```

It would be much better if we could have the generated map `EnumMap` to use the value specified in the constructor

**Comment by a7md0** [comment]
I have no idea how could generation work in the package, but one possibility will be offer some kind of interface `EnumValue<T>` to be implemented by the Enum, thus making the `T value` required to be implemented. Next it would be to check for Enums implementing this interface and use the value passed in the constructor to create the `EnumMap` with the code generation.

**Comment by kevmoo** [comment]
Or we could "steal" the `JasonValue` annotation and put it on the `enum` definition with the field name – in the case above `"value"`.

The package is not setup to support adding language-specific features until we're ready to bump the min SDK, so it'll likely be a while until we get there.

**Comment by kevmoo** [comment]
https://github.com/google/json_serializable.dart/pull/1180 bumps the min version of the required SDK – we could entertain this now!

**Comment by memoriasIT** [comment]
Hey, did this get any updates? I am running the latest version and it's still generating by name. Am I missing something?

**Comment by kevmoo** [comment]
This feature has been added as of

https://pub.dev/packages/json_annotation/versions/4.7.0
and
https://pub.dev/packages/json_serializable/versions/6.4.0

**Comment by YiannisBourkelis** [comment]
@kevmoo  Sorry for coming back on this. Just to make things clear, when using the new syntax of enhanced enums should we still use the @JsonValue annotation not top of each enum value or does the library takes care of it?

Looks that json_convert always generates a string representation of the enum name when there is no @JsonValue.

**Comment by kevmoo** [comment]
Just use `@JsonEnum` on the enum itself. `@JsonValue` should no longer be needed.

**Comment by YiannisBourkelis** [comment]
@kevmoo Perfect! Thank you
