### ISSUE TITLE
How can I initialize a object on generate class instead of 'null' ?

### ISSUE THREAD

**Issue by rvvarasdiya** [google/json_serializable.dart#1156]
Can anyone tell me how I can initialize a class instead of on null in the 'g.dart' file?

![Screenshot 2022-06-10 at 4 42 12 PM](https://user-images.githubusercontent.com/39657107/173053041-bc3b5f5e-d8b1-4eaa-9753-f695a50edd43.png)

Instead of null how can I just make an `Avtar()`.

**Comment by kevmoo** [comment]
You can't do that in the generated code – unless it's a `const` object, when you can use default value.

The other option is to support a `nullable` CTOR parameter and then instantiate the value when you create the class.
