### ISSUE TITLE
Is anyway to generate file inside "library part file"

### ISSUE THREAD

**Issue by HoangNguyen0403** [google/json_serializable.dart#1162]
Hi all, I have one concert that can we use both part of and part to generate .g.dart file like this. And if have can describe the solution here. Because I want to apply ecapsule in data layer.
@kevmoo 

<img width="612" alt="Screen Shot 2022-06-23 at 14 44 28" src="https://user-images.githubusercontent.com/103477760/175245651-32da5d29-a0e9-4bd0-8baf-16e21d6109bf.png">

**Comment by HoangNguyen0403** [comment]
<img width="1144" alt="Screen Shot 2022-06-24 at 08 56 22" src="https://user-images.githubusercontent.com/103477760/175446963-c1976dc8-0b2f-49e5-b496-c83eb13dd4dd.png">

when re-generated .g.dart file with delete output conflict I got this error, can't generated. It's similar with error syntax that
"The part-of directive must be the only directive in a part.  Try removing the other directives, or moving them to the library for which this is a part."

**Comment by Junama** [comment]
I have the same error

**Comment by HoangNguyen0403** [comment]
> I have the same error

Actually, have another way is using "export file_name.dart" but this is a workaround way, I still want to find a way to use both part and part of 
@kevmoo

**Comment by kevmoo** [comment]
We never designed the builder logic to target members defined in a part.

You *could* try to put the part definition in the "root" library.
