### ISSUE TITLE
Add parameter "caseSensitive"

### ISSUE THREAD

**Issue by enloc-port** [google/json_serializable.dart#1163]
JsonSerializable should be able to read keys case-insensitively.

In some cases, I do not care about the casing of the keys. In our case, we had an issue, because the app pulls JSON data from a REST API and one of the keys had a typo like below.

JSON as returned from the API:
```json
{
    "fooBar": "Hello World!",
    "someuniqueAndLongKeyName": 42
}
```

Generated json_serializable Dart code:
```dart
MyObject obj = MyObject()
  ..fooBar = json['fooBar']
  ..someUniqueAndLongKeyName = json['someUniqueAndLongKeyName']
;
```

`json['someUniqueAndLongKeyName']` will always return null, because the key as returned by the API was `someuniqueAndLongKeyName`.

**Comment by HoangNguyen0403** [comment]
If it's customize key, @JsonKey(name:) already have you can add this case into It with customize string key

**Comment by kevmoo** [comment]
Use https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/readValue.html to handle this case.
