### ISSUE TITLE
Super-parameters issue

### ISSUE THREAD

**Issue by coccyx-cyst** [google/json_serializable.dart#1171]
Hello.

I am facing the problem when I am using new Dart 2.17 super-parameters in constructor.

```dart
const BasketModel({
    required this.products,
    required this.delayedProducts,
    required this.unavailableProducts,
    required super.coupon,
    required super.couponData,
    required super.isCouponApplied,
    required this.summary,
  }) : super( 
          products: products,
          delayedProducts: delayedProducts,
          unavailableProducts: unavailableProducts,
          summary: summary,
        );
```

So I am getting this code-generation errors
![image](https://user-images.githubusercontent.com/72284940/177996407-01e2b8ee-00ed-4c02-8079-4eabf2757e9b.png)

My flutter and dart version in project are up to date
![image](https://user-images.githubusercontent.com/72284940/177996496-69944934-2746-45cf-b940-7849f4a55a19.png)

**Comment by coccyx-cyst** [comment]
I am able to solve that problem with command:
```
flutter pub run build_runner build --delete-conflicting-outputs --enable-experiment=super-parameters
```

But I wonder if there's any other way to handle that?

**Comment by kevmoo** [comment]
What's your SDK constraint in your pubspec?

It should be `sdk: '>=2.17.0 <3.0.0'`

**Comment by kencana16** [comment]
> What's your SDK constraint in your pubspec?
> 
> It should be `sdk: '>=2.17.0 <3.0.0'`

i am using these SDK constraint and get same error message

**Comment by coccyx-cyst** [comment]
> What's your SDK constraint in your pubspec?
> 
> It should be `sdk: '>=2.17.0 <3.0.0'`

It is.

**Comment by kevmoo** [comment]
Have you run `pub get` or `pub upgrade` and restarted your IDE?

**Comment by coccyx-cyst** [comment]
> Have you run `pub get` or `pub upgrade` and restarted your IDE?

Sure, I have.

**Comment by kevmoo** [comment]
Any progress here, @coccyx-cyst ?

**Comment by coccyx-cyst** [comment]
> Any progress here, @coccyx-cyst ?

Nope

I'm still using : ```flutter pub run build_runner build --delete-conflicting-outputs --enable-experiment=super-parameters```

**Comment by kevmoo** [comment]
give me the output of `flutter --doctor`

**Comment by kevmoo** [comment]
or `flutter doctor`

**Comment by coccyx-cyst** [comment]
> flutter --doctor

![image](https://user-images.githubusercontent.com/72284940/185848696-625923aa-0fc9-4323-92d7-d5f746c041e3.png)

**Comment by kevmoo** [comment]
Drop the `-0` from `12.17.0-0`
