### ISSUE TITLE
DelegatingX from collection package not correctly serialized

### ISSUE THREAD

**Issue by cedvdb** [google/json_serializable.dart#1174]
It seems like `DelegatingList` & `DelegatingSet` from the collection package do not serialize correctly.

For `DelegatingList` I had `Cannot populate the required constructor argument: images.`

```dart
class UserImages extends DelegatingList<StoredImage> {
  static const min = 5;
  static const max = 20;

  const UserImages(List<StoredImage> images)
      : assert(images.length >= 5),
        assert(images.length <= 20),
        super(images);
```

For DelegatingSet it created the `.g.dart` file but the constructor arguments were empty

```dart
class OpeningDays extends DelegatingSet<Day> {
  const OpeningDays(super.base);
}
```

**Comment by kevmoo** [comment]
Yup. `images` is not a property on the collection. For this, you'll have to implement `toJson` and `fromJson` yourself. Should be trivial.
