### ISSUE TITLE
[Feature Request] list name

### ISSUE THREAD

**Issue by 1AlexFix1** [google/json_serializable.dart#1179]
Hello, sometimes i need to have a list of different names for values
@JsonKey(name: ['firstName' ,  'altertativeName'])

codogen json['firstNane'] ?? json['altertativeName']

**Comment by k-paxian** [comment]
Do you mean something like that https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration ?

**Comment by 1AlexFix1** [comment]
> k

yes))

**Comment by k-paxian** [comment]
Nope, unfortunately it's a different independent package

**Comment by kevmoo** [comment]
Use https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/readValue.html – this is a general solution for this case.
