### ISSUE TITLE
Make JsonKey's defaultValue a Function? type

### ISSUE THREAD

**Issue by erf** [google/json_serializable.dart#1185]
I would like to supply a `DateTime.now()` as a `defaultValue` to `JsonKey`, but as it's not a `const` it's not possible to add it, however if it was of type `Function?` i could pass it a function which would return a value in the same way as `toJson` and `fromJson`, e.g. `static DateTime newDate() => DateTime.now();` This would be a breaking change so not sure if it's feasible, but it would make the API more flexible perhaps?

Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"

**Comment by kevmoo** [comment]
You know what I COULD do. We could allow `defaultValue` (which is already typed as `Object?`) to accept a function of type `T Function()` where `T` is the field type. Not a bad idea!

**Comment by kevmoo** [comment]
Not a priority for me, but I'd accept a reasonable PR.

**Comment by kevmoo** [comment]
@erf – you will ONLY be able to pass in top-level or static functions. No instance functions will be allowed.

**Comment by kevmoo** [comment]
@erf – like...the feature actually works? I don't remember adding that feature. (goes to look at code...)

**Comment by kevmoo** [comment]
This is NOT implemented. Build will break if you use a function. I actually have a todo here for this!

**Comment by eximius313** [comment]
@kevmoo - when do you plan the release?

**Comment by kevmoo** [comment]
Hopefully today!

**Comment by kevmoo** [comment]
Done! v6.5.0

**Comment by kevmoo** [comment]
You just need to use a top-level or static function.

**Comment by kevmoo** [comment]
Always good to share source code...

**Comment by kevmoo** [comment]
Remove the `?` from `date0`.

**Comment by kevmoo** [comment]
Hrm...I'm digging now and seeing the problem. Will have to investigate.

**Comment by kevmoo** [comment]
Will need to follow-up here: https://github.com/google/json_serializable.dart/issues/1219

**Comment by kevmoo** [comment]
@erf you actually FOUND A BUG!! It affects `BigInt`, `DateTime` and `Uri`. Completely unrelated to this feature.

Well done!

**Comment by kevmoo** [comment]
@erf – well, it's weird. Turns out the type helpers for certain types NEED to explicitly support default values. I'd never done "the work" for three types, because they weren't const-able. That's now fixed! See https://github.com/google/json_serializable.dart/pull/1220

**Comment by kevmoo** [comment]
Fixed now and published @erf
