### ISSUE TITLE
how to set default values to a field  in FromJson when it is null?

### ISSUE THREAD

**Issue by huangjiaxiang** [google/json_serializable.dart#1186]
```
@JsonSerializable()
class VersionInfo {
  VersionInfo();

  ///
  @JsonKey(name: "v_CreateTime")
  String? vCreateTime = '';

  ///
  @JsonKey(name: "v_Identity")
  num? vIdentity = 0;
}
```
v_Identity is null ,the vIdetity set 0

**Comment by huangjiaxiang** [comment]
I use

**Comment by huangjiaxiang** [comment]
using
 build_runner: ^2.1.11 
  json_annotation: ^4.5.0

**Comment by feicien** [comment]
```dart
import 'package:json_annotation/json_annotation.dart';

part 'version_info.g.dart';

@JsonSerializable()
class VersionInfo {
  @JsonKey(name: 'v_CreateTime', defaultValue: '')
  String? vCreateTime;
  @JsonKey(name: 'v_Identity', defaultValue: 0)
  int? vIdentity;

  VersionInfo({
    this.vCreateTime,
    this.vIdentity,
  });

  factory VersionInfo.fromJson(Map<String, dynamic> json) =>
      _$VersionInfoFromJson(json);

  Map<String, dynamic> toJson() => _$VersionInfoToJson(this);
}
```

**Comment by huangjiaxiang** [comment]
> ```dart
> import 'package:json_annotation/json_annotation.dart';
> 
> part 'version_info.g.dart';
> 
> @JsonSerializable()
> class VersionInfo {
>   @JsonKey(name: 'v_CreateTime', defaultValue: '')
>   String? vCreateTime;
>   @JsonKey(name: 'v_Identity', defaultValue: 0)
>   int? vIdentity;
> 
>   VersionInfo({
>     this.vCreateTime,
>     this.vIdentity,
>   });
> 
>   factory VersionInfo.fromJson(Map<String, dynamic> json) =>
>       _$VersionInfoFromJson(json);
> 
>   Map<String, dynamic> toJson() => _$VersionInfoToJson(this);
> }
> ```

谢了！这是本来就有的么，一开始我记得在fromJson会有空判断，后面更新就没了 ，这个参数我也没发现。
