### ISSUE TITLE
Add an option to create the reversed enum map

### ISSUE THREAD

**Issue by ValentinVignal** [google/json_serializable.dart#1187]
It would be very useful to create a reversed enum map:

```dart
@JsonEnum()
enum MyEnum {
  a,
  b,
}
```

What is currently generated:

```dart
const _$MyEnumEnumMap = {
  MyEnum.a: 'a',
  MyEnum.b: 'b',
};
```

It would be very useful to generate:

```dart
const _$MyEnumEnumMapFromNames = { // Or whatever better name.
  'a': MyEnum.a,
  'b': MyEnum.b,
};
```

With maybe some assertions when generating that check the json keys are all unique

**Comment by kevmoo** [comment]
Why do you want this? Just curious...

**Comment by kevmoo** [comment]
I'm NOT likely to take a PR here. I worry about the noise added to the system here – unless we have a very compelling use case.

**Comment by ValentinVignal** [comment]
We are using `JsonSerializable` on enums to parse some values obtained as a Json (ex: from an API) into a enum.

```dart
final String value = myApiCall();
```

We are reusing the generated code to get the enum value from its string representation:

```dart
@JsonEnum(alwaysCreate: true)
enum MyEnum {
  myEntry0,
  myEntry1;

  factory MyEnum.fromString(String string) {
    return _$MyEnumEnumMap.firstWhere((entry) => entry.value == string);
  }
}
```

Wouldn't it be better to have something for that directly?

```dart
  factory MyEnum.fromString(String string) {
    return _$MyEnumEnumMapFromNames[string]!;
  }
```

We could also use `$enumDecode` or `$enumDecodeNullable` but the documentation specifies it is not meant to be used, it is meant for the generated code.

**Comment by kevmoo** [comment]
Strictly speaking, you should be careful if you use `$enumDecode`. Practically speaking, those are VERY stable APIs, since I don't want break existing code that relies on them.

I won't tell anyone if you use them directly. 😄
