### ISSUE TITLE
Show the name of the 'key' along with the type in error

### ISSUE THREAD

**Issue by Gamezordd** [google/json_serializable.dart#1191]
Currently this is how errors for missing keys in api response is thrown:

```
The following TypeErrorImpl was thrown building MyWidget(dirty, state: _MyWidgetState#c5df2):
js_primitives.dart:30

Expected a value of type 'String', but got one of type 'Null'
```

Why not print the failed key name in the error to avoid unnecessary debugging. Like so:

```
The following TypeErrorImpl was thrown building MyWidget(dirty, state: _MyWidgetState#c5df2):
js_primitives.dart:30

Expected a value of type 'String' for argument 'some_arg', but got one of type 'Null'
```

**Comment by kevmoo** [comment]
@Gamezordd – I'd need more of a stack trace to see what broke.

If you want more helpful errors, you likely need to enabled `checked` configuration.

Include a full example if I'm missing something.
