### ISSUE TITLE
handling exceptions in data

### ISSUE THREAD

**Issue by thorizer** [google/json_serializable.dart#1192]
I'm using json_serializable to get data from backend that uses mongodb
there is sometimes exceptions where an id could be the full object in an array instead of a string (ObjectID)

for example, 5 out 830 had objects instead of a string , which means 
sometimes `json['_company_owner'] = json['_company_owner'] as String?` and 
sometimes `json['_company_owner'] = json['_company_owner']['_id'] as String?` (which not possible to access with ['_id'] as the actual type of company owner is a string)

I'm manually checking them , but if company_owner should be a string, then when I test with the runtime type like this:

`company_owner: json['_company_owner'].runtimeType != String
          ? json['_company_owner']['_id'] as String? : json['_company_owner'] as String?`

I'm getting an error , cause I'm accessing a string by [_id] 

the backend won't change as it's in production for 10 years. they populate objects sometimes and sometimes they don't. I'm having a hard time fixing these issues manually, I also do catch these issues but the app will be blank with no data
what's the optimal way to handle this ?
when I use typescript I put company owner type as a `String | _company_owner` type

![ShareX_ayHYnCpCtl](https://user-images.githubusercontent.com/13587810/186674041-e78dc888-f8f4-4a50-b97f-13599683ee13.png)

![Postman_CfJYl1bewv](https://user-images.githubusercontent.com/13587810/186674069-2d765bf7-6f6c-42e1-a9fa-9e7d8e00081d.png)

Flutter doctor :
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.4)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by kevmoo** [comment]
Use a custom converter that takes in `Object` and returns the type of the field. Sniff the data in the associated JSON value and "do the right thing"

**Comment by thorizer** [comment]
@kevmoo any example I could follow? any json annotation I should use ?

**Comment by thorizer** [comment]
@kevmoo I just found out about this , is this still valid in v6  ?
![DRWUI_XZnFx8Samq](https://user-images.githubusercontent.com/13587810/186733030-ee604580-7ccf-4df6-89c3-b56f7783ec5a.png)

**Comment by kevmoo** [comment]
@thorizer – should be!
