### ISSUE TITLE
[request] Generate utilities to serialize only a specific property of an object

### ISSUE THREAD

**Issue by rrousselGit** [google/json_serializable.dart#1198]
Hello! I'm bothering you one more time for some cloud_firestore_odm issues 🙈 

## Problem

Long story short, I'm trying to fix https://github.com/firebase/flutterfire/issues/9428.
The gist of the issue is that the ODM wants to partially encode an object. 

So for:

```dart
@JsonSerializable()
class Person {
  ...

  final String firstName;
  final String lastName;
}
```

someone may want to update only the `lastName` property of `Person`.
In plain Firestore, that would be:

```dart
personCollection.doc('42').update({'last_name': 'Mona'});
```

With the ODM, this ends-us as:

```dart
personCollection.doc('42').update(lastName: 'Mona');

// generate source code for update
class PersonDocumentReference {
  Future<void> update({String lastName = _sentinel}) {
    return _reference.upate({
      if (lastName != _sentinel)
        _$PersonFieldMap['lastName']!: lastName as String,
    });
  }
}
```

That works for simple primitives like `String`.  But for anything more complex, this doesn't work anymore.

For that, what I would need would be to invoke the "toJson" of `Person`, but only for its `lastName` property.

## Proposal

My thought for solving this would be to do something similar to what was done with "XFieldMap", but for a "toJson" variant

For example, for:

```dart
@JsonSerializable()
class Complex {
  ...

  final MyEnum enum;
  final Person person;
}

enum MyEnum {
  @JsonValue('hello_world')
  helloWorld,
}

@JsonSerializable()
class Person {
  ...

  final String firstName;
  final String lastName;
}
```

we could generate the following utility for `Complex`:

```dart
abstract class _$ComplexPropertyPerFieldToJson {
  static Map<String, Object?> person(Person person) {
    return person.toJson();
  }

  static String enum(MyEnum enum) {
    switch (enum) {
      case MyEnum.a: return 'hello_world';
    }
  }
}
```

This would allow the Firestore ODM to generate:

```dart
class ComplexDocumentReference {
  Future<void> update({MyEnum enum = _sentinel, Person person = _sentinel}) {
    return _reference.upate({
      if (enum != _sentinel)
        _$ComplexFieldMap['enum']!: _$ComplexPropertyToJson.enumToJson(enum as MyEnum),
      if (person != _sentinel)
        _$ComplexFieldMap['person']!: _$ComplexPropertyToJson.personToJson(person as Person),
    });
  }
}
```

**Comment by kevmoo** [comment]
@rrousselGit – I'm assuming you "own" this. 😄

**Comment by rrousselGit** [comment]
Yes 😊
