### ISSUE TITLE
Support for Records

### ISSUE THREAD

**Issue by TimWhiting** [google/json_serializable.dart#1222]
With the upcoming records feature, it would be good to figure out how to serialize those with this package.

I'd propose:
- Make it an error to mix positional and named fields in an **inline type**
- Allow records with only named fields - serializes to a normal JSON map with keys as the field names
- Allow records with only positional fields - serializes to a normal JSON list (note that the list might not be homogenous)

Allow records with mixed fields with the following qualifications:
- only via a typedef - so that we don't have to canonicalize structural types.
- is converted to a JSON map
- positional fields require a JsonKey annotation with a name

Potential other requirements to consider:
- Only support JsonKey annotation with typedefs - to make it clear we don't canonicalize structural types

Note that we could probably support not requiring to go through a typedef, it just makes it more error prone for users, because they need to understand that the type is not canonicalized and the annotation would have to be added to all records.

Finally, we would need to consider what annotating a record type by itself (not embedded in an object) with JsonSerializable would look like. I think creating a toJson extension method would be a good approach. Where to put the fromJson method / how to name it is a bit more tricky.

**Comment by kevmoo** [comment]
I'm not thinking about this too much (yet) – but a good thing to discuss early!

**Comment by shilangyu** [comment]
Probably worth reviving now that records reached stable?

**Comment by humbertoadan** [comment]
> Probably worth reviving now that records reached stable?

Yes, it's definitely needed now. I'm actually trying JsonKey.toJson and JsonKey.fromJson to use custom conversion on an annotated field which is a list of records. If I do this: List<({String id, int quantity})>? records, it gives me a "Null check operator used on a null value" error.

**Comment by kevmoo** [comment]
Hrm...perhaps...

I'm a bit nervous about the effort required here. I could dig a bit.

**Comment by eximius313** [comment]
I've just upgraded to Dart 3.0 and encountered this problem while generating mocks (using Mockito):
```
[SEVERE] json_serializable on lib/src/my_class.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:my_pkg/src/my_class.dart (or an existing part) contains the following errors.
my_class.dart:56:10: This requires the 'records' language feature to be enabled.

Try fixing the errors and re-running the build.
```

I've set 
```
analyzer:
  enable-experiment:
    - records
```
in `analysis_options.yaml` but this didn't help

**Comment by kevmoo** [comment]
You need to get the latest `pkg:analyzer`, too!

**Comment by eximius313** [comment]
@kevmoo, you mean [this one](https://pub.dev/packages/analyzer/install)?
I've used the newest one, but error is simmilar:
```
[SEVERE] mockito:mockBuilder on test/my_test.dart:

Could not format because the source could not be parsed:

line 33, column 22 of .: This requires the 'records' language feature to be enabled.
```

**Comment by kevmoo** [comment]
On the way - https://github.com/google/json_serializable.dart/pull/1314

**Comment by eximius313** [comment]
awesome!

**Comment by kevmoo** [comment]
You need to change your SDK constraint to `^3.0.0`

**Comment by eximius313** [comment]
I have it already.
I'm invoking command `dart run build_runner build --delete-conflicting-outputs`

**Comment by kevmoo** [comment]
Have you run `pub get/upgrade`?

**Comment by kevmoo** [comment]
You should NOT need to tweak analysis_options – that won't help the generator!

**Comment by eximius313** [comment]
`pub get/upgrade` helped.
I removed 
```
analyzer:
  enable-experiment:
    - records
```
from `analysis_options.yaml`
and
```
  analyzer: ^5.12.0
```
from `pubspec.yaml`

It generates value, but now the problem is different:
In generated file, it generated the imports as:
```
// Mocks generated by Mockito 5.4.0 from annotations
// in pos_sdk/test/pos_sdk_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i7;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
```
but in generated method:
```dart
_i4.Future<({Uint8List data, InternetAddress deviceAddress})> findIp({
```
it did not replaced the prefixes, so the file does not compile

**Comment by eximius313** [comment]
But now the problem is different - in generated file, it generated the imports as:
```
// Mocks generated by Mockito 5.4.0 from annotations
// in pos_sdk/test/pos_sdk_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i7;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
```
but in generated method:
```dart
_i4.Future<({Uint8List data, InternetAddress dA})> findIp({
```
it did not replaced the prefixes, so the file does not compile

**Comment by kevmoo** [comment]
This looks like a bug in `mockito` when dealing w/ Records. 🤷

**Comment by Reprevise** [comment]
I was kind of hoping for `Records` with only positional fields to be serialized as lists so if I have a list of:

```dart
[0.34, 0.123, 0.542, 0.4143]
```

it would be deserialized into:

```dart
(0.34, 0.123, 0.542, 0.4143)
```

Obviously I understand that whichever way it's implemented people are going to be upset but I think this is far more common than having a map with keys like `$1`.

**Comment by kevmoo** [comment]
@Reprevise – hrm. Yeah.

Or I could do a list if they are all positional. 

Hrm. File a separate issue. Happy to entertain for later.

**Comment by Reprevise** [comment]
@kevmoo Filed a new issue here #1321

**Comment by aldee** [comment]
> @kevmoo, you mean [this one](https://pub.dev/packages/analyzer/install)? I've used the newest one, but error is simmilar:
> 
> ```
> [SEVERE] mockito:mockBuilder on test/my_test.dart:
> 
> Could not format because the source could not be parsed:
> 
> line 33, column 22 of .: This requires the 'records' language feature to be enabled.
> ```

For those who still have this problem, instead of running pub upgrade, which would update a lot of your project's dependencies, you just need to update the package dart_style to the latest version/2.3.2, depending on the version of the package analyzer that you're using
