### ISSUE TITLE
@JsonKey(includeIfNull: false) does not work with JsonConverter<DateTime, String>

### ISSUE THREAD

**Issue by AndreiMisiukevich** [google/json_serializable.dart#1229]
Hello, and thanks for your awesome project!
I have an issue with codegen which become a problem recently.

Basically `writeNotNull` is not applied to fields that use a converter.

Class:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/10124814/197619382-37a3d1bd-f96e-4418-8344-ecd19543fde0.png">

Codegen:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/10124814/197619245-066885ae-b6e8-48b4-9e8a-daaf0df8ebfb.png">

Dart SDK version: 2.19.0-255.2.beta (beta) (Tue Oct 4 13:45:53 2022 +0200) on "macos_x64"
Flutter 3.4.0-34.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 71520442d4 (3 weeks ago) • 2022-10-05 16:38:28 -0500
Engine • revision db0cbb2145
Tools • Dart 2.19.0 (build 2.19.0-255.2.beta) • DevTools 2.18.0

It seems that it was broken in version 6.5.2 in this PR https://github.com/google/json_serializable.dart/commit/5107ac1df814527853ab65686dced776335bf498

**Comment by kevmoo** [comment]
`writeNotNull` should only be applied to things that could be null. Would `_$JsonCoverterToJson` possibly return `null`?

**Comment by AndreiMisiukevich** [comment]
@kevmoo sure, here is the sample https://github.com/AndreiMisiukevich/json_serializable.dart/commit/b1469cc8d819e0445349ca4101d62ff241b9f27c

**Comment by AndreiMisiukevich** [comment]
> `writeNotNull` should only be applied to things that could be null. Would `_$JsonCoverterToJson` possibly return `null`?

Yes, as I mentioned above it worked perfectly up to version 6.5.1

**Comment by kevmoo** [comment]
Good catch! Sorry for the regression. PR in-flight @AndreiMisiukevich

**Comment by kevmoo** [comment]
Fix published @AndreiMisiukevich !

**Comment by AndreiMisiukevich** [comment]
@kevmoo thanks for the prompt response!
