### ISSUE TITLE
regression: JsonConverter & Lists

### ISSUE THREAD

**Issue by cpboyd** [google/json_serializable.dart#1233]
```
flutter --version
Flutter 3.3.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d9111f6402 (7 days ago) • 2022-10-19 12:27:13 -0700
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0
```

I have a custom converter:
```dart
class OffsetConverter implements JsonConverter<Offset?, List<double>> {
  const OffsetConverter();

  @override
  Offset? fromJson(List<double> offsetList) => offsetFromJson(offsetList);

  @override
  List<double> toJson(Offset? offset) => offsetToJson(offset!);
}
```

The converter still works for `Offset?` if not within a `List`, however, this throws an error:

```dart
@JsonSerializable()
@OffsetConverter()
class PointDrawPart {
  final List<Offset?>? points;

  PointDrawPart({
    required this.points,
  });

  factory PointDrawPart.fromJson(Map<String, dynamic> json) =>
      _$PointDrawPartFromJson(json);

  @override
  Map<String, dynamic> toJson() => _$PointDrawPartToJson(this);
}
```

Here's the error:
```sh
    lib/platform/image_editor/json/option/draw.g.dart:65:31: Error: The argument type 'List<dynamic>?' can't be assigned to
    the parameter type 'List<Offset?>?'.
     - 'List' is from 'dart:core'.
     - 'Offset' is from 'dart:ui'.
          points: (json['points'] as List<dynamic>?)
                                  ^
```

**Comment by kevmoo** [comment]
Need more info, @cpboyd !

**Comment by cpboyd** [comment]
@kevmoo I updated the issue. I accidentally hit enter in the title field and GitHub created it prematurely.

Is there anything more that you need from the updated issue?

I'd also tried switching from `List<Offset?>?` to `List<Offset>` (and updating the `OffsetConverter` to remove the nullability) but it still had a similar issue:
```sh    lib/platform/image_editor/json/option/draw.g.dart:68:12: Error: The argument type 'List<dynamic>' can't be assigned to
    the parameter type 'List<Offset?>'.
     - 'List' is from 'dart:core'.
     - 'Offset' is from 'dart:ui'.
              .toList(),
               ^
```

**Comment by kevmoo** [comment]
This is an OOOOLD issue.

Duplicate of https://github.com/google/json_serializable.dart/issues/236

**Comment by cpboyd** [comment]
@kevmoo I don't think this is a duplicate. I already have a custom converter `OffsetConverter`, which still works for normal usages of `Offset?` in JSON objects:

```dart
@JsonSerializable()
@OffsetConverter()
class LineDrawPart extends DrawPart {
  final Offset? start;
  final Offset? end;

  LineDrawPart({
    required this.start,
    required this.end,
  });

  factory LineDrawPart.fromJson(Map<String, dynamic> json) =>
      _$LineDrawPartFromJson(json);

  @override
  Map<String, dynamic> toJson() => _$LineDrawPartToJson(this);
}
```

 Further, the `List<Offset?>?` property was working in `6.4.1`. It started throwing errors in `6.5.4`.

Is it now required to write a separate `List` converter?

The error seems to indicate the issue is with unwrapping the `List`, since I render `Offset?` to a `List<double>` (i.e. converting `List<Offset?>?` to `List<List<double>>?`)

**Comment by kevmoo** [comment]
Hrm. Okay. I'll need to dig then.

**Comment by kevmoo** [comment]
@cpboyd – would you send be the before/after of the generated code between 6.4.1 and 6.5.4?
