### ISSUE TITLE
Add trailing commas

### ISSUE THREAD

**Issue by TheCarpetMerchant** [google/json_serializable.dart#1238]
In the case of a generation such as below, the missing comma warning pops up. It'd be great if we could add a trailing comma to such cases (or better, all cases).
![image](https://user-images.githubusercontent.com/5080204/200175958-1930d450-47a0-418c-89fd-410e46dbbc97.png)

**Comment by kevmoo** [comment]
I'd LOVE to...but!

Either we put them everywhere, which makes trivial code really ugly. 

OR

We add some non-trivial logic to figure out the right place to put them

OR

we integrate with analysis_server, which has a fix for this, but no API.

In the short term, we just use https://github.com/dart-lang/source_gen/#ignore_for_file
