### ISSUE TITLE
How to pass DocumentSnapshot from FireStore to json_serializable fromJson?

### ISSUE THREAD

**Issue by giorgio79** [google/json_serializable.dart#1243]
I am trying to pass DocumentSnapshot to a json_serializable fromSnapshot, but having some issues. I found some sample code referenced here https://stackoverflow.com/questions/63439439/firestore-fromsnapshot-vs-frommap-for-reading-documentsnapshot from a now defunct google codelab, but getting an error message
 `Generative constructors can't redirect to a factory constructor. (Documentation)`

Here is the sample:

```
      MyClass.fromSnapshot(DocumentSnapshot snapshot)
          : this.fromJson(snapshot.data, reference: snapshot.reference);
    
      factory MyClass.fromJson(snapshot.data as Map<String, dynamic> json) =>
          _$MyClassFromJson(json);
```

**Comment by kevmoo** [comment]
you're hitting a Dart language issue. You need to make `MyClass.fromSnapshot` a factory, too!
