### ISSUE TITLE
Dynamic field and enum

### ISSUE THREAD

**Issue by SuricateTrading** [google/json_serializable.dart#1248]
When serializing a dynamic field containing an enum, the error "Converting object to an encodable object failed" occurs.

Example:

@JsonSerializable()
class MyClass{
  dynamic field;
}

@JsonEnum()
enum MyEnum{
  @JsonValue(0) top,
  @JsonValue(1) middle,
}

void main() {
  MyClass()
    ..field = MyEnum.top
    ..myClass.toJson();
}

**Comment by kevmoo** [comment]
By design. We NEED the type info to do any type of conversion. `dynamic` (or Object, etc) only works with values that are already JSON-compatible.
