### ISSUE TITLE
`JsonEnum` allow to use `index` with `valueField`

### ISSUE THREAD

**Issue by Zekfad** [google/json_serializable.dart#1249]
Currently you can't set `valueFiled` in `JsonEnum` to `index`:

```log
`JsonEnum.valueField` was set to "index", but that is not a valid, instance field on `MyEnum?`.
```

As part of enhanced enums, every enum has `index` property (and `name`, actually, since 2.15).
So it would be helpful, to avoid making field that replicates `index` field.

* Flutter 3.6.0-4.0.pre.8 • channel master • https://github.com/flutter/flutter.git
* Framework • revision a2233eabed (2 hours ago) • 2022-11-16 10:20:45 -0800        
* Engine • revision 223e1f092d
* Tools • Dart 2.19.0 (build 2.19.0-406.0.dev) • DevTools 2.19.0

**Comment by kevmoo** [comment]
Good idea!
