### ISSUE TITLE
README.md is missing step-by-step setup instructions

### ISSUE THREAD

**Issue by eseidel** [google/json_serializable.dart#1251]
Every time I use json_serializable, I have to re-learn how to set it up.  I think it would benefit the community to have step-by-step instructions in the readme.

For example, what *exactly* is the minimum I need to add to build.yaml.

What pub dependencies do I need to add?  With what Dart command?

What VSC extensions (if any) should I be installing?

The example in example/ is incomplete because its not a whole separate pub package, and json_serializable requires some outside-of-a-dart-file work to get it to work.

**Comment by kevmoo** [comment]
See the content here: https://github.com/google/json_serializable.dart/tree/master/example

what else do you want?

**Comment by eseidel** [comment]
https://github.com/google/json_serializable.dart/tree/master/example is helpful (I'm not sure which example I was looking at before which didn't have its own separate pubspec.yaml).

**Comment by eseidel** [comment]
It looks like this example is linked to right away from the readme.  Not sure how I got myself confused.  I'm sure there is more we can do here, but my but isn't particularly helpful.  Closing.
