### ISSUE TITLE
Is it possible to extend a model with additional info

### ISSUE THREAD

**Issue by Nedimko123** [google/json_serializable.dart#1257]
This might be confusing...

Lets say we have a model

```dart
@JsonSerializable()
class Address {
  String street;
  String city;

  Address(this.street, this.city);

  factory Address.fromJson(Map<String, dynamic> json) =>
      _$AddressFromJson(json);
  Map<String, dynamic> toJson() => _$AddressToJson(this);
}
```

Is it possible that I can describe a specific field, for example street = "a public road in a city, town, or..."
The scenario is like this:
Text(Street.name, street.description)   //describes what a street is   --   Text( address[index].street),  //value for a specific address input
Text(City.name, city.description )   //describe what a city is          --   Text(address[index].city,) //value for a specific address input

the JSON is Map<String, dynamic> =  {'street' : 123 , 'city' : 123};

So I would make a helper class thats says street = {'name' : blabla, 'description' : blabla} etc...

In my case I have over 100 json fields, so I  think that creating 100+ models for each field might be time consuming

**Comment by kevmoo** [comment]
@Nedimko123 – it is confusing.

What code do you want to write and what code do you want generated?

**Comment by kevmoo** [comment]
We have to talk in terms of what code you want to write and what code you want generated.
