### ISSUE TITLE
getting error when adding json_serializable

### ISSUE THREAD

**Issue by Abhishekkapoor1** [google/json_serializable.dart#1261]
I added json serializabe in my pubspec.yaml and getting below error :

Bad state: Could not parse the options provided for json_serializable. 
Unrecognized keys: [super-parameters, enhanced-enums]; supported keys: [any_map, checked, constructor, create_factory, create_field_map, create_to_json, disallow_unrecognized_keys, explicit_to_json, field_rename, generic_argument_factories, ignore_unannotated, include_if_null]

**Comment by kevmoo** [comment]
Do you have a `build.yaml` file? What's in it?
