### ISSUE TITLE
If enum has toJson method, use it.

### ISSUE THREAD

**Issue by hurelhuyag** [google/json_serializable.dart#1273]
Let's consider this code example. If I run build runner, it generates `'status': _$CallStatusEnumMap[instance.status]!,`. It is correct. But when I uncomment the `toJson` method. Generated code changes into `'status': instance.status,`. It is wrong. it should keep previous code or should generate like `'status': instance.status.toJson(),`.
```dart
part 'call.g.dart';

@JsonEnum(fieldRename: FieldRename.snake)
enum CallStatus {
  failed,
  busy,
  congestion,
  noAnswer,
  answered;
  
  /*String toJson() => _$CallStatusEnumMap[this] ?? "no_value";*/
}

@JsonSerializable()
Call {
  const Call({
    required this.status,
  });

  final CallStatus status;
  
  factory Call.fromJson(Map<String, dynamic> json) => _$CallFromJson(json);

  Map<String, dynamic> toJson() => _$CallToJson(this);
}
```

`flutter --version`
```
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (2 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```

`dart --version`
```
Dart SDK version: 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "linux_x64"
```

**Comment by kevmoo** [comment]
Keep in mind, `toJson()` is automatically called with `jsonEncode` in the SDK.

I wonder what will happen if you set `explicit_to_json: true`
