### ISSUE TITLE
Generated code should use a string uri to point at the library it is a part of

### ISSUE THREAD

**Issue by jakemac53** [google/json_serializable.dart#1313]
Today generated json_serializable code triggers the `use_string_in_part_of_directives` lint - we should really not be doing this by name but by uri.

**Comment by kevmoo** [comment]
It should follow the pattern used by the part usage from the source library IIRC.

**Comment by kevmoo** [comment]
Pretty sure this is a `source_gen` issue, @jakemac53 !
