### ISSUE TITLE
How to generate only one new file 

### ISSUE THREAD

**Issue by manhtran-itr** [google/json_serializable.dart#1322]
I want to generate only new files created, don't want to re-generate the whole project files because it takes too long for generate and face the risks to modify them.

**Comment by kevmoo** [comment]
If build is used correctly, incremental builds will be FAST and you won't risk modifying any other files.

**Comment by manhtran-itr** [comment]
@kevmoo if there is any way to specify only one file to generate codes? I would like to build only new files, it will save time.

**Comment by kevmoo** [comment]
This is not specific to this package.

maybe look at https://github.com/dart-lang/build/blob/master/build_config/README.md ?

**Comment by manhtran-itr** [comment]
@kevmoo Thanks for your response!. I found a way to generate a specific file by adding generate_for into build.yaml file but 
I always get the error 
`Found 460 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`.`

Because of the error, I must add the option '--delete-conflicting-outputs' it deletes all my files generated before I don't expect that. I want to generate a specific file and ignore all the previous files generated.

**Comment by kevmoo** [comment]
@manhtran-itr – please start a discussion on the build repo. This is not related to this package.
