### ISSUE TITLE
 Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'.

### ISSUE THREAD

**Issue by moyinqingshang** [google/json_serializable.dart#1336]
Failed to build build_runner:build_runner:
/Applications/flutter/flutter3.3.2/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.3.0/lib/src/dart/ast/ast.dart:8153:48: Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'.
 - 'NodeListImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('/Applications/flutter/flutter3.3.2/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
 - 'TypeAnnotationImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('/Applications/flutter/flutter3.3.2/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
Try correcting the name to the name of an existing method, or defining a method named 'elementAtOrNull'.
    var elementType = typeArguments?.arguments.elementAtOrNull(0)?.typeOrThrow;

每次运行flutter packages pub run build_runner build就会报错
json_serializable: 6.6.1
  json_annotation: 4.8.0
flutter:3.3.2

**Comment by kevmoo** [comment]
Have you tried running `pub upgrade`?
When you run `pub upgrade` are there any dependencies that are NOT updated?
