### ISSUE TITLE
Unhandled Exception cannot be caught on `catch` block

### ISSUE THREAD

**Issue by coder-Aayush** [google/json_serializable.dart#1338]
Hi, 
I have been using `json_serializable` package for serializing data from API request but sometimes, the data are not accurate what types is been defined. So, I want to catch and throw some kind of error but it's not going on catch block. 

## Sample Code
```dart
 try {
      final response =  await http.get("")
      return  JsonModel.fromJson(response);
    } catch (e) {
      throw AppException(message: e.toString());
    }
```

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'json_model.g.dart';
part 'json_model.freezed.dart';

@freezed
class JsonModel with _$JsonModel {
  const factory JsonModel({
    required int id,
    required String name,
    required String address,
    required String shortName,
  }) = _JsonModel;
  factory JsonModel.fromJson(Map<String, dynamic> json) =>
      _$JsonModelFromJson(json);
}

```

I am Expecting it should throw Exception for format error.

**Comment by kevmoo** [comment]
Maybe try https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/checked.html ?

**Comment by coder-Aayush** [comment]
@kevmoo can you please provide me sample code?
