### ISSUE TITLE
Ability to pinpoint where fromJson throws an error

### ISSUE THREAD

**Issue by martinralfreindl** [google/json_serializable.dart#1381]
Suppose I have a large and very nested json that represents a user. The json has tons of attributes (over 200 of them), but deeply nested in that json under user->settings->general there is a field called `age`, where the user's age is defined as an integer. If my backend somehow forgets to fill in this age field, json_serializable will now throw an error along the lines of: 

> Expected a value of type 'num', but got one of type 'Null'

It's nice that I get the error, but now I have to go find which of  those 200 fields the error is from, and that takes forever.  Would it be possible to improve json_serializable error message along the lines of: 
> Field "user->settings->general->age" expected a value of type 'num', but got one of type 'Null'

This would make it way easier for us to detect errors in large files

**Comment by Swayambhoo-Manu** [comment]
I also think this feature would be really helpful.

**Comment by kevmoo** [comment]
Already have it. Look at the "checked" property -
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/checked.html

**Comment by martinralfreindl** [comment]
Amazing. Thank you so much. Worked like a charm!
