### ISSUE TITLE
Omit properties from `toJson()` when value is null

### ISSUE THREAD

**Issue by lukehutch** [google/json_serializable.dart#1385]
Given a serializable class with nullable fields `firstName` and `lastName`:

```dart
@JsonSerializable()
class Person {
  final String? firstName, lastName;

  Person({required this.firstName, required this.lastName});

  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);

  Map<String, dynamic> toJson() => _$PersonToJson(this);
}
```

currently the code generator generates the following `toJson` method given a nullable field `someNullableField`:

```dart
Map<String, dynamic> _$PersonToJson(Person instance) => <String, dynamic>{
      'firstName': instance.firstName,
      'lastName': instance.lastName,
    };
```

I don't know if null values are serialized into a JSON string as 

```json
{ "someNullableField": null }
```

of if the map entry is simply omitted by the JSON string serializer when the value is `null`, but either way, it would be more optimal in terms of time and space to only add non-null fields to the map:

```dart
Map<String, dynamic> _$PersonToJson(Person instance) => <String, dynamic>{
      if (instance.firstName != null) 'firstName': instance.firstName,
      if (instance.lastName != null) 'lastName': instance.lastName,
    };
```

Related:
* #1369
* #1340
* #1356

**Comment by jtmuller5** [comment]
Can't you just set [includeIfNull](https://pub.dev/documentation/json_serializable/latest/type_helper/ClassConfig/includeIfNull.html) to false?

**Comment by lukehutch** [comment]
I didn't know about that. Thank you!
