### ISSUE TITLE
Generate an object to access json keys

### ISSUE THREAD

**Issue by ChreSyr** [google/json_serializable.dart#1400]
Hey !

It would be very nice to have a way to link the properties to their json keys. It would reduce the margin of error. For exemple, in my case, it would be for Firebase filters.

from : `Filter('datetime_start', isGreaterThan: ...)`
to : `Filter(MyModel.jsonKeys.dateTimeStart, isGreaterThan: ...)`

I know there already is the parameter 'create_field_map' which allows for `Filter(MyModel.fieldMap['dateTimeStart'], isGreaterThan: ...)` but it's safer to use properties instead of strings.

**Comment by ArthurREGNARD** [comment]
greate feature, need it !!

**Comment by aliaksei-liavonik** [comment]
That sounds good, also need it. To specify the list of fields for JSON_API-based server to return only needed fields, instead of listing all of the fields by hand from DTO objects
