### ISSUE TITLE
Decimal, API and SQLite

### ISSUE THREAD

**Issue by alexrosabr** [google/json_serializable.dart#1421]
### FromJson
The generated code uses `as String` but when the data comes from the API it fails with:
```
type 'double' is not a subtype of type 'String' in type cast
```
If I edit the generated code to use `.toString()` instead, it works.

### ToJson
The generated code does not work with SQLite; the warning message says it will allow it for now but the warning may become an error in the future.

If I edit the generated code to use `?.toDouble()` it works.

### Edited code (to make it work)

```dart
ApiPdvTroco _$ApiPdvTrocoFromJson(Map<String, dynamic> json) => ApiPdvTroco()
  ..cedula = json['cedula'] as bool?
  ..quant = json['quant'] as int?
  ..valor =
      json['valor'] == null ? null : Decimal.fromJson(json['valor'].toString());

Map<String, dynamic> _$ApiPdvTrocoToJson(ApiPdvTroco instance) =>
    <String, dynamic>{
      'cedula': instance.cedula,
      'quant': instance.quant,
      'valor': instance.valor?.toDouble(),
    };
```

Is there a way to configure "json_serialize" to generate code like this?

**Comment by kevmoo** [comment]
You need to use a converter. See https://pub.dev/packages/json_serializable#custom-types-and-custom-encoding

**Comment by alexrosabr** [comment]
Thanks! For reference, here's my `DecimalConverter`:

```dart
class DecimalConverter implements JsonConverter<Decimal?, dynamic> {
  const DecimalConverter();

  @override
  Decimal? fromJson(dynamic json) => Decimal.tryParse('$json');

  @override
  double? toJson(Decimal? object) => object?.toDouble();
}
```

I had to use `dynamic` -- the API may return `{"multiplier":0}` sometimes.
