### ISSUE TITLE
build_runner failed after upgrading my flutter

### ISSUE THREAD

**Issue by casontek** [google/json_serializable.dart#1427]
i am unable to generate my model file after upgrading my flutter and dart sdk

`dart --version`
Dart SDK version: 3.5.0-103.0.dev (dev) (Thu Apr 25 17:03:06 2024 -0700) on "macos_x64"

`flutter --version`
Flutter 3.22.0-18.0.pre.30 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5f0628d335 (11 days ago) • 2024-04-26 02:23:26 -0400
Engine • revision d794580077
Tools • Dart 3.5.0 (build 3.5.0-103.0.dev) • DevTools 2.35.0-dev.8

`pubspec.yaml`

environment:
  sdk: '>=3.3.0-273.0.dev <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

`model object`

import 'package:json_annotation/json_annotation.dart';

part 'p_user.g.dart';

@JsonSerializable()
class User {
  String name;
  String phone;
  String state;
  String country;
  String address;

  User({
    this.name = '',
    this.phone = '',
    this.country = '',
    this.address = ''
  });

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);

}
  
  
`Build Error`

[INFO] Precompiling build script... completed, took 147ms
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

**Comment by piotrkovsy1331** [comment]
Sadly I'm facing the same issue.

**Comment by kevmoo** [comment]
have you tried running `dart pub upgrade`?

**Comment by jakemac53** [comment]
You need the latest frontend_server_client package (this is a transitive dependency). Running `dart pub upgrade` (or `flutter pub upgrade`) should do the trick.

**Comment by robot-den** [comment]
`dart pub upgrade` helped. 

I will write our error, so after search indexing some devs will find this solution faster
```
Error: No named parameter with the name 'isNonNullableByDefault'
Context: Found this candidate, but the arguments don't match.
```

**Comment by kevmoo** [comment]
Very thoughtful, @robot-den !! 🙏

**Comment by ROD-MASAMI** [comment]
@robot-den God bless you

**Comment by ahsys-app** [comment]
> have you tried running `dart pub upgrade`?

Work for me, Thanks @kevmoo 👏

**Comment by FullStackMusa** [comment]
> have you tried running `dart pub upgrade`?

Thanks work like a charm 👍
