### ISSUE TITLE
Asynchronous fromJson 

### ISSUE THREAD

**Issue by HeropolisDa2ny** [google/json_serializable.dart#1439]
There is currently an issue with asynchronous variables on this package if we want our project to be functional offline.
If for example we want to get an image from an API to fill it into the model, we're forced either to get it after the parsing done or before by modifying the json right after the reception of the request.

We also have the possibility to use `createFactory: false`. However using createFactory returns to just do not use json_serializable at all because every extends class will have to use `createFactory: false`.

Here's a way to do it without using flutter_serializable :

```
static Future<ModelImage> fromMap(Map<String, dynamic> map) async {
    Future<Uint8List>? getBytesFromUrl(String url) {
      return http.readBytes(Uri.parse(url));
    }

    return ModelImage(
        map['value'] != null ? await getBytesFromUrl(map['value']) : null);
  }
```

The fromJson is instantiated with a factory in json_serializable, that doesn't allow any use of async inside of it. I would like to know if it was possible to instantiate a param or something else to work with async fromJson, or if it was possible to create a feature to allow that kind of use ? Because right now it's really annoying to create models without this possibility.

flutter --version
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

Related issue (https://github.com/google/json_serializable.dart/issues/1306) was forgotten for a year.

**Comment by kevmoo** [comment]
I know it's annoying, but you'll have to create two layers of objects.

One with the `url` as a field and another with the `image` byte data as a field.

You can save a lot of code by sharing a base class.

It'll be too much work to add support for async types in the serializer.
