### ISSUE TITLE
Consider support aliases for name: for @JsonKey

### ISSUE THREAD

**Issue by Reekoooo** [google/json_serializable.dart#144]
I can't  do this: 
@JsonKey(name: "text", alternate = {"full_text"})
  String text;

in **gson** I can do something like:
@SerializedName(value = "text", alternate = {"full_text"})
    public final String text;

**Comment by kevmoo** [comment]
To be clear, you want the option of reading `test` or `full_text` when deserializing?

**Comment by Reekoooo** [comment]
the attribute sometimes is _"text"_ and some times is _"full_text_" i want to pick automatically between the two by providing alternate or alias name for the attribute i want to deserialize .. like I showed in the actual issue I want the equivalent of 
 
@serializedname(value = "text", alternate = {"full_text"})
public final String text;

**Comment by walkermanx** [comment]
**yes. i need this too much! **

**Comment by walkermanx** [comment]
**### i will follow this issue. looking forward to  the coming updates solving it .**

**Comment by kevmoo** [comment]
Happy to take a PR here.

**Comment by Jerry805** [comment]
Is this supported now?

**Comment by kevmoo** [comment]
> Is this supported now?

If any work happens here, this issue will be updated
