### ISSUE TITLE
Add kebab- and snake-case options to entire enum via annotation

### ISSUE THREAD

**Issue by enyo** [google/json_serializable.dart#297]
Now that the great feature of specifying a `FieldRename` strategy to a `JsonSerializable` class has been added, it would be great if the same functionality could be used on `enums`.

If I'm not mistaken, right now, the only way to do it, is like this:

```dart
enum RoutingCodeType {
  @JsonValue('sort_code')
  sortCode,
  @JsonValue('bsb_code')
  bsbCode
 }
```

Something like this would be great:

```dart
@JsonSerializableEnum(fieldRename: FieldRename.snake)
enum RoutingCodeType {
  sortCode,
  bsbCode
 }
```

**Comment by kevmoo** [comment]
Low-pri for me. If you want to implement it, I'm happy to review.

**Comment by enyo** [comment]
I can have a look. Would you introduce a new annotation class that can be added to enums, like `JsonSerializableEnum`?

**Comment by lukepighetti** [comment]
What if it followed the case transform on the parent serializable class?

```dart
@JsonSerializable(fieldRename: FieldRename.snake)
class MyClass {
  final MyEnum enum;

  /// ...
}

enum MyEnum {firstField, secondField}
```

**Comment by kevmoo** [comment]
> What if it inherited fieldRename from the parent serializable class?
> 
> ```dart
> @JsonSerializable(fieldRename: FieldRename.snake)
> class MyClass {
>   final MyEnum myEnum; // my_enum
> 
>   /// ...
> }
> 
> enum MyEnum {firstField, secondField} // first_field, second_field
> ```

The problem with that, @lukepighetti is that I generate one set of helpers for a given enum – so I'd rather not have parent-class-specific configuration

**Comment by lukepighetti** [comment]
In that case the previous suggestion seems like the remaining way to handle it.

**Comment by petrnymsa** [comment]
Would like to see this implemented. From our API source, I am getting object properties with camelCase but enum values as PascalCase... so the only way right now to handle this is via `JsonValue` on each enum value, which is really tedious to do so.

**Comment by kevmoo** [comment]
In progress: https://github.com/google/json_serializable.dart/pull/992
