### ISSUE TITLE
Allow different json generation from same class 

### ISSUE THREAD

**Issue by Nico04** [google/json_serializable.dart#439]
I use serialization/deserialization for both web services and local save. But both JSON needs to be a bit different (some field are included in local but not in the Web services and vice versa), while using the same dart class. How can I achieve that? 
Thanks a lot!

**Comment by Nico04** [comment]
Any idea on this?

**Comment by kevmoo** [comment]
You'd have to do some deep hacking into this package, I think.

It might be possible w/ subclasses – or mixins, but I'm not sure.

**Comment by Nico04** [comment]
Ok so your point is that you do not recommend it...
Thanks 😅

**Comment by kevmoo** [comment]
Not that I don't recommend – It's that I haven't spent any time on it. Might be possible. Just don't know. 🤷‍♂

**Comment by dt-ap** [comment]
Bump. I need this functionality also. Might be someone who read this Issue could give some guidance how to tacke this problem? 
For now, I am manually writes the mapping of _Json_ and from _local db_ without this library. 

I've tried using interface class, like so:
```dart
abstract class TestInt {
  final int v1;
  // constructor here
}

class TestModel implements TestInt {
  final int v1;
  ...
}

class TestJSON implements TestInt {
  @JsonKey(name: 'v1JSON')
  final int v1;
  ...
}

class TestDB implements TestInt {
  @JsonKey(name: 'v1DB')
  final int v1;
  ...
}
```

But then I have to write the mapping from TestDB/TestJson to TestModel manually. And It gives me plus two more class for one model class. 
Wish I can pick and choose the class field to generate the **toJson** and **fromJson**.

**Comment by kevmoo** [comment]
I'm open to a concrete recommendation of what's wanted here, but I worry about the added complexity.

**Comment by kevinelliott** [comment]
I would also like something that does this. The JSON I parse is in a format I don't prefer, and I'd like to be able to generate JSON that has the attributes named differently.

**Comment by k-paxian** [comment]
@Nico04 @dt-ap 

Gentleman's, I think [this implementation](https://github.com/k-paxian/dart-json-mapper#schemes) is somewhat closer to what's needed in this issue, I'm right?

**Comment by kevmoo** [comment]
Closing this out. Not planned.
