### ISSUE TITLE
support for nested items in @JsonKey(name:)

### ISSUE THREAD

**Issue by KorbinianMossandl** [google/json_serializable.dart#490]
It would be great if we could directly access nested items in the `name` String of `@JsonKey`. Consider this Json:

```JavaScript
"root_item": {
    "items": [
        {
            "name": "first nested item"
        },
        {
            "name": "second nested item"
        }
    ]
}
```

I would like to do:

```Dart
@JsonKey(name: "root_item/items")
List<NestedItem> nestedItems;
```

Sorry if this is already possible, but i could not find anything.

**Comment by kevmoo** [comment]
Interesting idea. It is currently not supported.

**Comment by vanlooverenkoen** [comment]
This should really be added. Now we have to create extra objects because we had to use a crappy backend. Using a simple api to flatten your backend models

**Comment by huanxsd** [comment]
I really need this feature. Is it supported now?

**Comment by vanlooverenkoen** [comment]
Is there a roadmap for this feature? What timeframe could we expect for a P2?

**Comment by k-paxian** [comment]
If you guys are still waiting for that feature, this library already has it implemented
https://github.com/k-paxian/dart-json-mapper#nesting-configuration

**Comment by vanlooverenkoen** [comment]
Thanks. but I need to use json_serializable. Because I am using retrofit.dart that uses toJson and fromJson.

**Comment by kevmoo** [comment]
PRs welcome here!

**Comment by NicolaChimerapps** [comment]
I am working on an implementation for this.
Rough draft can be found here: https://github.com/Chimerapps/json_serializable/tree/feature/json_path

WIP, not ready for production

**Comment by mokai** [comment]
Necessary function !

**Comment by taoyimin** [comment]
I really need this feature!

**Comment by masewo** [comment]
I forked @NicolaChimerapps fork and corrected two small errors:
https://github.com/masewo/json_serializable/tree/feature/json_path
For now it is working for me.

**Comment by kevmoo** [comment]
@masewo and @NicolaChimerapps – I'll happily take a solid PR with testing, etc

**Comment by ouyanghuacom** [comment]
It's wishful for me.

**Comment by jeffaknine** [comment]
Any update on this ?

**Comment by miguelpruivo** [comment]
Bumping as this is a must have.

**Comment by kevmoo** [comment]
Pull requests welcome – beyond the core features offered now, this package is a "beyond work hours" project.

**Comment by hacker1024** [comment]
If #783 gets merged, this will be possible, albeit in a convoluted manner:

```dart
@JsonSerializable()
class MyObject {
  @JsonKey(name: 'myRegularField')
  final String myRegularField;

  @JsonKey(extra: true)
  final String myNestedField;

  MyObject({
    required this.myRegularField,
    required this.myNestedField,
  });

  factory MyObject.fromJson(Map<String, dynamic> json) {
    return _$MyObjectFromJson(
      json,
      myNestedField: json['myInnerObject']['myNestedField'],
    );
  }
  
  Map<String, dynamic> toJson() {
    final output = _$MyObjectToJson(this);
    output['myInnerObject'] = {'myNestedField': myNestedField};
    return output;
  }
}
```

**Comment by NicolaVerbeeck** [comment]
How does 368a8c7 fix this?

**Comment by kevmoo** [comment]
gah! Wrong issue!

**Comment by CiriousJoker** [comment]
Any news on this?

**Comment by kevmoo** [comment]
There is NOT an open PR on this. That was a mistake.

The issue here: we need some other syntax for key that's not a `String` because any `String` can be a valid key in a JSON map. So we'd need to support `List<String>` for key – or add another value. Both of which are quite a bit of work!

**Comment by ad-on-is** [comment]
> There is NOT an open PR on this. That was a mistake.
> 
> The issue here: we need some other syntax for key that's not a `String` because any `String` can be a valid key in a JSON map. So we'd need to support `List<String>` for key – or add another value. Both of which are quite a bit of work!

How about something like

```dart
@JsonSerialiable(explicitJson: true, keySeparator: ">")


class Person {
@JsonKey(name: 'name>fist_name')
String name;
}

```

**Comment by kevmoo** [comment]
After consideration, I've decided not to invest time here. It adds a LOT of complexity.

If you still want this feature, it's pretty easy to implement with a `JsonConverter`

See https://github.com/google/json_serializable.dart/blob/master/example/lib/nested_values_example.dart

**Comment by qevka** [comment]
> After consideration, I've decided not to invest time here. It adds a LOT of complexity.
> 
> If you still want this feature, it's pretty easy to implement with a `JsonConverter`
> 
> See https://github.com/google/json_serializable.dart/blob/master/example/lib/nested_values_example.dart

That would be nice if JsonConvert was actually working. I am having the same problem that is mentioned here: https://github.com/google/json_serializable.dart/issues/1066

**Comment by Alameen688** [comment]
In my case I didn't need the `toJson` data to transform data back to the original structure I just needed to read the correct data and `readValue` worked perfectly fine in combination with [deep_pick](https://pub.dev/packages/deep_pick).

```dart
@JsonKey(readValue: readNestedItems)
List<NestedItem> nestedItems;
```

```dart
  static List<String, dynamic> readNestedItems(Map json, String key) {
    final fields = pick(json, key, 'items').asListOrEmpty(_yourFromPickFunction);
    return fields;
  }
```

**Comment by bojanivanovski** [comment]
Hi,

First of all I am sorry to hear that this feature will not be implemented any time soon, because it will help with a lot of problems with nested json data.

For example, I am using YouTube Data API, and to get the needed info for a video the fromMap method looks like this:

```
  factory Video.fromMap(Map<String, dynamic> snippet) {
    return Video(
      id: snippet['resourceId']['videoId'],
      title: snippet['title'],
      thumbnailUrl: snippet['thumbnails']['high']['url'],
      channelTitle: snippet['channelTitle'],
    );
  }
```
how can I solve this problem using the package without the support for nested items? 
Thanks

**Comment by Veeksi** [comment]
> > After consideration, I've decided not to invest time here. It adds a LOT of complexity.
> > If you still want this feature, it's pretty easy to implement with a `JsonConverter`
> > See https://github.com/google/json_serializable.dart/blob/master/example/lib/nested_values_example.dart
> 
> That would be nice if JsonConvert was actually working. I am having the same problem that is mentioned here: #1066
> 
> I tried downgrading my build_runner and json_annotation packages and also tried just using your code directly neither worked.

I am also having this exact same problem with the explicit json converter

**Comment by JPaulMora** [comment]
Chiming in to show support/need for this functionality.

**Comment by rignaneseleo** [comment]
Up

**Comment by EvGeniyLell** [comment]
i'm use next solution
```dart
@freezed
class MyDto with $MyDto {
     ...
    @JsonKey(readValue: nestedReader, name: 'lastLocation/lng')
    double? test,
    ...
}
```
where
```dart
Object? nestedReader(Map json, String key) {
  Object? result = json;
  final subKeys = key.split('/');
  for (final subKey in subKeys) {
    final subResult = result;
    if(subResult is Map) {
      result = subResult[subKey];
    } else {
      return null;
    }
  }
  return result;
}
```

**Comment by EvGeniyLell** [comment]
I'm use next solution
```dart
@JsonKey(readValue: nestedReader, name: 'extras/apiKey') List<String>? extras,
```
where  `nestedReader` is
```dart
Object? nestedReader(Map json, String key) {
  final keys = key.split('/');
  return _nestedReader(json, keys);
}

Object? _nestedReader(final Object object, Iterable<String> keys) {
  if (keys.isEmpty) {
    return object;
  }
  if (object is Map) {
    final subObject = object[keys.first];
    final subKeys = keys.skip(1);
    return _nestedReader(subObject, subKeys);
  }
  if (object is List) {
    return object.map((subObject) => _nestedReader(subObject, keys));
  }
  return object;
}
```

for this test
```dart
void main() {
  final Map map = {
    'extras': [
      {'apiKey': 1, 'name': 'a'},
      {'apiKey': 3, 'name': 'b'},
      {'apiKey': 5, 'name': 'c'},
      {'apiKey': 7, 'name': 'd'},
    ]
  };

  final result = nestedReader(map, 'extra/apiKey');
  print('result $result');
}
```
result will be
> result (1, 3, 5, 7)

**Comment by phamquoctrongnta** [comment]
There is no solution to this problem in 2024

**Comment by creativecreatorormaybenot** [comment]
@phamquoctrongnta check https://github.com/google/json_serializable.dart/commit/2dfffd0df2abc4592b37e75de2ee75932711c503.
