### ISSUE TITLE
Add support for annotating a specific constructor to be used

### ISSUE THREAD

**Issue by jakemac53** [google/json_serializable.dart#50]
This allows you to not have a public constructor, or have a specialized one just for json serialization.

**Comment by leoshusar** [comment]
Any idea when this could be on the roadmap?

I am trying to allow setting ID only by JSON deserialization and private constructor would be perfect for this:

```dart
class User {
  final String? id;
  String name;

  User._(this.id, this.name); // use for deserialization
  User(this.name)
    : id = null;
}
```

My other idea was to use private field and public setter, but private fields are ignored, so that's another no way.

**Comment by kevmoo** [comment]
Fixed in https://github.com/google/json_serializable.dart/commit/368a8c704b3caf0c57bc32af26666a92b37545e6

**Comment by kevmoo** [comment]
Landed in https://pub.dev/packages/json_serializable/versions/6.0.0
