### ISSUE TITLE
Comply with strict-raw-types in generated code

### ISSUE THREAD

**Issue by natebosch** [google/json_serializable.dart#517]
For the most part this means when we do `as List` we should be doing `as List<dynamic>`

**Comment by kevmoo** [comment]
Ugh. I played with this a bit. It's noisy. But I get it...

**Comment by kevmoo** [comment]
@natebosch – got you started here https://github.com/dart-lang/json_serializable/pull/519

**Comment by kevmoo** [comment]
Not going to do this.
