### ISSUE TITLE
consider support "Generators with constructor arguments "

### ISSUE THREAD

**Issue by rostyslavroshak** [google/json_serializable.dart#520]
Let's say you have a custom data type for units, with constructor like following:
```dart
class Temperature {
   Temperature(TemperatureUnit unit, double value)...
}
```
And you have a json, where all the values for temperatures are double, which represent temperature in  Fahrenheit.

It will be very nice to be able to use converters like following:
```
  @JsonKey(name: 'temperatureDewPoint')
  @TemperatureConverter(TemperatureUnit.F)
  final List<Temperature> temperatureDewPoint;
```
`TemperatureConverter` is a `JsonConverter`, but it has a constructor parameter.

So right now I have to add into `TemperatureConverter` fields:
```
  static const C = TemperatureConverter._(TemperatureUnit.C);
  static const F = TemperatureConverter._(TemperatureUnit.F);
```
and use it as 
```
  @JsonKey(name: 'temperatureDewPoint')
  @TemperatureConverter.F
  final Temperature dewPoint;
```

**Comment by kevmoo** [comment]
Nice to have. I'd accept a PR for this if it was well implemented and tested!

**Comment by avioli** [comment]
Could I ask why "Generators with constructor arguments are not supported"?

Is it because the arguments could be non-const values?

**Comment by spixy** [comment]
Generators have to be `const`, and `const` constructors cannot have non-`const` argument values.

**Comment by kevmoo** [comment]
I'd simply add in a constructor for the cases you care about

Like `TemperatureConverter.Celsius` etc.

The reason they are supported now: we have to create custom logic to parse out the ctor arguments to create an instance. This is tough and error prone.
