### ISSUE TITLE
Don't create empty objects in a List

### ISSUE THREAD

**Issue by lookfirst** [google/json_serializable.dart#521]
This will generate an empty `{}` within `Shelf.books`. I'd prefer it if it just put a null into Shelf.books. Maybe I'm missing something.

```
@JsonSerializable(includeIfNull: false, nullable: true)
class Book {
  @JsonKey(toJson: normalizeName)
  String name;

  String normalizeName() {
    return null;
  }
  factory Book.fromJson(Map<String, dynamic> json) => _$BookFromJson(json);
  Map<String, dynamic> toJson() => _$BookToJson(this);
}

@JsonSerializable()
class Shelf {
    @JsonKey()
    List<Book> books;
  factory Shelf.fromJson(Map<String, dynamic> json) => _$ShelfFromJson(json);
  Map<String, dynamic> toJson() => _$ShelfToJson(this);
}
```

Looking at the code, it seems like complicating the output of `_writeToJsonWithNullChecks` (which generates the `_$BookToJson` method) to count if any fields have been written via `writeNotNull` and if not, just return null instead of an empty object.

The point being is that without this fix, I have to check to see if Shelf.books[index].name exists as a property as well as check to see if Shelf.books[index] is null. It is less code to just do the null check.

**Comment by lookfirst** [comment]
Changing  ```  Map<String, dynamic> toJson() => _$BookToJson(this);```

to:

```
  Map<String, dynamic> toJson() {
    final result = _$BookToJson(this);
    return (result['name'] == null) ? null : result;
  }
```

Is what I'm talking about... but I'd like it to be done internally.

**Comment by kevmoo** [comment]
Not going to add a special one-off for this. Your solution looks fine.

**Comment by Dieterbe** [comment]
@nzackoya writeNotNull is a helper function that is generated when you use the `  includeIfNull: false` option in your annotation/configuration. it is used to not write fields if they are null.
```
  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }
```
