### ISSUE TITLE
Empty object

### ISSUE THREAD

**Issue by Tokenyet** [google/json_serializable.dart#538]
## Enviroment
Flutter 1.10.1-pre.41 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5a3a46ada2 (9 days ago) • 2019-09-07 18:37:41 -0400
Engine • revision c9ea4dba8d
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 ec7ec4ecf7)
build_runner: ^1.6.1
json_serializable: ^3.1.0

Is there any way to slove `{}` with builtin way? I had a null object returned `{}`, so I had to write custom `fromJson` to `JsonKey`. Below code sloved my problem, but I wanna check If there is more elegant way to check for all fields.

```dart
  static _bankFromJson(Map<String, dynamic> json) {
    if(json['bank'] == null)
      return null;
    else
    {
      if(json['bank'] is Map)
        if(json['bank'].keys.length == 0)
          return null;
      return CompanyBank.fromJson(json['bank'] as Map<String, dynamic>);
    }
  }
  @JsonKey(fromJson: _bankFromJson)
  CompanyBank bank;
```

**Comment by kevmoo** [comment]
In this case it looks like you have `{"bank":{"bank":...}}`, right?

**Comment by Tokenyet** [comment]
This issue is a bit long for me, but I think It was the problem in the case as below:

```
{
    "bank": {}
}
```

This should be fixed in the backend:

```
{
    "bank": null
}
```

I'm not sure If I should keep this issue open or not, because this wasn't a workaround for frontend side.

**Comment by kevmoo** [comment]
I don't think we're going to add special handling here. It'd add too much complexity.

**Comment by 1207roy** [comment]
@kevmoo @Tokenyet 
Can you guys please suggest any way to achieve this?
I have been using json_serializable for a very long time and suddenly I have been asked to handle this from the front end side as many third-party APIs are sending this type of empty map in API response json!

**Comment by kevmoo** [comment]
@1207roy – have you tried using a custom converter?

**Comment by kevmoo** [comment]
@1207roy – I think so.

To be clear on your request here: you want `treateEmptyAsNull`, right?

**Comment by 1207roy** [comment]
@kevmoo 
Yes exactly like that
as @Tokenyet has given the example, I need that for all of my models(consider 100+ models)

So I am thinking, like this:
@JsonSerializable(**treateEmptyAsNull: true**, explicitToJson: true) and/or 
@JsonKey(**treateEmptyAsNull: false**)

so when the fromJson is generated, it will check always like if it is empty then create it as null, instead of creating an instance with all of its fields as null(**"bank": {}**)
