### ISSUE TITLE
If list is null, it will throw exception.

### ISSUE THREAD

**Issue by JamesKarl** [google/json_serializable.dart#583]
Dart code.
```
@JsonSerializable()
class StoreModel {
final List<String> imageUrls;
}
```
Generated Code.
```
StoreModel _$StoreModelFromJson(Map<String, dynamic> json) {
  return StoreModel(
    (json['imageUrls'] as List)?.map((e) => e as String)?.toList()
  );
}
```
### (json['imageUrls'] as List) may throw Exception if json['imageUrls'] is null.

**Comment by kevmoo** [comment]
We really need this feature –  https://github.com/dart-lang/language/issues/399

I'm worried about the ugly code that will be required without it 😕

**Comment by lukepighetti** [comment]
We can't null coalesce the result to `?? []`?

**Comment by kevmoo** [comment]
Did you try using a default value of a `const []` – I forget if that works or not...

**Comment by kevmoo** [comment]
Or maybe we just need to wait until null safety lands – it's coming along nicely!

**Comment by lukepighetti** [comment]
Thanks for the tip. Can't try it now but I'll reach out again if the issue arises. Can't wait for NNBD!

**Comment by kevmoo** [comment]
Migrating json_serializable to it is going to be a BEAR! I'm looking
forward to it, too

**Comment by kevmoo** [comment]
I think this is fixed. Please reopen if not!
