### ISSUE TITLE
Support custom Iterator/List types

### ISSUE THREAD

**Issue by MisterJimson** [google/json_serializable.dart#593]
I'm looking at how it can be possible to support Iterators that are not supported by default in 
json_serializable.

Examples are `ObservableList ` from Mobx or `BuiltList` from built_collection.

I am able to implement a basic solution, however it requires a JsonConverter for every type you plan to use with those Lists.

One example here: https://mobx.pub/guides/json shows that it works, but that Converter only works for `ObservableList<Todo>`, not `ObservableList<T>`. (And of course T in this case is either a basic JSON type or has a `toJson` method).

Another example from my codebase using `BuiltList`.

```dart
class BuiltListConverterNote
    implements JsonConverter<BuiltList<Note>, List<Map<String, dynamic>>> {
  const BuiltListConverterNote();

  @override
  BuiltList<Note> fromJson(List<Map<String, dynamic>> json) =>
      BuiltList.of(json.map((x) => Note.fromJson(x)));

  @override
  List<Map<String, dynamic>> toJson(BuiltList<Note> list) =>
      list.map((x) => x.toJson()).toList();
}

@JsonSerializable()
class ServiceOrder {
  @BuiltListConverterNote()
  final BuiltList<Note> notes;
}
```

The above works, but again I need to create that JsonConverter for every type like Note I want to use.

I'm looking for something like the following.

```dart
final factories = <Type, Function>{
  Note: (Map<String, dynamic> json) => Note.fromJson(json)
};

T make<T>(Type type, Map<String, dynamic> x) {
  return factories[type](x);
}

class BuiltListConverter<T>
    implements JsonConverter<BuiltList<T>, List<Map<String, dynamic>>> {

  const BuiltListConverter();

  @override
  BuiltList<T> fromJson(List<Map<String, dynamic>> json) =>
      BuiltList.of(json.map((x) => make(T, x)));

  @override
  List<Map<String, dynamic>> toJson(BuiltList<T> list) =>
      list.map((x) => (x as dynamic).toJson()).toList();
}

@JsonSerializable()
class ServiceOrder {
  @BuiltListConverter()
  final BuiltList<Note> notes;
}
```

This currently doesn't work.

```
Error running JsonSerializableGenerator
Could not generate `fromJson` code for `notes`.
None of the provided `TypeHelper` instances support the defined type.
package:hx_tech_app/domain/models.dart:28:25
   ╷
28 │   final BuiltList<Note> notes;
   │                         ^^^^^
   ╵

```

Is there a different way I should approach this? Perhaps a TypeHelper? 

I have been looking online for documentation for adding TypeHelper but I can't find any anywhere and the example in this repo does not add TypeHelpers.

**Comment by kevmoo** [comment]
Custom TypeHelper is your only path here.

You're right, we don't have a lot of docs on how to set those up. You have
to create your own builder, which takes some work!

**Comment by MisterJimson** [comment]
Thanks for the confirmation @kevmoo. Glad I wasn't missing something obvious.

It does seem like a feature to allow users to support custom list types without a TypeHelper would be cool. I've updated the title of this issue to reflect.

**Comment by knaeckeKami** [comment]
Could you point us in a direction on how to implement a custom TypeHelper?
I'd like to use custom list classes so that my models behave like value types.

**Comment by kevmoo** [comment]
> Could you point us in a direction on how to implement a custom TypeHelper?
> I'd like to use custom list classes so that my models behave like value types.

We don't have docs here. I exposed these types as a courtesy for relatively advanced and highly motivated users.

I totally admit, this is missing from the package – it's just not a high priority work item for me. Sorry. 🤷‍♂

**Comment by knaeckeKami** [comment]
@MisterJimson If you still need this, I wrote a package that add a custom builder that supports BuiltList and BuiltSet.

https://github.com/knaeckeKami/immutable_json_list_serializer

If you like, check it out and report to me if you run into any issues!

**Comment by subzero911** [comment]
@knaeckeKami wrote a cool new package which serializes MobX Observable collections, check it out
https://pub.dev/packages/json_serializable_mobx

**Comment by kevmoo** [comment]
FYI – https://github.com/google/json_serializable.dart/pull/710

**Comment by knaeckeKami** [comment]
Is it possible to (de)-serialize types that one does not own (e.g. from third-party libraries like BuiltList) with this approach? If yes, I could deprecate my packages.

**Comment by kevmoo** [comment]
> Is it possible to (de)-serialize types that one does not own (e.g. from third-party libraries like BuiltList) with this approach? If yes, I could deprecate my packages.

Not yet. That's the NEXT thing I'm working on...

**Comment by knaeckeKami** [comment]
Great, thanks for the info!

**Comment by friebetill** [comment]
Is there any news on this?
> Is it possible to (de)-serialize types that one does not own (e.g. from third-party libraries like BuiltList) with this approach? If yes, I could deprecate my packages.

**Comment by kevmoo** [comment]
This will come AFTER null safety lands.

So no work here likely until next year...
