### ISSUE TITLE
Property is not generated

### ISSUE THREAD

**Issue by pueffl** [google/json_serializable.dart#613]
Hi!

As far as I can see, there is no code generated for the following constellation:

```dart
class Preference {
  String _id;
  set id(String value) {
    checkNotEmpty(value, source: "id");

    _id = value;
  }

  get id {
    return _id;
  }
....
```

```dart
@JsonSerializable(nullable: false)
class PreferenceModel extends Preference with EquatableMixin {
  PreferenceModel() : super();

  @override
  get id {
    if (super.id == null || super.id.trim().isEmpty) {
      super.id = Uuid().v4();
    }
    return super.id;
  }
...
```

Don't know if this is because of the name 'id', similar fields seem to work fine.

**Comment by 7Kronos** [comment]
The underscore prefix means the variable is private in your class (dart convention).
Private members are not serialized. Just make your field final to prevent mutating it by accident.

`final String id;

PreferenceModel(this.id);
`

Don't call super() as your class does not heritage from any class.

**Comment by pueffl** [comment]
This is compiling code. PreferenceModel extends from Preference.The call to super is correct.
I know that _id is private, the getter and setter are not. The same stuff seem to work with other fields.

**Comment by kevmoo** [comment]
That's a legit bug!

**Comment by kevmoo** [comment]
Fixed published https://pub.dev/packages/json_serializable/versions/3.4.1
