### ISSUE TITLE
No instruction

### ISSUE THREAD

**Issue by chris-rutkowski** [google/json_serializable.dart#643]
Hello,
I noticed you are missing one essential step in readme - instruction how to trigger generation. It would be helpful to everyone, especially beginners.

I had to learn how to actually generate code by reading this:
https://flutter.dev/docs/development/data-and-backend/json#running-the-code-generation-utility

**Comment by kevmoo** [comment]
Thanks for the feedback!

**Comment by kevmoo** [comment]
PRs welcome to add instructions!

**Comment by celesteking** [comment]
These are end-users. They will never send any PRs. You should've known that by working at google.

**Comment by kevmoo** [comment]
See https://github.com/google/json_serializable.dart/tree/master/example

**Comment by kevmoo** [comment]
Done! https://github.com/google/json_serializable.dart/commit/47a4db659e1c6de9b5636c11adf7bc3d5f837e9d
