### ISSUE TITLE
JsonConverter for custom object

### ISSUE THREAD

**Issue by pblinux** [google/json_serializable.dart#646]
Hi!

I'm working on a package that fetches data and deserialize into a `Response` object. That class have many attributes but one in specific: `data`, is a nested json. The idea is to devs create their own class that represent this `data` object.

JsonConverter should resolve this nested deserialization but this custom class for `data` it's outside the package, can't verify type to call `toJson()` and `fromJson()`. Is there a way to tell JsonConverter to use an outside class for this methods? Maybe inheritance class?

Thanks.

**Comment by kevmoo** [comment]
Could you explain your problem in a bit more detail?

**Comment by pblinux** [comment]
Of course!

Here is my `Data` class (this is the data class from package):

```dart
@JsonSerializable()
class Data<T> {
  final String id;
  final String lang;
  final String type;
  final T data;

  Data({this.data, this.id, this.lang, this.type});

  factory Data.fromJson(Map<String, dynamic> json) => _$DataFromJson<T>(json);

  Map<String, dynamic> toJson() => _$DataToJson(this);
}
```
Now, let's say someone creates the following class (this is someone using the package):

```dart
@JsonSerializable()
class Test {
  final String field1;
  final String field2;
  final String field3;

  Test({this.field1, this.field2, this.field3});

  factory Test.fromJson(Map<String, dynamic> json) => _$TestFromJson<T>(json);

  Map<String, dynamic> toJson() => _$TestToJson(this);
}
```
We expect to call something like:
```dart
Data<Test> testResult = apiCall(...); ///
```
If `Test` were included in the package, we could create a custom `fromJson/toJson` to handle this case, but since it is an object created outside, that's the problem, I don't know what type `data` will be to deserialize/serialize and call their respective method.

Hope I'm not mixing concepts :sweat_smile:

**Comment by kevmoo** [comment]
This is just another case of https://github.com/google/json_serializable.dart/issues/593

It's pretty gnarly to provide a clean solution here!
