### ISSUE TITLE
Polymorphism issue

### ISSUE THREAD

**Issue by fauzynurn** [google/json_serializable.dart#655]
Supposed I have two classes named Person and Birthday. And I also have other two classes named PersonResponse and BirthdayResponse. These two classes are supposed to extend Person and birthday respectively : 

```dart
class Birthday{
  int day;
  int month;
  int year;

  Birthday({this.day,this.month,this.year});
}

class Person{
  String name;
  int age;
  Birthday birthday;

  Person({this.name,this.age,this.birthday});
}

@JsonSerializable()
class PersonResponse extends Person{
  PersonResponse(
      String name,
      int age,
      BirthdayResponse birthday
      ) : super(name: name, age: age, birthday: birthday);

  factory PersonResponse.fromJson(Map<String,dynamic> json) => _$PersonResponseFromJson(json);
}

@JsonSerializable()
class BirthdayResponse extends Birthday{
  BirthdayResponse(
      int day,
      int month,
      int year
      ) : super(day: day,month: month,year: year);

  factory BirthdayResponse.fromJson(Map<String,dynamic> json) => _$BirthdayResponseFromJson(json);
}
```
I tried to generate the serializer using command `flutter packages pub run build_runner build` and these errors came up : 

```
[SEVERE] json_serializable:json_serializable on lib/model/person_response.dart:
Error running JsonSerializableGenerator
Could not generate `toJson` code for `birthday`.
None of the provided `TypeHelper` instances support the defined type.
```

From those errors, it seems like json_serializable is looking for `Birthday` class instead of `BirthdayResponse` class, even I wrote explicitly `BirthdayResponse` on `PersonResponse`'s constructor.

Here's my flutter and dart I'm using : 

`Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (2 weeks ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3`

**Comment by kevmoo** [comment]
Closing this out. No solid way to fix it since we have conflicting property types

`BirthdayResponse` in the constructor, but `Birthday` as a getter on the base class.

What you really want here is the ability to generate JSON helpers for types you don't own.

That'd be a good feature request to file!

**Comment by lucavenir** [comment]
> That'd be a good feature request to file!

Hi @kevmoo, I know this is an old issue, but has such request ever been filed by the community?

**Comment by kevmoo** [comment]
@lucavenir – I don't think so. Please do!
