### ISSUE TITLE
Map<String, double> generated wrong.

### ISSUE THREAD

**Issue by Xezolpl** [google/json_serializable.dart#664]
Hello just a simple bug, I have a simple Map<String, double> parties, and json generator generates me code like this:
```dart
parties: (json['parties'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(k, (e as num)?.toDouble())),
```
but i get a bug in my program 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
```
i simply fixed it my casting k to string with code 
```dart
parties: (json['parties'] as Map<dynamic, dynamic>)?.map(
      (k, e) => MapEntry(k as String, (e as num)?.toDouble())),
```

I dont know it is something wrong in my code or its just generator's fault. Greetings

**Comment by kevmoo** [comment]
See https://github.com/google/json_serializable.dart/issues/351
