### ISSUE TITLE
ToJson Not converting subModel into the json string.

### ISSUE THREAD

**Issue by DhavalRKansara** [google/json_serializable.dart#675]
Suppose I have a model UserDetails

```
@JsonSerializable()
class UserDetailsDm {
  int userId;
  String name;
  ContactInfo contactInfo;

  UserDetailsDm({
    @required this.userId,
    @required this.name,
    @required this.contactInfo,
  });

  Map<String, dynamic> toJson() => _$UserDetailsDmToJson(this);

  factory UserDetailsDm.fromJson(Map<String, dynamic> json) =>
      _$UserDetailsDmFromJson(json);
}

```

Not when I call UserdetailsDm.toJson() it will return me JSON something like this:

```
{
"userId" : 123,
"name": "Dhaval",
"contactInfo": instance of ContanctInfo
}
```

So on behalf of an `instance of ContactInfo` it should return the JSON form of the model ContantInfo too.

As the same functionality working when we convert JSON to UserModle it will automatically map Json of `contantInfo` with subModle`ContantInfo`.

**Comment by pierrediderot** [comment]
> Suppose I have a model UserDetails
> 
> ```
> @JsonSerializable()
> class UserDetailsDm {
>   int userId;
>   String name;
>   ContactInfo contactInfo;
> 
>   UserDetailsDm({
>     @required this.userId,
>     @required this.name,
>     @required this.contactInfo,
>   });
> 
>   Map<String, dynamic> toJson() => _$UserDetailsDmToJson(this);
> 
>   factory UserDetailsDm.fromJson(Map<String, dynamic> json) =>
>       _$UserDetailsDmFromJson(json);
> }
> ```
> 
> Not when I call UserdetailsDm.toJson() it will return me JSON something like this:
> 
> ```
> {
> "userId" : 123,
> "name": "Dhaval",
> "contactInfo": instance of ContanctInfo
> }
> ```
> 
> So on behalf of an `instance of ContactInfo` it should return the JSON form of the model ContantInfo too.
> 
> As the same functionality working when we convert JSON to UserModle it will automatically map Json of `contantInfo` with subModle`ContantInfo`.

Hi,
You tried use @JsonSerializable(explicitToJson: true) ?
DOC: https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
Example: https://stackoverflow.com/a/60647648/2141562

**Comment by kevmoo** [comment]
What @pierrediderot said!

**Comment by devSC** [comment]
me too
