### ISSUE TITLE
Enhancement: Live template for adding toJson and fromJson for IDE

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [google/json_serializable.dart#677]
I made a live template for adding toJson and fromJson.
Maybe it is useful if you add this to the readme.

**Add Part**
```
part '$fileNameWithoutExtension$.g.dart';
```
<img width="1300" alt="Screen Shot 1399-05-07 at 10 59 56 PM" src="https://user-images.githubusercontent.com/5219339/88706675-69127080-d126-11ea-9c9e-ca9c512b9388.png">

**Add fromJson and toJson**

```
factory $class_name$.fromJson(dynamic json) => _$$$class_name$FromJson(json);

Map<String, dynamic> toJson() => _$$$class_name$ToJson(this);
```
<img width="1266" alt="Screen Shot 1399-05-07 at 11 00 08 PM" src="https://user-images.githubusercontent.com/5219339/88706712-74659c00-d126-11ea-975a-ad8e73ab31a9.png">

**Comment by kevmoo** [comment]
I don't think I'd add such a thing to this core package. Happy to link to an add-on if someone creates it, though!
