### ISSUE TITLE
How to use custom JsonConverter with second argument in fromJson?

### ISSUE THREAD

**Issue by BigGitWorld** [google/json_serializable.dart#687]
Hi!
Thank you for this great library.
I know this is the JsonConverter abstract class:
```
abstract class JsonConverter<T, S> {
  T fromJson(S json);
  S toJson(T object);
```
What I want to do is as the below : 
I want to add a second argument (a Function) to the ``fromJson`` method and use it inside of the ``fromJson`` method in extended my own JsonConverter class.
So how can I do this?

Thank you

**Comment by kevmoo** [comment]
We don't have support for that, sadly.

**Comment by BigGitWorld** [comment]
@kevmoo 
Can you support this feature please?
Do you think this is easy to implement? I want to add this feature to the library but unfortunately I do not know what classes need to change.

**Comment by kevmoo** [comment]
Try adding the 2nd argument as either optional-positional or optional named.

**Comment by BigGitWorld** [comment]
Do I have to add the 2nd argument to which classes (only ``JsonConverter`` asbtract class is enough or other classes is needed also)?

**Comment by kevmoo** [comment]
I believe the commits I just landed may help you – without having to use `JsonConverter`

Take a look at https://github.com/google/json_serializable.dart/blob/master/example/lib/tuple_example.dart and let me know!
