### ISSUE TITLE
Const class should be instanciated using const keyword

### ISSUE THREAD

**Issue by Nico04** [google/json_serializable.dart#695]
When using JsonSerializable on an immutable class with a const constructor, the generated `factory MyConstClass.fromJson(...)` doens't use the keyword const for instantiation, therefore two instances of the same json will make to object instances.
It would be nice to have an option to force using the const keyword at instantiation to make real const instances.

**Comment by kevmoo** [comment]
It CANNOT use the const keyword because the inputs are not const.

Try adding `const` to the generated code when you have it open in an IDE w/ analyzer. You should see a lot of red.

**Comment by Nico04** [comment]
You're totally right, my bad.
