### ISSUE TITLE
Should we commit/not-commit generated files to git repository (gitignore)

### ISSUE THREAD

**Issue by danielgomezrico** [google/json_serializable.dart#696]
Hi 

In https://pub.dev/packages/build_runner#source-control they advise you to not upload generated `.g.` files into your repository, but warns that it depends on the generators itself, so should we upload this to the repository for this one?

**Comment by kevmoo** [comment]
If you publish the package, you SHOULD commit the generated files.

Otherwise, it depends on how much you and your team use `build_runner`. If you check in the files, then syncing the repo guarantees you'll be in a good state without running the builder first.

**Comment by danielgomezrico** [comment]
@kevmoo what do you mean by publish the package? do you mean like generating a pub library?

**Comment by kevmoo** [comment]
> @kevmoo what do you mean by publish the package? do you mean like generating a pub library?

publish to `pub.dev`, yes.

**Comment by danielgomezrico** [comment]
Got it, thank you very much for your answer.

**Comment by vkammerer** [comment]
@kevmoo `.g.dart` files should be committed to version control when they are part of the published lib, but this repo also contains them [in the example](https://github.com/google/json_serializable.dart/tree/f1c04e26ce2323fd52d4be13014225e673eda46e/example/lib)

So should they be removed from the example?
This might seem trivial but we are having a long discussion about it in my team and your example directory is referenced as an argument in favour of committing to them to git, when it is indeed in contradiction with the `build_runner` guideline to keep them out.

**Comment by kevmoo** [comment]
Here's my take: if this is an app package – with no other users – and the generated code changes a lot, then I'd not check it in.

If the package is a library package – used by other packages – and/or the generated code is meant to fill in boiler plate – then I'd check in the code.

Look at these examples:

https://github.com/dart-lang/pubspec_parse/tree/master/lib/src
https://github.com/dart-lang/build/tree/master/build_config/lib/src

In both cases we check in the generated code. We publish these to pub. The users of these packages don't have to worry about code generation. The code is just...there.

CC @natebosch and @jakemac53 who may have their own thoughts here...

**Comment by jakemac53** [comment]
Only thing I will add here is if you do check in code you should ensure it is up to date as a verification step in your CI tests. For instance using the build_verify package.
