### ISSUE TITLE
Add types for all generics

### ISSUE THREAD

**Issue by vr19860507** [google/json_serializable.dart#705]
The analyzer shows an error without types. "implicit_dynamic_parameter"

Do you have any plans to fix it?

For example instead of this 
```
 models: (json['models'] as List)
        ?.map((e) =>
```
just use this
```
 models: (json['models'] as List<Object>)
        ?.map((e) =>
```

**Comment by kevmoo** [comment]
See https://github.com/google/json_serializable.dart/issues/705

**Comment by vr19860507** [comment]
> See #705

?

**Comment by kevmoo** [comment]
So sorry! I meant

See https://github.com/google/json_serializable.dart/issues/557
And also https://github.com/dart-lang/language/issues/993

**Comment by vr19860507** [comment]
Thank you, I read it.

But to fix the problem, not add "exclude". You can just close the generic type with an object!
`json['models'] as List<Object>` instead of `json['models'] as List` and that's all!

And in the future when nullable types are added, just replace with `json['models'] as List<Object?>`

**Comment by vr19860507** [comment]
@kevmoo What do you think about it

**Comment by kevmoo** [comment]
I'm not going to do anything extra here until https://github.com/dart-lang/language/issues/993#issuecomment-635618384 is resolved.

It'd just create too much churn.

**Comment by vr19860507** [comment]
I understood.
