### ISSUE TITLE
lib/core/uri.dart:3259:39 - Expected an identifier.

### ISSUE THREAD

**Issue by chenyongze** [google/json_serializable.dart#716]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include the entire output
of either `dart --version` or `flutter --version`, depending on what
you're using.

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

**Comment by kevmoo** [comment]
Please add more details! I can reopen.
