### ISSUE TITLE
support tool generate json to class dart which has @JsonSerializable @JsonKey

### ISSUE THREAD

**Issue by duy1998** [google/json_serializable.dart#717]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include the entire output
of either `dart --version` or `flutter --version`, depending on what
you're using.

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

**Comment by kevmoo** [comment]
Please add more details here. I can reopen this issue if there are more details.
