### ISSUE TITLE
Feature request: repopulating / overwriting an existing object

### ISSUE THREAD

**Issue by rknell** [google/json_serializable.dart#727]
Not sure if this has been raised before but a quick search of the issues turned up nothing.

I often find myself in a situation where I have an object and have a function on that object such as save() which will call a backend and return JSON with the result of the operation. The object being saved doesn't have any awareness of where it lives in the ecosystem, so disposing of itself and recreating itself is challenging.

What I am looking for is the ability to do a "fromJSON" function that overwrites the current instance with values from JSON. I have had a go and it and couldn't work it out, probably due to a lack of experience. Is this something that is on the roadmap or has been discussed before?

**Comment by k-paxian** [comment]
Nice use case, not sure about this library, but `dart-json-mapper` library could help you out with template for deserialization
https://github.com/k-paxian/dart-json-mapper#deserialization-template

**Comment by cedvdb** [comment]
Why does json_serialization went the route of a builder instead of having helpers like dart_json_mapper?  It seems much more elegant and customizable.

**Comment by kevmoo** [comment]
🤷  – we started earlier. Suggestions welcome @cedvdb

**Comment by kevmoo** [comment]
This is out of scope for this package. I get the scenario. It's interesting. Just out of scope.

Forking this package and doing your own thing is always an option.
