### ISSUE TITLE
Allow Same name for two variables 

### ISSUE THREAD

**Issue by pr-1** [google/json_serializable.dart#728]
How to Allow this -

@JsonKey(name: 'uid')
String id;

@JsonKey(name: 'uid')
String uid;

Currently it gives error on code generation that we cannot give same name to. 2 variables. 
If there is any Workaround do let me know because I could not find any. 
id is in BaseModel and uid in Child model .

**Comment by kevmoo** [comment]
This is explicitly forbidden – because it's unclear how to resolve such a confilct!
