### ISSUE TITLE
Const as default value

### ISSUE THREAD

**Issue by aloisdeniel** [google/json_serializable.dart#741]
I'm wondering why default values are limited to literals and not consts ?

```dart
[SEVERE] json_serializable:json_serializable on lib/src/models/settings_data.dart:

Error with `@JsonKey` on `sosOptions`. `defaultValue` is `SosOptions`, it must be a literal.
package:munic_core/src/models/settings_data.dart:1050:20

     ╷      @JsonKey(defaultValue: SosOptions())
1050 │   final SosOptions sosOptions;
     │                    ^^^^^^^^^^
     ╵
```

For more context, I'm using it in combination with the `freezed` package wich define a single `Default` annotation.

**Comment by kevmoo** [comment]
It turns out to be *really* hard to rehydrate arbitrary constant values. Your case would likely be easy, but some `const _RandomClass(_someField, {_otherField: const OtherValue})` gets super complex.

**Comment by aloisdeniel** [comment]
Okay, I could imagine. 

Couldn't you just take the raw content of the annotation as the generate default value, without any analyzer pass ? *I guess that there are edge cases*.

**Comment by kevmoo** [comment]
Tracking here https://github.com/google/json_serializable.dart/issues/849
