### ISSUE TITLE
Add support for dynamic JsonKey names

### ISSUE THREAD

**Issue by mpw-migalv** [google/json_serializable.dart#751]
Make it possible to make the JsonKey names dynamic. Something like this:

```
class ParentObject {
  ParentOject({
    @JsonKey(name: object.key)
    AnObject object,
  });
}
class AnObject {
  String key;
  String value;
}
```

Then when you call the toJson method:

```
parentObject.toJson() => {
  key: value,
}
```

**Comment by k-paxian** [comment]
Since annotation must be a `const`, you cannot have anything dynamic there, unfortunately.

**Comment by kevmoo** [comment]
What @k-paxian said. ☝️

**Comment by migalv** [comment]
I understand that annotations are const, so it's not possible to add this dynamically inside the annotation, but it was just an example.

What I was asking for is the possibility of doing something like this with some workaround or a new feature that enables this somehow.
