### ISSUE TITLE
migrate checked_yaml to null safety

### ISSUE THREAD

**Issue by kevmoo** [google/json_serializable.dart#758]

**Comment by kevmoo** [comment]
This package is used by `build_config`. This package also uses `pkg:yaml` – which has been migrated to null safety.

But we need `build_config` to migrate to support the newest analyzer which supports the newest yaml. So blocked.

**Comment by kevmoo** [comment]
Blocked on https://github.com/dart-lang/build/issues/2906

**Comment by vanlooverenkoen** [comment]
1.5.2 is available with analyzer 0.41

**Comment by kevmoo** [comment]
Still blocked by `build_config` using the right flavor of yaml

**Comment by kevmoo** [comment]
Waiting on https://github.com/dart-lang/build/pull/2908

**Comment by kevmoo** [comment]
Now waiting on https://github.com/dart-lang/build/pull/2927
