### ISSUE TITLE
Publish json_serializable null-safety pre-release

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [google/json_serializable.dart#763]
The `json_annotation` null-safety pre-release cannot be used because `json_serializable` has not been published yet.

That is the latest `json_serializable` release on Pub is `3.5.1`.

@kevmoo Is this an oversight or is there a reason for this?

**Comment by kevmoo** [comment]
There is a BUNCH of coordination we need to do to get this out.

json_annotation <- (used by) checked_yaml <- pubspec_parse <- build_config <- build_runner <- json_serializable

I'm hoping to work with @jakemac53 this week to get it out

**Comment by kevmoo** [comment]
- [ ] checked_yaml
- [ ] pubspec_parse - in progress
- [ ] build_config
- [ ] json_serializable

**Comment by pratikpparikh** [comment]
@kevmoo json_serializable does not the version published?  Is that by design?

**Comment by kevmoo** [comment]
Just waiting on https://github.com/google/json_serializable.dart/pull/770 approval! CC @jakemac53 @natebosch 😄

**Comment by pratikpparikh** [comment]
Thank you, @kevmoo

**Comment by creativecreatorormaybenot** [comment]
@kevmoo Thanks a bunch! ✨ 

Worked great :)
