### ISSUE TITLE
Cannot generate parts of parts.

### ISSUE THREAD

**Issue by normancarcamo** [google/json_serializable.dart#773]
Hello there, I would like to know if there's any possible workaround for including parts of parts in dart.

Let's say, I have the following structure:

config/
....app_config.dart (class AppConfig ...)
part of ('index.dart');
part 'app_config.g.dart'; // <- This file suggest me to move this part to the entry point of the library which in this case is in the file index.dart, but when I run flutter pub run build_runner build it says that it's missing the part 'app_config.g.dart'.

....graphql_config.dart (class GraphQLConfig)
part of 'index.dart';

....index.dart

library config;

// ...imports skipped by brevity...

part 'app_config.dart';
part 'graphql_config';

Any idea of what to do here?
I would like to hide several implementations from import statements in my project and by using the library/parts concepts I achieve these goals, but not in this case.

`dart --version`
`Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"`

`flutter --version`
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (4 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

Is it really an issue? For general questions consider starting with StackOverflow:
I did a little research on this site, but with no luck.

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build
Thanks, I left a message there, I hope I could get a good answer from there or from here.

**Comment by kevmoo** [comment]
I'm not sure I follow. 

You should put most of your source in the `lib/src` directory then export it in `lib/my_lib.dart`
