### ISSUE TITLE
_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by Konoshenko** [google/json_serializable.dart#774]
The strongly typed operator `as` triggers an error in runtime. 
This issue solving by using `Map<String, dynamic>.from(json['collection'])`

Attached collection structure witch I try parse.

```
{
    "members": {
        "X8zb53SMJGb9pAhB9PtTbm7PsTm2": {
            "uid": "X8zb53SMJGb9pAhB9PtTbm7PsTm2",
            "role": "admin"
        },
        "X8zb53SMasdJGb9pAhB9PtTbm7PsTm2": {
            "uid": "X8zb53SMJGb9pAhB9PtTbm7PsTm2",
            "role": "admin"
        }
    },
    "show_other_member": false,
    "category": "VoZMyrGwRkegbroUn25z",
    "title": "Test for demonstration",
    "show_group_member": true
}
```

**Comment by kevmoo** [comment]
Anything coming from Dart's JSON decode logic will give you a `Map<String, dynamic>`

Are you using Flutter, per chance?

**Comment by Konoshenko** [comment]
@kevmoo Yes i`am use it in flutter project for decode firestore model.

**Comment by kevmoo** [comment]
See https://github.com/flutter/flutter/issues/16589
