### ISSUE TITLE
Option to generate encoder/decoder for enum?

### ISSUE THREAD

**Issue by PiN73** [google/json_serializable.dart#778]
Currently one can't decode/encode enum values directly from/to string.

For example, I have
```dart
enum State {
  @JsonValue('in_review')
  inReview,

  ...
}
```

and want to do this
```dart
String s = 'in_review';
State state = stateFromString(s);
```

I need either implement `stateFromString` manually (which will duplicate strings in @JsonValue) or make a wrapper class.

It would be great to have an option to generate from/to string converters by some annotation, e.g.
```dart
@JsonSerializable()
enum State {
  ...
```

**Comment by PiN73** [comment]
Maybe the generator can also reuse this generated function (like `stateFromString` and `stateFromString`) in `fromJson`/`toJson` for classes, e.g. if there is
```dart
class Article {
  State state;
  ...
}
```
inside another file

**Comment by PiN73** [comment]
Also it would be great to have one place for setting `unknownEnumValue`, e.g.
```dart
@JsonEnumSerializable(unknownEnumValue: State.unknown)
enum State {
  ...
```
which will be used as default in `stateFromString`/`stateFromString` functions with possibility to override it

**Comment by LichKing-2234** [comment]
You can follow this.
https://github.com/google/json_serializable.dart/issues/653#issuecomment-903583793

**Comment by kevmoo** [comment]
I have an idea for this, but we'll need to wait for Dart 2.14

**Comment by kevmoo** [comment]
WIP: https://github.com/google/json_serializable.dart/pull/989

**Comment by HJ29** [comment]
Is it possible to convert enum to json value?
eg,
``` dart
enum StatusCode {
  @JsonValue(200)
  success,
  @JsonValue('500')
  weird,
}
```
Sometime, I want to display the `200` value, but I cant find a way to decode `StatusCode.success` to json value `200`.
json_serializable use `_$EnumNameEnumMap` and `_$enumDecode` to decode, but these aren't exposed to public,
so I cant use same way to decode.
