### ISSUE TITLE
Reduce boilerplate fromJson requirements

### ISSUE THREAD

**Issue by MatrixDev** [google/json_serializable.dart#782]
For some reason library requires child classes to implement fromJson factory during deserialisation. It is very strange that developers need to write this boilerplate code when it can be easily omitted by using generated methods during deserialisation.

### Actual behaviour
1. Generated code requires child class to implement fromJson

### Expected behaviour

1. Library must not require any boilerplate from developer besides annotating classes/fields and adding `part` line.
2. In the case below it must use already generated `_$ChildFromJson` method.

## Input code
```dart
@JsonSerializable()
class Parent {
  Child child;
}

@JsonSerializable()
class Child {
  String value;
}
```

## Generated code
```dart
Parent _$ParentFromJson(Map<String, dynamic> json) {
  return Parent()
    ..child = json['child'] == null
        ? null
        : Child.fromJson(json['child'] as Map<String, dynamic>);      // <----- just use _$ChildFromJson here
}

Map<String, dynamic> _$ParentToJson(Parent instance) => <String, dynamic>{
      'child': instance.child,
    };

Child _$ChildFromJson(Map<String, dynamic> json) {
  return Child()..value = json['value'] as String;
}

Map<String, dynamic> _$ChildToJson(Child instance) => <String, dynamic>{
      'value': instance.value,
    };
```

## Setup
- build_runner: ^1.0.0
- json_annotation 3.1.1
- json_serializable 3.5.1

**Comment by tnc1997** [comment]
@MatrixDev I think that this would only work if all of the serializable classes are in the same file. I can only speak for myself here, but I tend to have one class per file, and the generated methods are private. The fact that the generated methods are private means that they are only usable from the `part of` file. Moving the two classes into two files should reproduce this.

###### parent.dart
```dart
@JsonSerializable()
class Parent {
  Child child;
}
```

###### child.dart
```dart
@JsonSerializable()
class Child {
  String value;
}
```

**Comment by kevmoo** [comment]
I already discussed this in another issue, but I can't find it.

We try to minimize the "magic" here, including knowledge of other classes using `json_serializable`. So we just depend on public implementation – for instance, having a `fromJson` factory – so the use of this library remains an implementation detail.

**Comment by MatrixDev** [comment]
It becomes quite cumbersome to write those methods for each class when you have 100+ of them. Even more - you can't just copy fromJson method from class to class, as its implementation differs fo each class.

**Comment by tnc1997** [comment]
@MatrixDev I'm not sure if this might help but I was able to somewhat automate that process using regular expressions and the find and replace functionality in IntelliJ. Obviously your mileage may vary but it's something that I found useful.

```
(?s)\@JsonSerializable\(\)
class ([a-zA-Z0-9]+) \{
  (.+?)
\}
```

```
@JsonSerializable()
class $1 {
  $2

  factory $1.fromJson(Map<String, dynamic> json) => _\$$1FromJson(json);

  Map<String, dynamic> toJson() => _\$$1ToJson(this);
}
```

```diff
@JsonSerializable()
class Parent {
  Child? child;

  Parent({this.child});
+
+  factory Parent.fromJson(Map<String, dynamic> json) => _$ParentFromJson(json);
+
+  Map<String, dynamic> toJson() => _$ParentToJson(this);
}

@JsonSerializable()
class Child {
  String? value;

  Child({this.value});
+
+  factory Child.fromJson(Map<String, dynamic> json) => _$ChildFromJson(json);
+
+  Map<String, dynamic> toJson() => _$ChildToJson(this);
}
```
