### ISSUE TITLE
No mapper is generated for stanadlone enum files that aren't part of any class

### ISSUE THREAD

**Issue by agilob** [google/json_serializable.dart#784]
No mapper is generated for an enum when the enum isn't used in any class and has its own file, but has fields annotated with `@JsonValue`. Since `@JsonSerializable` is allowed only on classes, not enums, there's no way to deserialize such enums.

Enum also has `part x.g.dart`, but it's never generated.

**Comment by kevmoo** [comment]
Duplicate of https://github.com/google/json_serializable.dart/issues/778
