### ISSUE TITLE
Generic argument factories and null field

### ISSUE THREAD

**Issue by botty87** [google/json_serializable.dart#785]
```dart
@JsonSerializable(genericArgumentFactories: true, createToJson: false)
class PostResponse<T> {
  String error;

  @JsonKey(nullable: true)
  T value;

  PostResponse({this.error, this.value});

  factory PostResponse.fromJson(Map<String, dynamic> json,T Function(Object json) fromJsonT) => _$PostResponseFromJson<T>(json,fromJsonT);
}

PostResponse<T> _$PostResponseFromJson<T>(
  Map<String, dynamic> json,
  T Function(Object json) fromJsonT,
) {
  return PostResponse<T>(
    error: json['error'] as String,
    value: fromJsonT(json['value']),
  );
}
```

If my json does not have any field "value", or if this field is null, we get a null exception when call the function fromJsonT. There is no check if json['value'] has a not null value, even if we use @JsonKey(nullable: true).

**Comment by wwwdata** [comment]
I am also experiencing this issue. When the `T` value field is annotated with `nullable: true` I would have expected that there is a null check before calling `fromJsonT`

**Comment by kevmoo** [comment]
which version of things are ya'll using now?

**Comment by wwwdata** [comment]
I am using the latest non-preview version `3.5.1`

**Comment by kevmoo** [comment]
You need to handle `null` in your `fromJsonT` function, then. The content of `value` is `fromJsonT(json['value'])` passed in with no checks.

If you expect null here, you need to handle it here.

Otherwise, it seems you're asking for support similar to what we have in `DateTime` where we do 

```dart
json['value'] == null ? null : DateTime.parse(json['value'] as String)
```

Right?

**Comment by wwwdata** [comment]
Yes seems right. In my case the `fromJsonT` function is from another json serializable class. So when that is called with `null` it crashes.

**Comment by v7lin** [comment]
I have same issue
