### ISSUE TITLE
Data objects with arrays don't parse correctly.

### ISSUE THREAD

**Issue by Copy33** [google/json_serializable.dart#788]
I am on this version of Flutter and Dart:
```
Flutter 1.26.0-2.0.pre.296 • channel master • https://github.com/flutter/flutter.git
Framework • revision 737496e8db (9 hours ago) • 2021-01-12 02:54:03 -0500
Engine • revision 10cee6abcb
Tools • Dart 2.12.0 (build 2.12.0-214.0.dev)
```
This is my issue:
I have these 2 simple objects, first is called ``MyObject`` which has a ``MyArray`` which is a list of ``Item``s.
```
@JsonSerializable()
class MyObject {
  String id;
  String property1;
  String property2;
  MyArray items;

  MyObject({this.id, this.property1, this.property2, this.items});

  factory MyObject.fromJson(Map<String, dynamic> json) => _$MyObjectFromJson(json);

  Map<String, dynamic> toJson() => _$MyObjectToJson(this);
}
```
```
@JsonSerializable()
class MyArray {
  List<Item> items;

  MyArray({this.items});

  factory MyArray.fromJson(List<Map<String, dynamic>> json) => _$MyArrayFromJson(json);

  Map<String, dynamic> toJson() => _$MyArrayToJson(json);
}
```
The plugin currently generates for my_array.g.dart:
```
MyArray _$MyArrayFromJson(Map<String, dynamic> json) {
      return MyArray(
        items: (json['items'] as List)
            ?.map((e) =>
                e == null ? null : Item.fromJson(e as Map<String, dynamic>))
            ?.toList(),
      );
    }

    Map<String, dynamic> _$MyArrayToJson(MyArray instance) =>
        <String, dynamic>{
          'items': instance.items,
        };
```
which is wrong because the type of json of the first function should be ``List<Map<String, dynamic>`` and not ``Map<String, dynamic>``.
Also, in the ``_$MyArrayFromJson`` method, no need to parse the json parameter as List anymore and also no need to parse the json for every item since we did it the step before (where it's coming from) so just do it this way:
```
MyArray _$MyArrayFromJson(List<Map<String, dynamic>> json) {
  return MyArray(
    items: json
        ?.map((e) =>
            e == null ? null : Item.fromJson(e))
        ?.toList(),
  );
}
```

**Comment by kevmoo** [comment]
investigating now

**Comment by kevmoo** [comment]
Please include the code for `Item` to make sure I understand...but.

I think this is by design. `json_serializable` assumes every `fromJson` is from a `Map`, not a `List`.

You're welcome to implement your own `fromJson` and `toJson` on a class that takes a List (or whatever) though.

Note: the `List` instance from from the JSON decoder in Dart is ALWAYS `List<Object?>`. It map always have `Map` instances within it, but the concrete type of the child is always just `Object?`.
