### ISSUE TITLE
Publish checked_yaml nullsafe 1.9.0

### ISSUE THREAD

**Issue by Nolence** [google/json_serializable.dart#793]
Hi!

I'm just wondering if there's a reason the null safe checked_yaml hasn't been published to pub. Looking at the code, it looks like there's a `1.9.0-nullsafety-dev` version that was merged a month ago or so. If it's still being tested that's fine, was just curious if publishing it was just overlooked by mistake.

Thanks!

**Comment by kevmoo** [comment]
On it!

**Comment by kevmoo** [comment]
I need to update `build_config` to support the latest version here. Thanks for your patience.
