### ISSUE TITLE
Set JsonConverter abstract class to constant class

### ISSUE THREAD

**Issue by alfinbi** [google/json_serializable.dart#807]
Constant constructor can't call non-constant super constructor of 'JsonConverter<DateTime, Timestamp>'.
Try calling a const constructor in the superclass, or removing the keyword 'const' from the constructor.

**Comment by kevmoo** [comment]
Have you tried `implements JsonConverter` instead of `extends`?

**Comment by Ascenio** [comment]
What @kevmoo said does work, take a look at [this](https://pastebin.com/V4mpNm5R) example. However, I see no harm in making JsonConverter have a const constructor.

**Comment by kevmoo** [comment]
nope. I'll land that next. Just need to do a follow-up with updating the version, etc
