### ISSUE TITLE
Doesn't convert nested objects in 4.0.0-nullsafety.0

### ISSUE THREAD

**Issue by haashem** [google/json_serializable.dart#808]
Using latest null safe version:
```
json_annotation: ^4.0.0-nullsafety.0
json_serializable: ^4.0.0-nullsafety.0
```
 try this demo:

```dart
import 'package:json_annotation/json_annotation.dart';

part 'location.g.dart';

@JsonSerializable()
class Location {
  final double latitude;
  final double longitude;
  Location({required this.latitude, required this.longitude});
  factory Location.fromJson(Map<String, dynamic> json) =>
      _$LocationFromJson(json);
  Map<String, dynamic> toJson() => _$LocationToJson(this);
}

```

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

import 'coordinate_dto.dart';

part 'person.g.dart';

@JsonSerializable()
class Person {
  final String name;
  final Location location;
  Person({required this.name, required this.location});
  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);
  Map<String, dynamic> toJson() => _$PersonToJson(this);
}

```

then check the generated `person.g.dart` file:
```
Map<String, dynamic> _$PersonToJson(Person instance) => <String, dynamic>{
      'name': instance.name,
      'location': instance.location,
    };
```
as you see location is not converted to json. but in older version it works well.

flutter --version:
<details><summary>Click To Expand</summary>
```
Flutter 1.26.0-17.6.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision a29104a69b (5 days ago) • 2021-02-16 09:26:56 -0800
Engine • revision 21fa8bb99e
Tools • Dart 2.12.0 (build 2.12.0-259.12.beta)
```

**Comment by kevmoo** [comment]
location has a `toJson` function on it which is called by `jsonEncode` or similar. This has been how it always works.

**Comment by haashem** [comment]
I didn't get your point, when I call `person.toJson()` in debug console, I see location is not converted to json.
<img width="772" alt="Screen Shot 2021-02-22 at 10 47 43" src="https://user-images.githubusercontent.com/3206748/108672418-75637e00-74fb-11eb-92c3-8e2da363d733.png">


But when I generate with older version of `json_serializer: ^3.5.0`
toJson for location is called:
```
Map<String, dynamic> _$PersonToJson(Person instance) => <String, dynamic>{
      'name': instance.name,
      'location': instance.location?.toJson(),
    };
```

if its not a bug, what I'm doing wrong?

**Comment by kevmoo** [comment]
Yes. So this is setup to assume the JSON utils in `dart:convert`.

If you want explicit `toJson` called, use https://pub.dev/documentation/json_annotation/3.1.0/json_annotation/JsonSerializable/explicitToJson.html

**Comment by haashem** [comment]
Thanks I got the point.
Please provide a clear practical example in documentation.
