### ISSUE TITLE
Change disallowNullValue to allowNullValue

### ISSUE THREAD

**Issue by agilob** [google/json_serializable.dart#824]
`disallowNullValue` makes users of the API need to think about negative/positive effect of the settings in form of disallow = false then allow, rather than simpler allowNullValue, which doesn't bring consequences of double-negative thinking about the setting. i personally find "enable" much easier to read in code eg in if-conditions `if(enable)` rather than `if(disable == false)`. If the API of `@JsonKey` isn't final yet, please consider changing the option to "allowNullValue", if you consider it final, feel free to close this issue.

**Comment by agilob** [comment]
It would also keep the positive vs negative logic consistent with other parameters "nullable" vs "nonNullable", "includeIfNull" vs "excludeIfNull", "required" vs "nonRequired"

**Comment by agilob** [comment]
@kevmoo will you accept a PR if I implemented this?

**Comment by kevmoo** [comment]
Likely not going to do anything here – at least for a while. We'd have to do a breaking change to `json_annotation`.

I'll mark it as "future".

**Comment by agilob** [comment]
Yea, that's why I raised it in 4.0.1, early releases for dart 2.12

**Comment by kevmoo** [comment]
Thinking about it, I'm going to close this out.

I'm a fan of having bool values default to `false`.

By default, `disallowNullValue` *is* false. We allow null values.

If I was starting over, I might consider changing this. Call this a historical accident.

I totally get your point, though!
