### ISSUE TITLE
@JsonKey and @JsonValue combined with defaultValue doesn't seem to work

### ISSUE THREAD

**Issue by arnoutvandervorst** [google/json_serializable.dart#825]
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"

My class contains:
@JsonKey(name: 'activityLevel', defaultValue: ActivityLevel.unknown)

The enum is:
enum ActivityLevel {
  @JsonValue('LEVEL1')
  level1,
  @JsonValue('LEVEL2')
  level2,
  @JsonValue('LEVEL3')
  level3,
  @JsonValue('LEVEL4')
  level4,
  @JsonValue('LEVEL5')
  level5,
  @JsonValue('UNKNOWN')
  unknown,
}

This results in:
SEVERE] json_serializable:json_serializable on lib/model/user.dart:

line 1, column 14755 of package:newme_app/model/enum.dart: Could not resolve annotation for ActivityLevel level1
  ╷
1 │ @JsonValue('LEVEL1')
  │ ^^^^^^^^^^^^^^^^^^^^
  ╵

When I comment all the @JsonValue lines, it works but ofc it won't translate correctly on runtime. Also, when I leave the @JsonKey values but I remove the defaultValue, it also works. I'd like to really include the defaultValue, but then the code won't build....so why do I need a different value on the enum key from the value? Backwards compatibility with old data...yup I know...

When I manually edit the .g.dart to add the 'LEVEL1' etc, it works correctly...

**Comment by arnoutvandervorst** [comment]
Update: seems my enum.dart is a bit long...when I move this particular enum to another file, it works! So basically every enum defined after line 500 or something rather is triggering this error? Should I move enums to their classes or keep them in a separate file?

**Comment by kevmoo** [comment]
This almost sounds like a bug in `pkg:analyzer`. Hrm...

**Comment by PiN73** [comment]
Same in a big project for me, but when I try to reproduce it in a minimal project, the error magically appears and disappears, can't figure out when and why

**Comment by kevmoo** [comment]
I'm seeing issues with annotated enums in other places.

**Comment by PiN73** [comment]
After removing gitignored files, pub get and build, got another error:
```
...
[INFO] 27.8s elapsed, 257/272 actions completed.
[WARNING] json_serializable:json_serializable on lib/my_json_serializable_class.dart:
An unexpected error was thrown trying to get location information on `MyEnum firstMyEnumValue` (ConstFieldElementImpl_EnumValue). 

Please file an issue at https://github.com/dart-lang/source_gen/issues/new
Include the contents of this warning and the stack trace along with
the version of `package:source_gen`, `package:analyzer` from `pubspec.lock`.

InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

[SEVERE] json_serializable:json_serializable on lib/my_json_serializable_class.dart:

Could not resolve annotation for `MyEnum firstMyEnumValue`.
[INFO] 29.6s elapsed, 646/653 actions completed.
...
```

**Comment by PiN73** [comment]
Well, I had
```
dependency_overrides:
  source_gen: ^1.0.0
```
which seems to be the case.

**Comment by PiN73** [comment]
@arnoutvandervorst do you have any dependency_overrides?

**Comment by arnoutvandervorst** [comment]
Nope, in my case it was just the size of the file containing the enums. When I moved the enum that caused the error to the top of the file, another enum triggered the error. The error shows a very high column number, which makes me believe that the dart file is compiled to single line, and then the parsing of that single line fails somewhere...

**Comment by marcosmko** [comment]
Hello, I also have this problem.
Code generation seems unstable, sometimes it works, other doesn't.

**Comment by kevmoo** [comment]
Here's the root issue: https://github.com/dart-lang/sdk/issues/45127

**Comment by marcosmko** [comment]
fixed! https://github.com/dart-lang/sdk/issues/45127#issuecomment-805531881!
analyzer 1.2.0 -> 1.3.0

**Comment by kevmoo** [comment]
Which version of `pkg:analyzer` is in your pubspec.lock file, @SashaFarkas ?

**Comment by Patrick386** [comment]
Has this problem been resolved? I also have the same problem. Is it full support for enums?

```
@JsonSerializable()
enum PageType {
  @JsonValue(0)
  All,
  @JsonValue(1)
  Body,
  @JsonValue(2)
  Header,
  @JsonValue(3)
  Bottom
}
```

Model 
```
    @JsonKey(unknownEnumValue: SmartPageType.All)
 //@JsonKey(name: 'PageType', defaultValue: PageType.All)
       PageType pageType,
```
```

[SEVERE] freezed:freezed on lib/pages/sdpage/page_model/page_model.dart:

The parameter `pageType` of `PageModel` is non-nullable but is neither required nor marked with @Default
package:console/pages/dspage/page_model/page_model.dart:60:23
   ╷
60 │            PageType pageType, // 0:All, 1:Body, 2:Header, 3:Bottom
   │                ^^^^^^^^
   ╵
[SEVERE] json_serializable:json_serializable on lib/pages/sdpage/page_model/page_model.dart:

The class `PageType` has no default constructor.
package:console/pages/sdpage/page_model/page_model.dart:18:6
   ╷
18 │ enum PageType {
   │             ^^^^^^^^^^
   ╵
[INFO] Running build completed, took 16.0s
```

**Comment by KouAkitaki** [comment]
@Patrick386  I had a similar problem where I had an enum like

```dart
@JsonSerializable()
enum MyEnum {
  @JsonValue("Foo")
  Foo,
  @JsonValue("Bar")
  Bar
}
```
, which triggered the following error when I ran `pub run build_runner build`:
```
The class `MyEnum` has no default constructor.
asset:dartplayground/bin/lib.dart:18:6
   ╷
18 │ enum MyEnum {
   │      ^^^^^^
   ╵
```

By removing the `@JsonSerializable()`, it worked like a charm.

**Comment by seunghwanly** [comment]
@KouAkitaki Hi, I'm facing a similar issue while parsing `enum`.

I made enum like this below.
``` dart
enum TaskType {
  @JsonValue(0)
  checkerTask,
  @JsonValue(1)
  imageTask,
}
```
and used `enum` in another class called `Task`.

``` dart
@JsonSerializable(explicitToJson: true)
class Task {
  late int _uid;
  late String _title;
  late TaskType _taskType;
  late bool _isCompleted;
  late String? _imageURL;
...
```

I have got a problem with parsing some example data made up with `JSON`.

``` json
{
 "uid": 1234,
 "title": "Empty Trash Can",
 "taskType": 0,
 "isCompleted": false,
 "imageURL": null
}
``` 
and this is the part of `task.g.dart`. I think auto-generated functions have no errors.

``` dart
const _$TaskTypeEnumMap = {
  TaskType.checkerTask: 0,
  TaskType.imageTask: 1,
};
```

Thanks for reading :)
