### ISSUE TITLE
[4.1.0] Wrong DateTime generation

### ISSUE THREAD

**Issue by bdremynoel** [google/json_serializable.dart#845]
With version 4.1.0, I experience issues on generated code.
I have converters across multiple entities in my app, and most of generated code is unchanged since 4.0.2.

Here's the trimmed issue I experience:

```dart
@JsonSerializable()
class Comment {
  @JsonKey(name: 'created_at')
  @DateTimeConverter()
  final DateTime createdAt;

  Comment({
    DateTime? createdAt,
  }) : this.createdAt = createdAt ?? DateTime.now();

  factory Comment.fromJson(Map<String, dynamic> json) => _$CommentFromJson(json);

  Map<String, dynamic> toJson() => _$CommentToJson(this);
}

class DateTimeConverter implements JsonConverter<DateTime, String> {
  // ...
}
```

generates wrong _$CommentFromJson. Converter is ignored.
Also, it could output null.
But _$CommentToJson is OK.
```dart
Comment _$CommentFromJson(Map<String, dynamic> json) {
  return Comment(
    createdAt: json['created_at'] == null
        ? null
        : DateTime.parse(json['created_at'] as String),
  );
}

Map<String, dynamic> _$CommentToJson(Comment instance) => <String, dynamic>{
      'created_at': const DateTimeConverter().toJson(instance.createdAt),
    };
```

Same example with nullable value is OK, both ways call dedicated converter:
```dart
final DateTime? createdAt;
// ...
class DateTimeConverter implements JsonConverter<DateTime?, String?> {
  // ...
}
```

Running build script in verbose mode does not provide any relevant info...

```yaml
dependencies:
  json_annotation: 4.0.1
dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: 1.12.2
```

```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (3 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**Comment by kevmoo** [comment]
This is a bit gnarly, but it's by design.

We have to "pick" which type to use for `createdAt`.

The constructor parameter is `DarteTime?`. The field type is `DateTime`.

So we pick the constructor parameter, which means the converter you supplied initially won't work `JsonConverter<DateTime, String>` because `DateTime` != `DateTime?`.

so the right solution is to use `JsonConverter<DateTime?, String?>`

Are you blocked on this, or just found it weird?

**Comment by bdremynoel** [comment]
I'll make a named constructor to get around this. Thanks for the clarification.

I suggest to clearly mention how generation works to avoid further issues especially since NNBD version.

Better, if possible, throw exceptions when there's weird declaration.
Another example, this is easy to silently generate wrong code by adding `?` to a class member associated to non nullable converter.
