### ISSUE TITLE
Override list serialisation

### ISSUE THREAD

**Issue by mirunamd** [google/json_serializable.dart#852]
I have a list within an object which I am serialising: 

```dart
@JsonSerializable(explicitToJson: true)
class ExamAnswers {
  final List<String> answers;
  final String subject;
  final String examName;

  ExamAnswers(this.answers, this.subject, this.examName);

  Map<String, dynamic> toJson() => _$ExamAnswersToJson(this);
}
```

The way `answers` is serialised is that its contents are separated by commas. I am having issues with this as it is possible that I have strings which already contain commas so the data is mixed up in the Firestore DB. 

For instance, `answers=['option1, something else', 'option2']`. This will be written to the DB as `answers: option1, something else, option 2` and I have no way of knowing which is item 1 and which is item 2 from the original array when I retrieve this data.

I would like to have my own separator that is different from comma. Is this possible?

**Comment by k-paxian** [comment]
Easy and painless way to mitigate is to encode/decode each answer String using `base64` for [instance](https://api.dart.dev/stable/2.12.1/dart-convert/Base64Codec-class.html)
