### ISSUE TITLE
Custom `fromJson` with non-existent key

### ISSUE THREAD

**Issue by 3ph** [google/json_serializable.dart#857]
Is is possible to use custom `fromJson` when key is not present in JSON?

Generated code:
`customField: CustomClass._customFromJson(json['non-existent-key'] as Map<String, dynamic>)`

The cast will fail when `non-existent-key` is not present in the JSON. I've tried other modifiers as `includeIfNull` (this doesn't seem to have any effect on the generated code), `default` (will issue warning and doesn't affect the cast) to no avail.

Using:
`json_annotation: ^4.0.1`
`json_serializable: ^4.1.0`

```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (11 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**Comment by kevmoo** [comment]
`customField` must be `nullable` then. Change the type to `Map<String, dynamic>?`

**Comment by 3ph** [comment]
You mean change it to `Map<String, dynamic>` in generated code? Making the field optional makes no difference to generated code.
