### ISSUE TITLE
Supporting nullable fields that use a converter

### ISSUE THREAD

**Issue by edwardaux** [google/json_serializable.dart#872]
I've successfully been using a custom converter to serialise a bunch of non-nullable fields but today I went to change one of them to be nullable, and I now get an error that says:

> Could not generate `fromJson` code for `backgroundColor`.

A reproducible testcase looks like:
```
@JsonSerializable()
class DummyClass {
  @ColorSerialiser() final Color foregroundColor;
  @ColorSerialiser() final Color? backgroundColor;

  DummyClass({required this.foregroundColor, required this.backgroundColor});
}
```
If I change `backgroundColor` to be non-nullable, everything works fine.

FWIW, my serialiser looks like:
```
class ColorSerialiser implements JsonConverter<Color, String> {
  const ColorSerialiser();

  @override
  Color fromJson(String string) => ColorExtensions.colorFromHex(string);

  @override
  String toJson(Color color) => color.toHex();
}
```

Flutter version:
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (4 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**Comment by kevmoo** [comment]
If you want to support nullable values, you need a nullable-supporting converter.

```dart
class ColorSerialiser implements JsonConverter<Color?, String> {
  const ColorSerialiser();

  @override
  Color? fromJson(String string) => string == null ? null : ColorExtensions.colorFromHex(string);

  @override
  String toJson(Color color) => color.toHex();
}
```

**Comment by edwardaux** [comment]
Ah, gotcha. I must admit tried this earlier, but what your reply has made me realise is that the type-system is going to force me to have two converters - one for nullable and one for non-nullable.

Thanks for the nudge in the right direction (and more broadly for your support to the community).

**Comment by UsamaKarim** [comment]
What is the code for `ColorExtensions.colorFromHex(string)` ?

Thanks

**Comment by NeatFastro** [comment]
@UsamaKarim Idk about his code but here's how mine looks:
```dart
  /// Converts the [Color] to a hex-string (e.g. #AARRGGBB)
  String toHex(Color color) {
    return '#${color.value.toRadixString(16).padLeft(8, '0').toUpperCase()}';
  }

  /// Converts a hexadecimal string (#AARRGGBB) into a [Color]
  Color fromHex(String hex) {
    hex = hex.toUpperCase().replaceAll('#', '');
    if (hex.length == 6) hex = 'FF$hex';
    return Color(int.parse(hex, radix: 16));
  }
```
With that said I really wish this package would support `Color` serialization out of the box.
