### ISSUE TITLE
Lists and generics

### ISSUE THREAD

**Issue by elizabethlfransen** [google/json_serializable.dart#882]
```
Dart version: 2.12.1
json_serializable_version: ^4.0.0
```
There is an issue when generating a deserializer for a list inside a generic.
For example Say i have a serializable model `Foo<T>` and I'm generating a serializer for `Bar<T>` which contains a property `baz` of type `List<Foo<T>>`

The generated code is
```dart
ApiCollection<T> _$BarFromJson<T>(
    Map<String, dynamic> json,
    T Function(Object? json) fromJsonT,
    ) {
  return Bar<T>(
    baz: (json['baz'] as List<dynamic>)
        .map((e) => Foo.fromJson(e as Map<String, dynamic>))
        .toList(),
  );
}
```
The error here is that the method call `Foo.fromJson(e as Map<String, dynamic>)` should be `Foo.fromJson(e as Map<String, dynamic>, fromJsonT)`

**Comment by elizabethlfransen** [comment]
I'm going to be working on a PR for this

**Comment by keremcankabadayi** [comment]
Is it same issue @elizabethlfransen ? https://github.com/google/json_serializable.dart/issues/890

**Comment by kevmoo** [comment]
@elizabethlfransen – what's the annotation you have on the `ApiCollection` class?

Are you using https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/genericArgumentFactories.html ?

**Comment by kevmoo** [comment]
Er, on `Foo` or `Bar`?
