### ISSUE TITLE
Requirement of null-safety makes package unusable

### ISSUE THREAD

**Issue by komape** [google/json_serializable.dart#889]
I just wanted to update the `*.g.dart` files because of some model changes when I suddenly got into the issue that it is required to be null-safety. I don't see the necessity to make my project null-safety. I also don't see the necessity for `json_serializable` to be null-safety. Why is it null-safety?

I really like this package but currently I have to look out for another one. Using some old version where bugs don't get fixed is not an option for me.

Please make it possible to use your package without being null-safety.

`json_serializable` version: 4.1.0
Flutter version: 2.0.2
Dart version: 2.12.1

**Comment by ollydixon** [comment]
Also seeing tons of issues. Wasted days on it.

**Comment by kevmoo** [comment]
Sorry, folks. We have to pick one side of null safety to be on – and we picked to be null safe.

The experience is BETTER (in general) with null-safety, but we know the migration can be tricky for folks.

Remember: this is open source software maintained mostly by me in my spare time. You're welcome to fork it and do as you like!

**Comment by ollydixon** [comment]
@kevmoo of course; we also picked null safety; but now the library cannot parse a double. If any json comes down as the number 1 for example; it tries to parse int even though the model says double.

For example,

```
final Map<String, double> muscleGroups; << Not way to generate this code now. The library fails. Tries to parse int on 1

final Map<String, num> muscleGroups; << Invalid code.
```

**Comment by kevmoo** [comment]
@ollydixon – I've been VERY heads down on I/O things the last few weeks.

Did you file a bug for THIS specific issue?

**Comment by ollydixon** [comment]
@kevmoo I have not no. I will do it a few times. :-) (need to hack a solution for this for now)

**Comment by kevmoo** [comment]
> @kevmoo I have not no. I will do it later/tomorrow. :-) (need to hack a solution for this for now)

I may be able to FIX it for you now, if you give me a repro 😄

**Comment by ollydixon** [comment]
Here is an example of code that breaks when parsing json.

```
@JsonSerializable()
@immutable
class ExerciseV1 {
  final Map<String, double> muscleGroups;
}
```

Too fix we do this; but it's broken for other purposes.
```
@JsonSerializable()
@immutable
class ExerciseV1 {
  final Map<String, number> muscleGroups;
}
```

The json that breaks is simple:

```
{
    'abs': 1, << fails
    'hamstrings': 0.5, << pass
}
```

Sorry I'm fairly drunk at the moment

**Comment by kevmoo** [comment]
> Sorry I'm fairly drunk at the moment

🤣

**Comment by kevmoo** [comment]
Cheers to you @ollydixon – https://github.com/google/json_serializable.dart/pull/894

Good bug!

**Comment by ollydixon** [comment]
@kevmoo thanks for being so responsive hehe :-). Yes indeed; cheers to you too! 🍻

**Comment by kevmoo** [comment]
> @kevmoo thanks for being so responsive hehe :-). Yes indeed; cheers to you too! 🍻

Now we just need to annoy @jakemac53 and/or @natebosch to approve! 😁

**Comment by ollydixon** [comment]
@jakemac53 @natebosch package breaking bug here! 🕺😍

**Comment by kevmoo** [comment]
@ollydixon – landed and published!

**Comment by ollydixon** [comment]
@kevmoo thanks! :-D

**Comment by komape** [comment]
@kevmoo I still don't understand why it is required for MY project to be null-safety just because THIS package is null-safety. Can't this package be null-safety without requiring projects that depend on this package to be null-safety?

**Comment by JoseGeorges8** [comment]
Isn't possible to add a flag to the specific class or on a 'build.yaml' folder to decline null-safety?

**Comment by kevmoo** [comment]
@JoseGeorges8 – sadly, not. It's a DEEP implementation. It's not a simple thing to turn on/off

**Comment by joaopmarquesini** [comment]
@komape @JoseGeorges8 I'm not sure if this solve your issues ( or if you still have this issue) but for anyone looking for a workaround:
You can add `//@dart=2.12` to the beginning of the files that needs to be generated and change only them to be null safe instead of the entire project.
