### ISSUE TITLE
static fromJson methods not working in another entity class 

### ISSUE THREAD

**Issue by berkanaslan** [google/json_serializable.dart#892]
Hello. Actually is this a pattern mistake i don't know but guessing it's an issue. I use my "fromJson" method as static due to a specific need. This static "fromJson" not working another Entity class' variable. Let me give an example like this:

```
@JsonSerializable()
class Foo {
...

static fromJson() => _$FooFromJson();
...
}

```

```
@JsonSerializable()
class Bar {
List<Foo> foos;

static fromJson() => _$BarFromJson();
...
}
```

When i fetch "Bar" from network api i get an exception:
`type 'List<dynamic>' is not a subtype of type 'List<Foo>'`

But when i define like "factory Foo.fromJson ..." everything is ok. 

It is really important to access this method (fromJson) through the class.

```
Flutter 2.0.6
json_annotation: ^4.0.0
json_serializable: ^4.1.0
build_runner: ^2.0.3
```

**Comment by kevmoo** [comment]
Please share the generated code before and after you add the `fromJson` bit.

FYI: the generator does pay attention to `fromJson` in some cases.
