### ISSUE TITLE
Ignore nullable fields instead of throwing an exception

### ISSUE THREAD

**Issue by Himanshuarora97** [google/json_serializable.dart#899]
Suppose there are two models **User** and **City**  

    @JsonSerializable()
    class User {
        int id;
        String name;
        City? city;
    }

    @JsonSerializable()
    class City {
       int id;
       String name;
    }

Now suppose during API call, we've got a user model but in the city object model, we only get **id** not **name**. Something like this

    {
        "id": 5,
        "name": "Matthew",
        "city": {
            "id": 12
        }
    }

But due to the default nature of json_serializable and json_annotation.
This JSON is not mapped to the User model, during mapping, it throws the exception.  
*type Null is not a subtype of type String. (because here **name** key is missing in city object)*  

But as we already declared in the User object that City is optional, I wanted that it should parse the User JSON with the city as null.

**Dart version: 2.12.3**
**json_serializable: 4.1.0**

**Comment by Himanshuarora97** [comment]
In native iOS development, I've been this library [Unbox](https://github.com/JohnSundell/Unbox), this works if something wrong while parsing the Optional field, it returns null (we can explicitly mention using `try? ` and `try` during unboxing)

**Comment by kevmoo** [comment]
@Himanshuarora97 – it doesn't matter that city is optional. When city appears, it is decoded. And it's missing the required `name` value.

Do you expect that city is not decoded if it's missing the name field?

**Comment by Himanshuarora97** [comment]
@kevmoo Well, we've marked the city as optional, if in any case, the decoding fails then the city field should be null instead of throwing an exception.
Because I've been using the Unbox library in native iOS. where I can clearly mark which properties I expect to be parsed.

**Comment by kevmoo** [comment]
This is a tricky one. Your use case is special.

You may be better off just hand-writing this case. We're trying to find a balance between flexibility and complexity with this package.
