### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<Object>

### ISSUE THREAD

**Issue by huylethanh** [google/json_serializable.dart#904]
I am using json_annotation: ^4.0.1 and got the issue when parsing a list of object
Code generated:
```
return WorkOrderWithComplianceResponse(
 workCompliances: json['workCompliances']
        ?.map((e) => e == null
            ? null
            : WorkCompliance.fromJson(e as Map<String, dynamic>))
        ?.toList()
);
```

it throws exception -> type 'List<dynamic>' is not a subtype of type 'List<WorkCompliance>?'
when i add after toList() cast<WorkCompliance>(). it works

full code changes

```
return WorkOrderWithComplianceResponse(
 workCompliances: json['workCompliances']
        ?.map((e) => e == null
            ? null
            : WorkCompliance.fromJson(e as Map<String, dynamic>))
        ?.toList().cast<WorkCompliance>()
);
```

Class
```

@JsonSerializable(explicitToJson: true)
class WorkOrderWithComplianceResponse extends Entity {
  final List<WorkCompliance>? workCompliances;
}

WorkOrderWithComplianceResponse(
      {String? id,
      String? name,)
      : super(id: id, name: name);

  factory WorkOrderWithComplianceResponse.fromJson(Map<String, dynamic> json) =>
      _$WorkOrderWithComplianceResponseFromJson(json);
  Map<String, dynamic> toJson() =>
      _$WorkOrderWithComplianceResponseToJson(this);
```

Can you please take a look at the issue?

update:

I take a look at the other generated codes in my project (because i see some objects can be parsed from json) and see they are different:

Some class it generate the code like  this.
```
 workCompliances: (json['workCompliances'] as List<dynamic>?)
        ?.map((e) => WorkCompliance.fromJson(e as Map<String, dynamic>))
        .toList(),
```
It has a cast to List<dynamic> then do the map. The issue one does the map without cast to List<dynamic>.

I tried to change to the code like above and it works.

**Comment by huylethanh** [comment]
Sorry, someone on the team commit the wrong one.

**Comment by dalton5** [comment]
I have the same issue with version 4.1.3. If I downgrade to 4.1.1 it works. WHich version is the good one?
