### ISSUE TITLE
Dart 2.13 typedef?

### ISSUE THREAD

**Issue by PiN73** [google/json_serializable.dart#905]
Type aliases are [introduced](https://medium.com/dartlang/announcing-dart-2-13-c6d547b57067) in Dart 2.13.

Is it recommended to use this typedef with json_serializable now?

```dart
typedef Json = Map<String, dynamic>;
```

**Comment by kevmoo** [comment]
Ooo. It'd be good to check to make sure this works! Anyone want to experiment?

**Comment by kevmoo** [comment]
Are you broken by this?

**Comment by PiN73** [comment]
No, I have no problems, but want to know, what is best practice now. For example, should typedefs be declared in package code or in my app code?

**Comment by kevmoo** [comment]
You can declare them anywhere you want.

I probably won't be adding typedefs to `json_annotation`.

I'm going to mark this for investigation to add a test to make sure typedefs work with this package, though!

**Comment by kevmoo** [comment]
I just did a bit of hacking and everything seems to work great!

Types defined by aliases are parsed and used correctly. The generator doesn't use the typedef in the generated code – which I think is fine.

Going to close this out...unless specific bugs come up...

**Comment by dkbast** [comment]
@kevmoo Using typedef does indeed work great - I was just writing a bunch of classes and each time I typed out Map<String, dynamic> switched to my own definition and that was good, but I was wondering why we don't have this in dart:convert or here in this package?

Maybe we could add a typedef for this, calling it JsonMap to be explicit about it being a Map and not a list or Object which would probably also be valid json? 

May I ask whats the reasoning behind not adding typedefs to json_annotation or this package in general?
