### ISSUE TITLE
DateTime converter doesn't work

### ISSUE THREAD

**Issue by enyo** [google/json_serializable.dart#908]
I am using `json_serializable` to serialize objects that are meant to be inserted into a mongodb. The mongodb library uses DateTime when inserting or reading dates from the database, so I wrote a simple `DateTimeConverter`:

```dart
class DateTimeConverter implements JsonConverter<DateTime, DateTime> {
  const DateTimeConverter();

  @override
  DateTime fromJson(DateTime value) => value;

  @override
  DateTime toJson(DateTime value) => value;
}
```

The problem is, that the generated `fromJson` doesn't seem to use this converter:

```dart
Submission _$SubmissionFromJson(Map<String, dynamic> json) {
  return Submission(
    // ...
    time: json['time'] == null ? null : DateTime.parse(json['time'] as String),
    // ...
  );
}
```

Here it uses `DateTime.parse` instead of `const DateTimeConverter().fromJson`

**`toJson`** works fine however:

```dart
writeNotNull('time', const DateTimeConverter().toJson(instance.time));
```

**Comment by enyo** [comment]
I found a workaround for now: on my `DateTimeConverter` I created a **static** function:

```dart
  static DateTime tmpFromJson(DateTime value) => value;
```

and I then used it in my message:

```dart
  @JsonKey(fromJson: DateTimeConverter.tmpFromJson)
  @DateTimeConverter()
  final DateTime time;
```

This generates the correct output as expected:

```dart
Submission _$SubmissionFromJson(Map<String, dynamic> json) {
  return Submission(
    // ...
    time: DateTimeConverter.tmpFromJson(json['time'] as DateTime),
    // ...
  );
}

```

**Comment by kevmoo** [comment]
So you DON'T want to generate valid JSON output? You just want to send a map to mongo – with native Dart objects in it?

If it works for you!

**Comment by enyo** [comment]
@kevmoo it's not as much that I don't _want_ to, it's just the way the mongo db library expects the data to be provided: as a simple Map. (It's the same with the document IDs). I just want proper typing for it, that's why I use a serialisation library.

I think this is still an issue with the library. Maybe my use case is a bit strange, but if I provide a converter, I would assume that it's going to be used. There are examples of valid JSON that I could want to serialise which would also break.

**Comment by kevmoo** [comment]
Have you tried using https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html ?

**Comment by YouSour** [comment]
@enyo hi , can you show me your full code with data class ? i got  this problem too , i try to get a data type DateTime from mongodb i get this error : 
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'DateTime' is not a subtype of type 'String?' in type cast
#0      _$SaleOrderModelFromJson
package:restaurant_app/…/order/sale_order_model.g.dart:20
#1      new SaleOrderModel.fromJson
package:restaurant_app/…/order/sale_order_model.dart:60
#2      SaleProvider.realTimeData.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:restaurant_app/…/providers/sale_provider.dart:47
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:390:20)
#4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#6      new List.of (dart:core-patch/array_patch.dart:50:28)
#7      Iterable.toList (dart:core/iterable.dart:366:12)
#8      SaleProvider.realTimeData.<anonymous closure>.<anonymous closure>
package:restaurant_app/…/providers/sale_provider.dart:48
#9    <…>
flutter: WebSocketException: Unsupported URL scheme ''
```

**Comment by kevmoo** [comment]
@enyo – it looks like there is already a DateTime in the source data. this package expects "real" JSON – meaning just valid JSON literals

**Comment by enyo** [comment]
@kevmoo this issue is not only related to me using dart objects instead of "real" JSON and I think this should be reopened.

Let's say, as an example, you have a use case, where you need to serialise your `DateTime` strings in an uncommon format, like a string representing the microseconds. I think this is a completely valid and reasonable use case of the library:

```dart
class DateTimeConverter implements JsonConverter<DateTime, String> {
  const DateTimeConverter();

  @override
  DateTime fromJson(String value) => DateTime.fromMicrosecondsSinceEpoch(int.parse(value));
  @override
  String toJson(DateTime value) => value.microsecondsSinceEpoch.toString();
}

@JsonSerializable()
class Project {
  @DateTimeConverter()
  final DateTime updatedTime;

  // ...
}
```

The generated code for this looks like this:

```dart
    // ...
    updatedTime: json['updatedTime'] == null
        ? null
        : DateTime.parse(json['updatedTime'] as String),
    // ...
```

which completely bypasses the `DateTimeConverter`. So right now, you're either stuck to encode `DateTime` the way this library thinks it should be encoded, or you need to use the "hack" that I posted before.
