### ISSUE TITLE
How to add new non-nullable fields to existing models

### ISSUE THREAD

**Issue by timosturm** [google/json_serializable.dart#921]
If we look at the example code:
~~~~dart
Person _$PersonFromJson(Map<String, dynamic> json) {
  return Person(
    json['firstName'] as String,
    json['lastName'] as String,
  );
}
~~~~

we can see, that non-nullable fields are cast to a non-nullable type. If the model was to be extended by a new field this cast would fail because it is missing in the json. Is there a straightforward way to handle this case assuming a valid default value exists for such fields? Or would you have to edit the `json` before attempting to parse it each time?

**Comment by chaochaox1990** [comment]
add one

**Comment by kevmoo** [comment]
With v5 of json_serializable, you can use default values in the constructor and "the right thing will happen"
