### ISSUE TITLE
type 'UnspecifiedInvalidResult' is not a subtype of type 'LibraryElementResult' in type cast

### ISSUE THREAD

**Issue by Vofchuk** [google/json_serializable.dart#924]
Im tring to run the package on my project, but I'm getting this error and I can't understand why...

`Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "windows_x64"`

```Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (2 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0```

**Comment by kevmoo** [comment]
Would you run the build command with --verbose?

**Comment by geoffreylzf** [comment]
![asasasas](https://user-images.githubusercontent.com/37864004/128680183-a0af3229-ee4c-496c-b559-e9b8ec87fef8.JPG)

**Comment by kevmoo** [comment]
What's the contents of pubspec.lock?

**Comment by JKris95** [comment]
I was dealing with the same issue so I decided to downgrade to version ^4.1.0 of json_serializable and a compatible version of json_annotation. With these constraints the build was successful again. After this I ran
`flutter pub upgrade --major-versions` 
which updated the version constraints to json_annotation: ^4.4.0 and json_serializable: ^6.1.1. The build is now also successful with these constraints. Not sure what caused the issue in the first place but downgrading followed by upgrading seems to have solved it for me. I'm using the following flutter version
`flutter --version`
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (7 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

**Comment by subzero911** [comment]
Same issue.
I had a project containing built_value and kiwi_generator
after I removed built_value and added json_serializable, everything got broken.

Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (7 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

**Comment by kevmoo** [comment]
FYI @jakemac53 @natebosch 

![image](https://user-images.githubusercontent.com/17034/146817939-679b8b1c-41b1-435c-b9a2-826346bb6079.png)

Maybe we could improve the error if the cast fails here?

**Comment by subzero911** [comment]
Yeah, that would be great.
Currently the error makes little sense

**Comment by natebosch** [comment]
> Maybe we could improve the error if the cast fails here?

Do you have a suggestion for a more actionable error? Do we have any idea how this comes up?

**Comment by tarektaamali** [comment]
Same issue happened in my project after upgrade flutter from 2.2.3 to 2.8.2 .

**Comment by dev-abdiel** [comment]
I was having the same issue, my solution is to delete the `pubspec.lock` file and then `run flutter pub get`, after that just ran the command `flutter pub run build_runner build` or `flutter run build_runner build --delete-conflicting-outputs`.

**Comment by slightfoot** [comment]
@kevmoo just had this problem after updating to Flutter 2.10. Solved it by adding dependency on source_gen to force it to the latest compatible version 1.2.1. Might be an idea to add that to the json_serializable pubspec.
