### ISSUE TITLE
how could i change anymap to true 

### ISSUE THREAD

**Issue by hashoome132** [google/json_serializable.dart#925]
flutter --version`,

just i want to know how could i change anymap to true because i have this issue
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'BannerModel'

**Comment by kevmoo** [comment]
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/anyMap.html

https://pub.dev/packages/json_serializable#annotation-values

You have to show me your code for me to understand what you're trying to do.
