### ISSUE TITLE
[Request] Break references (deep copy) in toJson.

### ISSUE THREAD

**Issue by bernaferrari** [google/json_serializable.dart#926]
When calling `toJson()` in a field that is a list (or a map), it keeps the same reference. That is tricky, since `json = node.toJSON(); node.children = ['1']` affects the json's value. I would love to have a compiler option to break these references, so a deep copy/deep clone can easily be made using json_serializable, instead of `decodeJson(encodeJson(json))` which is a popular, less efficient, solution.

current input:
```dart
@JsonSerializable()
class Frame {
  final String id;
  final List<String> children;
}
```
current output:
```dart
Map<String, dynamic> _$FrameToJson(Frame instance) => <String, dynamic>{
      'id': instance.id,
      'children': instance.children,
}
```
desired output: 
```dart
'children': instance.children.toList()
```

**Comment by SwissCheese5** [comment]
We really need this functionality on our team, it will help us implement our undo/redo system properly.

**Comment by kevmoo** [comment]
Are you sure your use case is `List<String>` and not `List<CustomObject>`?

Have you looked at https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html ?

**Comment by bernaferrari** [comment]
Yes, we have that. However, it only adds `toList` for nested json objects.

Example
```dart
'reactions': instance.reactions.map((e) => e.toJson()).toList(), // Ok!
'children': instance.children, // I want .toList() here too!
```

**Comment by kevmoo** [comment]
Ah! You're looking for features this package is not designed for.

I get your desire for deep copy, but that's getting out of scope for what we're trying to do here.
