### ISSUE TITLE
option like field_rename for enum

### ISSUE THREAD

**Issue by ashinan** [google/json_serializable.dart#929]
As far as I can tell, current implementation converts each name of enum value directly to string.
For now, I am wring `@JsonValue(...)` for every enum value because I always prefer kebab not only field name but also enum value string like this:

```
enum Value {
   @JsonValue('one-value')
   OneValue.
   @JsonValue('two-value')
   TwoValue.
}
```

It would be nice to have an option like `field_rename` for enum values(maybe `enum_rename` or `enum_value_rename` would be good).

**Comment by kevmoo** [comment]
Fixed in https://github.com/google/json_serializable.dart/commit/3a0cc4317883b2c45b87e8630d20ffb626cab5d0
