### ISSUE TITLE
New release for json_annotation package

### ISSUE THREAD

**Issue by ashinan** [google/json_serializable.dart#930]
The latest release for json_annotation package is 4.0.1 which is missing https://github.com/google/json_serializable.dart/commit/410988e92b302014dd41304e32622bec8b57ee0d.
This bug causes unavoidable build failure when using `JsonConverter` so I think this is urgent.

**Comment by kevmoo** [comment]
Working on it - https://github.com/google/json_serializable.dart/pull/937

If you `implement` `JsonConverter` instead of extending it, you should be fine!

**Comment by kevmoo** [comment]
Done: https://github.com/google/json_serializable.dart/commit/6cb51dbacfbebe4a570b8a891732de9109fbce40
