### ISSUE TITLE
Package generates incorrectly named parser for private classes

### ISSUE THREAD

**Issue by DreadBoy** [google/json_serializable.dart#931]
Consider class
```dart
@JsonSerializable(createToJson: false)
class _Submodule {
  final int id;
  final String name;

  _Submodule(this.id, this.name);

  static _Submodule fromJson(Map<String, dynamic> json) =>
      _$_SubmoduleFromJson(json);
}
```

We often use private classes where we don't care to expose JSON structure to app (because it's too complex or we need to read single property nested deep inside JSON structure).

Dart issues warning "Name non-constant identifiers using lowerCamelCase." for method `_$_SubmoduleFromJson`. Our policy is to either suppress or fix any warning but we can't do either in that case. Is there any workaround we can use?

```
Flutter 2.0.4 • channel unknown • unknown source
Framework • revision b1395592de (3 months ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```

**Comment by kevmoo** [comment]
This was fixed in `json_serializable` v5
