### ISSUE TITLE
[Request]: Being able to define a JsonSerializable with default JsonConverts

### ISSUE THREAD

**Issue by SimoneBressan** [google/json_serializable.dart#932]
The ideal would be to define its own JsonSerializable and define all the converters for that JsonSerializable without having to repeat it for each class

1. Define your JsonConverts
2. Define your JsonSerializable
3. Annotate all your JsonConverts to your JsonSerializable class
4. Use your JsonSerializable class for your json class classes with all its converters

```dart
@MyJsonSerializable()
class MyJson extends StreetAddress {
  final DateTime dateTime;

  MyJson({required this.dateTime});

  factory MyJson.fromJson(Map<String, dynamic> json) => _$MyJsonFromJson(json);

  Map<String, dynamic> toJson() => _$MyJsonToJson(this);
}

@MyDateTimeConverter()
// And more JsonConverts ...
class MyJsonSerializable extends JsonSerializable {
  @MyDateTimeConverter()
  const MyJsonSerializable();
}

class MyDateTimeConverter implements JsonConverter<DateTime, int> {
  const MyDateTimeConverter();

  @override
  DateTime fromJson(int json) => throw UnimplementedError();

  @override
  int toJson(DateTime object) => throw UnimplementedError();
}
```

It would be very effective for not having to rewrite the same JsonConverters for all your classes

Thank you very much for all the work you have done

**Comment by kevmoo** [comment]
You *can* do this, but you need to create your own builder.

You need to create an instance of `JsonSerializableGenerator` using your own `TypeHelper` classes.

It's a pretty specialized and rare thing, so it's not suggested. It's also not documented.

Look at 

https://github.com/dart-lang/source_gen/tree/master/example
https://github.com/google/json_serializable.dart/blob/master/json_serializable/lib/builder.dart
https://github.com/google/json_serializable.dart/blob/master/json_serializable/lib/src/json_part_builder.dart
https://pub.dev/documentation/json_serializable/latest/type_helper/type_helper-library.html
