### ISSUE TITLE
Possible to have multiple serializers?

### ISSUE THREAD

**Issue by jimmyff** [google/json_serializable.dart#933]
Hi, I'm coming from using `built_value` but thinking this is the more darty solution to serialization.

I have a have a number of models that I serialize/deserialize from either firestore or pubsub. Due to Firestore having a none-standard DateTime format (Timezone) I currently handle them differently, so I have two sets of serializers. Is there a solution for this scenario using `json_serializable`? I see I can specify a toJson/fromJson in `JsonKey` but that would tie the serializing to the class and not let it work for two different targets.

I guess one solution is to make all my classes serialize DateTimes as a Timestamp() but that feels a little hacky.

Thanks

**Comment by kevmoo** [comment]
You can create a converter that overrides what's in the box.

See https://github.com/google/json_serializable.dart/blob/6e7b1eb2b7319a8897f30d18838e6cd199e342b3/example/lib/json_converter_example.dart#L24-L60
