### ISSUE TITLE
Serialize/deserialize numeric values without losing precision

### ISSUE THREAD

**Issue by pubiqq** [google/json_serializable.dart#943]
Is there any way to serialize/deserialize numbers with an arbitrary number of digits without losing precision? I mean the case when the data comes _in a numeric format_, like this:

```
{
  "total": 0.123456789012345678901234567890
}
```

**Comment by kevmoo** [comment]
You need a data type that stores arbitrary precision doubles when you deserialize.

When you serialize, to support valid JSON, you could use a String.

**Comment by pubiqq** [comment]
Oh, my bad! I thought the library is also responsible for parsing JSON, apologies.
