### ISSUE TITLE
flutter_test from sdk is incompatible with json_serializable 5.0.0

### ISSUE THREAD

**Issue by oysterpack** [google/json_serializable.dart#949]
> Because every version of flutter_test from sdk depends on meta 1.3.0 and analyzer >=2.0.0 depends on meta ^1.7.0, flutter_test from sdk is incompatible with analyzer >=2.0.0.
And because json_serializable >=5.0.0 depends on analyzer ^2.0.0, flutter_test from sdk is incompatible with json_serializable >=5.0.0.
So, because oysterpack_clubs depends on both json_serializable ^5.0.0 and flutter_test any from sdk, version solving failed.

> Because every version of flutter_test from sdk depends on meta 1.3.0 and json_annotation >=4.1.0 depends on meta ^1.4.0, flutter_test from sdk is incompatible with json_annotation >=4.1.0.
So, because oysterpack_clubs depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.

**Comment by kevmoo** [comment]
Yup. See https://github.com/google/json_serializable.dart/issues/944

**Comment by kevmoo** [comment]
Flutter 2.5 stable is out!
