### ISSUE TITLE
Use DateTime.tryParse if DateTime field is nullable

### ISSUE THREAD

**Issue by Aqua-Ye** [google/json_serializable.dart#953]
I have a model with an optional DateTime property: `DateTime? watchedAt`. 
Currently it generates the following code:

```
    watchedAt: json['watched_at'] == null
        ? null
        : DateTime.parse(json['watched_at'] as String),
```

It would be better if the generated code is using `tryParse` instead of `parse` to prevent having an exception when the string can't be parsed.

**Comment by kevmoo** [comment]
This is by design. We want to error out of the value is incorrect.

If you want a different behavior, you can create your own converter.

See https://github.com/google/json_serializable.dart/blob/master/example/lib/json_converter_example.dart
