### ISSUE TITLE
factory fromJson to not generate nullable parse;

### ISSUE THREAD

**Issue by nagringapp** [google/json_serializable.dart#963]
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

  json_annotation: ^4.0.1

Factory do not generate file for nullable parameters: 
  factory UserSettingsModel.fromJson(Map<String, dynamic>? json) => _$UserSettingsModelFromJson(json);

Generated:

UserSettingsModel _$UserSettingsModelFromJson(Map<String, dynamic> json) {

instead of 

UserSettingsModel _$UserSettingsModelFromJson(Map<String, dynamic>? json) {

**Comment by kevmoo** [comment]
Yup! We assume you give us a non-null map. You need to update the code you use to bind to this function to handle null however you like!
