### ISSUE TITLE
how to work with IconData ?

### ISSUE THREAD

**Issue by YouSour** [google/json_serializable.dart#964]
hi , how can i work with IconData ? i can't find any example related to this ? thank in advance
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'select_option_model.g.dart';

@JsonSerializable(createToJson: false)
class SelectOptionModel {
  @JsonKey(disallowNullValue: true)
  final IconData iconName;
  final String label;
  final dynamic value;

  const SelectOptionModel({
    this.iconName,
    @required this.label,
    @required this.value,
  });

  factory SelectOptionModel.fromJson(Map<String, dynamic> data) =>
      _$SelectOptionModelFromJson(data);
}
```

**Comment by kevmoo** [comment]
You have to create a `Converter` for a type you don't control.

See https://github.com/google/json_serializable.dart/blob/master/example/lib/json_converter_example.dart

Or you could specify functions for `toJson` and `fromJson` in `JsonKey`

**Comment by YouSour** [comment]
@kevmoo thank you

**Comment by techouse** [comment]
Make sure to compile your app store bundle with `--no-tree-shake-icons` in this case, otherwise it will fail to build.
