### ISSUE TITLE
Map<String, String?> in a generated file ended up as Map<String, String>

### ISSUE THREAD

**Issue by matthewfx** [google/json_serializable.dart#965]
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

Map<String, String?> in a generated file ended up as Map<String, String>.

When I change the generated file manually JSON serialization works fine for null values in the map.

Thanks!

**Comment by kevmoo** [comment]
I need more info here. Can you create a minimal repro with source + generated code? And the input?

**Comment by Silver-Fullbuster** [comment]
## Sample Code
```dart
import 'package:json_annotation/json_annotation.dart';

part 'json_test.g.dart';

@JsonSerializable()
class JsonTest {
  JsonTest(this.stringMap);

  Map<String, String?> stringMap;

  factory JsonTest.fromJson(Map<String, dynamic> json) =>
      _$JsonTestFromJson(json);

  Map<String, dynamic> toJson() => _$JsonTestToJson(this);
}
```

## Generated Code
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_test.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

JsonTest _$JsonTestFromJson(Map<String, dynamic> json) {
  return JsonTest(
    Map<String, String>.from(json['stringMap'] as Map),
  );
}

Map<String, dynamic> _$JsonTestToJson(JsonTest instance) => <String, dynamic>{
      'stringMap': instance.stringMap,
    };
```

As you can see, Map<String, String?> is being casted as Map<String, String> by the `_$JsonTestFromJson` function

**Comment by kevmoo** [comment]
I'll digg.

I have an almost IDENTICAL test case that seems to work fine: https://github.com/google/json_serializable.dart/blob/cccbf7251045c8cdc1370e03c4a6fb8e3426df13/json_serializable/test/supported_types/input.type_map.g.dart#L4914-L4924

**Comment by kevmoo** [comment]
@Silver-Fullbuster – which version of json_serialiable are you on?

**Comment by Silver-Fullbuster** [comment]
I'm on 4.1.4, can't upgrade to 5.0 due to flutter stable from the looks of it.

**Comment by kevmoo** [comment]
There's your issue. You need to be on v5 and all will be good.
