### ISSUE TITLE
Getters annotated with `@JsonKey` do not end up in the generated `toJson` method.

### ISSUE THREAD

**Issue by emme1444** [google/json_serializable.dart#968]
Given the following code and invoking, `dart run build_runner build --delete-conflicting-outputs`

```dart
import 'package:json_annotation/json_annotation.dart';

part 'hello.g.dart';

@JsonSerializable()
class Hello {
  @JsonKey()
  String get hello => "hey";
}
```

I get the following generated `toJson` method:

```dart
part of 'hello.dart';

...

Map<String, dynamic> _$HelloToJson(Hello instance) => <String, dynamic>{};
```

I would expect the `toJson` method to include the `hello` key for the json output.

From what I've read and seen this should be possible right? Also the target of the `@JsonKey` annotation is fields and getters. So... yeah.

Am I doing something wrong? What?

Thanks!

---
`dart --version`:
```sh
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"
```

**Comment by kevmoo** [comment]
You need to mark the class with `@JsonSerializable(createFactory: false)`.

There is no way to create a factor for the class with the provided `hello` field, so it skips it.
