### ISSUE TITLE
Expose utilities to allow other code-generators to know how an object is serialized

### ISSUE THREAD

**Issue by rrousselGit** [google/json_serializable.dart#972]
Some code-generators may take serializable classes as input, but want to defer the process of generating fromJson/toJson to the user (due to the sheer complexity of the feature), in which case the recommendation is typically to use json_serializable.

But in some use-cases, a code-generators may need extra informations on how an object is serialized. I have identified the following cases:

- generators may want to get the list of serializable properties of an object (taking `ignore` into account)
- they may also want to know the "json" name of a property (as in, a property `fullName` may be serialized as `full_name`)
- they may need the ability to serialize only one specific property at a time (while still applying converters/defaults/...)

For example, from the following class:

```dart
@JsonSerializable(fieldRename: FieldRename.snake)
@MyCodeGeneratorAnnotation()
class Person {
  Person(...)
  Person.fromJson(..)
  toJson(...)

  final String firstName;
  final String lastName;
}
```

Then a separate code-generator may want to generate methods like:

```dart
Future<void> updateFirstName(String newFirstName) async {
  // partial serialization of the Person instance
  await httpClient.post('/api/set', { 'first_name': newFirstName }); 
}

Future<List<Person>> findPersonWithFirstName(String firstName) {
  // understood that Person is using fieldRename, therefore "firstName" in the query was renamed as "first_name"
  await httpClient.get('/api/where?first_name=$firstName');
}
```

**Comment by rrousselGit** [comment]
One solution I have in mind is generating a static map for classes annotated with `@JsonSerializable`, which would list the properties and associate them with a new name and a toJson method:

```dart
@JsonSerializable(fieldRename: FieldRename.snake)
class Person {
...

  static const jsonProperties = _$PersonJsonProperties;
}
```

which would allow:

```dart
void main() {
  print(Person.jsonProperties['firstName'].name) // first_name
  print(Person.jsonProperties['firstName'].toJson(Person(...)) // encode "firstName". So here, since it's a String, simply returns it.
}
```

**Comment by kevmoo** [comment]
Ooo...this is...complex.

This is the type of thing we should have in https://github.com/google/source_helper.dart/

Would be happy to chat about how to collaborate here...

**Comment by rrousselGit** [comment]
I'll admit, I am not quite sure what source_helper has to do with this issue. Do you mind explaining? 🙏

**Comment by kevmoo** [comment]
> I'll admit, I am not quite sure what source_helper has to do with this issue. Do you mind explaining? 🙏

Sorry. `source_helper` is where I'm trying to put things that could be used by other generators.

I've started pulling shared code there from json_serializable and https://github.com/kevmoo/build_cli

This seems like the type of thing that could be shared – right?

**Comment by rrousselGit** [comment]
I'm not sure. I don't really see what could be shared, since the problem seems to be tightly coupled with json_annotation

What did you have in mind?

**Comment by kevmoo** [comment]
There are the raw inputs: field/property definitions + constructors.

Then there may be logic laid on top of those to filter/rename/etc.

Then a tool to generate constructor invocations.

...something like that?

**Comment by rrousselGit** [comment]
Indeed, but how would you make source_helper aware of FieldRename and other similar things?

**Comment by kevmoo** [comment]
@rrousselGit – need to ponder that. Maybe hoist it out and make it pluggable. 🤔

**Comment by rrousselGit** [comment]
Rather than exposing functions that code generators need to import, what do you think about generating metadatas?

Since we can control the order in which code genestors are executed, we could explicitly say "my generator needs to run after json_serializable".
Then that generator will be able to see the metadatas generated by json_serializable

**Comment by rrousselGit** [comment]
:wave: @kevmoo 

I've started working on this and managed to generate a `Map<String, String>` with the desired metadata.

An example would be:

```dart
final _$PersonMeta = <String, String>{
  'firstName': 'firstName',
  'lastName': 'lastName',
  'middleName': 'middleName',
  'dateOfBirth': 'dateOfBirth',
  'house': r'$house',
  'order': 'order',
  'customOrders': 'customOrders',
  'houseMap': 'houseMap',
  'categoryCounts': 'categoryCounts',
};

Map<String, dynamic> _$PersonToJson(Person instance) => <String, dynamic>{
  <typical toJson code>
}
```


One thing that I wonder though is: 

Do you know if there is a way to generate this piece of code _only_ if another code-generator needs it?

I suppose we could technically do:

```dart
@MyGenerator()
@JsonSerializable(generateMetadata: true)
class Model {...}
```

but I wonder if there's a way to avoid that flag (as it sounds pretty error-prone).

**Comment by kevmoo** [comment]
> Do you know if there is a way to generate this piece of code only if another code-generator needs it?

@rrousselGit – ugh. Not really. You'd like need to add another annotation or something...

**Comment by rrousselGit** [comment]
Thinking about it, I think that's not too bad. The config could default to false, and folks can enable the config globally in the build.yaml file
