### ISSUE TITLE
Error when generating double json value

### ISSUE THREAD

**Issue by UMUTARPT** [google/json_serializable.dart#976]
When I use https://app.quicktype.io/ website to generate json to dart. It gives correct variables with double type. But when I use json_serializable it gives int type when it needs to give double type. 

Thus it gives this error: "Expected a value of type 'int?', but got one of type 'double'"

My issue is: Sometimes with big data it doesn't generate double type when it needs to. Instead gives int type. Example value: 187.78

**Comment by kevmoo** [comment]
I need to see your input class to see what's going on.

We don't have any relationship with the quicktype app

**Comment by shawnlauzon** [comment]
Let me know if I should created another issue. Since this was never resolved, I thought would be better to reuse this.

The generated code is casting as an int when it should be casting as a double. Here is my data object:
```
@JsonSerializable()
class Author extends Equatable {
  const Author({required this.username, required this.reputation});

  final String username;
  final double reputation;

  factory Author.fromJson(Map<String, dynamic> json) => _$AuthorFromJson(json);

  Map<String, dynamic> toJson() => _$AuthorToJson(this);

  @override
  List<Object> get props => [username, reputation];
}
```

And the generated code:
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'author.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Author _$AuthorFromJson(Map<String, dynamic> json) => Author(
      username: json['username'] as String,
      reputation: json['reputation'] as int, // <-- problem here "The argument type 'int' can't be assigned to the parameter type 'double'."
    );

Map<String, dynamic> _$AuthorToJson(Author instance) => <String, dynamic>{
      'username': instance.username,
      'reputation': instance.reputation,
    };
```

**Comment by shawnlauzon** [comment]
Hmm, I don't think I changed anything, but now the generated code is correct, really weird.

```
Author _$AuthorFromJson(Map<String, dynamic> json) => Author(
      username: json['username'] as String,
      reputation: (json['reputation'] as num).toDouble(),
    );
```

**Comment by shawnlauzon** [comment]
Hmm, I might have done a `pub get` but I didn't change the version, it's been `json_serializable: ^5.0.1` the whole time

**Comment by kevmoo** [comment]
If the type is changing around – that's likely a bug in pkg:analyzer

**Comment by shawnlauzon** [comment]
Yeah, it's not the first place either. There's another where it's not calling `toJson` correctly on an embedded object. Luckily everything can be worked around with `fromJson` and `toJson` @JsonKey annotation.

**Comment by kevmoo** [comment]
> Yeah, it's not the first place either. There's another where it's not calling `toJson` correctly on an embedded object. Luckily everything can be worked around with `fromJson` and `toJson` @jsonkey annotation.

Do you have an issue open on that?

**Comment by shawnlauzon** [comment]
No I don't. I'll create one now.

**Comment by shawnlauzon** [comment]
See issue #983
