### ISSUE TITLE
Integer (or number) cannot be deserialized if it's a String

### ISSUE THREAD

**Issue by dovahkiin98** [google/json_serializable.dart#988]
Consider this object

```json
{
 "id": "1"
}
```

If I write the object in Dart as the following

```dart
class Obj { int id; }
```

The serializer will make the `fromJson` code try to cast `json['id'] as int`, and not consider the alternative, that it might be a string value of a number, or even a double maybe.

Why doesn't it do something like

```dart
id = json['id] is int? json['id'] as int : int.parse(json['id'].toString());
```

This will insure that whatever value `id` is, it will either return a valid number, or a null/default value.

**Comment by kevmoo** [comment]
Because we try to keep things simple and predictable.

If you want to support String-to-int, you can use a `JsonConverter` or to/from JSON on `JsonKey`.

See https://github.com/google/json_serializable.dart/blob/master/example/lib/example.dart#L51 for an example
