### ISSUE TITLE
type 'UnspecifiedInvalidResult' is not a subtype of type 'LibraryElementResult' in type cast

### ISSUE THREAD

**Issue by azreddy84** [google/json_serializable.dart#993]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include the entire output
of either `dart --version` or `flutter --version`, depending on what
you're using.

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

**Comment by kevmoo** [comment]
Please. include a stack trace, the versions of the package you're using, etc.
